- examples/question-answering/requirements.txt
- examples/question-answering/run_qa.py
- examples/text-classification/run_glue.py
- tests/example_diff/run_glue.txt
- tests/example_diff/run_qa.txt
Update example diff files. Tests failed because they were not updated after last modifications.
> Update example diff files

- optimum/habana/version.py
The version of the package is updated to 1.0.1.
> Update package version

- README.md
- setup.py
Fixes the broken image in [PyPI](https://pypi.org/project/optimum-habana/).
> Update image link

- .github/workflows/slow_tests.yml
- tests/ci/albert_xxl_1x.sh
- tests/test_examples.py
This PR adds ALBERT XXL 1x to non-regression tests on Saturdays.
> Add ALBERT XXL 1x to non-regression tests every Saturday

- optimum/habana/trainer.py
- optimum/habana/training_args.py
`--use_lazy_mode` and/or `--gaudi_config_name` are accepted when `--use_habana` is not given. This should not happen and an error is now raised if it does.
> Raise error if --use_lazy_mode or --gaudi_config_name is given while --use_habana is not

- examples/language-modeling/run_clm.py
- tests/example_diff/run_clm.txt
The diff file for assessing whether or not run_clm.py is up to date was missing.
> Add diff file for run_clm.py

- Makefile
- examples/gaudi_spawn.py
- examples/language-modeling/run_clm.py
- examples/question-answering/run_qa.py
- examples/text-classification/README.md
- examples/text-classification/run_glue.py
- optimum/habana/distributed/distributed_runner.py
- optimum/habana/gradient_checkpointing.py
- optimum/habana/trainer.py
- optimum/habana/training_args.py
- setup.py
- tests/example_diff/run_clm.txt
- tests/example_diff/run_glue.txt
- tests/example_diff/run_qa.txt
- tests/test_trainer.py
- tests/test_trainer_distributed.py
Update the repo with Transformers 4.20.0 changes.
> Update with Transformers 4.20.0 changes

- Makefile
- tests/test_examples.py
This PR removes the slow test assessing the performance of T5 on a summarization task. This test makes the AWS instance used for CI freeze. I have not been able to gather more useful information yet. I will add T5 back when this is solved or when we move CI to our on-prem machine.
> Remove T5 from slow tests (temporary fix for CI)

- .github/workflows/fast_tests.yml
- .github/workflows/slow_tests.yml
- examples/gaudi_spawn.py
- optimum/habana/trainer.py
- optimum/habana/training_args.py
- setup.py
- tests/baselines/albert_large_v2.json
- tests/baselines/albert_xxlarge_v1.json
- tests/baselines/bert_base_uncased.json
- tests/baselines/bert_large_uncased_whole_word_masking.json
- tests/baselines/distilbert_base_uncased.json
- tests/baselines/gpt2.json
- tests/baselines/roberta_base.json
- tests/baselines/roberta_large.json
- tests/baselines/t5_small.json
- tests/configs/gaudi_config_trainer_test.json
- tests/test_trainer.py
- tests/test_trainer_distributed.py
This PR adds support for SynapseAI 1.5.0:
- remove the call to `load_habana_module` as it is not necessary anymore,
- call `initialize_distributed_hpu` to simplify the initialization of multi-HPUs configuration,
- uncomment some tests in `tests/test_trainer.py` since the behaviour of `torch.nn.functional.mse_loss` on HPU has been fixed,
- update baselines for CI slow tests,
- update AMI id in AWS instances used for CI.
> Add support for SynapseAI 1.5.0

- tests/baselines/bert_base_uncased.json
BERT base 8x on MRPC takes slightly longer to complete in CI for no obvious reason. Reverting back the training time baseline to its former value.
I will try again when CI is moved away from AWS.
> Temporary fix for CI

- optimum/habana/__init__.py
- optimum/habana/version.py
- setup.py
The dev version is bumped since v1.1.0 has just been released.
A quality section is also added to `setup.py` to install packages used for formatting the code.
> Bump version after release

- docs/source/index.mdx
Fixes the rendering of some emojis in the supported models table.
> Fix emojis in table

- docs/source/_toctree.yml
- docs/source/distributed.mdx
- docs/source/quickstart.mdx
- docs/source/trainer.mdx
More docs with GaudiTrainer, Distributed, and some minor changes
> Add more docs 

- setup.py
This PR enables to install `hf-doc-builder` from source to have [this fix](https://github.com/huggingface/doc-builder/pull/270) needed for building the documentation of namespace packages.
> Install hf-doc-builder from source

- README.md
- docs/Dockerfile
- docs/source/_toctree.yml
- docs/source/accelerate_training.mdx
- docs/source/distributed.mdx
- docs/source/gaudi_config.mdx
- docs/source/index.mdx
- docs/source/quickstart.mdx
- docs/source/single_hpu.mdx
- docs/source/trainer.mdx
This PR expands the documentation of the package:
- it adds a section about `GaudiConfig` in the "Main Classes" section,
- it creates a section called "How-To Guides" where:
- the section about distributed training has been moved there,
- it adds a section about single-hpu training and about good practices for making training faster
> Expand documentation

- .github/workflows/check_code_quality.yml
This PR changes the name of the code quality test as it appears in Github Actions and it adds the `--preview` flag to `black --check` for checking the code format.
> Refine check_code_quality.yml

- .github/workflows/build_pr_documentation.yml
- Makefile
- docs/Dockerfile
The PR doc generation would fail if the PR comes from a fork. This PR fixes that by extracting the clone URL in the GH workflow and providing it to the Dockerfile.
> Make PR doc build possible from forks

- .github/workflows/fast_tests.yml
- .github/workflows/slow_tests.yml
- optimum/habana/trainer.py
- tests/baselines/albert_large_v2.json
- tests/baselines/albert_xxlarge_v1.json
- tests/baselines/bert_base_uncased.json
- tests/baselines/bert_large_uncased_whole_word_masking.json
- tests/baselines/distilbert_base_uncased.json
- tests/baselines/gpt2.json
- tests/baselines/roberta_base.json
- tests/baselines/roberta_large.json
- tests/baselines/t5_small.json
- tests/baselines/vit_base_patch16_224_in21k.json
- tests/test_trainer.py
This PR mainly updates the CI baselines for each model on SynapseAI 1.6.0.
It also reverts to AWS for CI regression tests since our on-prem Gaudi requires a driver update.
Two tests in `test_trainer.py` have been uncommented.
> Update to SynapseAI 1.6.0

- README.md
- docs/source/_toctree.yml
- docs/source/deepspeed.mdx
- docs/source/index.mdx
- docs/source/pretraining.mdx
- examples/image-classification/README.md
- examples/language-modeling/README.md
- examples/language-modeling/run_clm.py
- examples/language-modeling/run_mlm.py
- examples/question-answering/README.md
- examples/summarization/README.md
- examples/text-classification/README.md
- examples/translation/README.md
- setup.py
This PR updates the documentation:
- Explanations about how to do pretraining are added.
- A working DeepSpeed configuration is given in the README of each example.
- Swin is added to the table of validated models.
> Improve documentation

- Makefile
- README.md
- docs/source/deepspeed.mdx
- docs/source/index.mdx
- setup.py
It is not possible to upload a wheel to PyPI when a direct dependency of the package is defined as a URL, which is the case for DeepSpeed.
Thus, in this PR, this dependency is removed and the documentation is modified accordingly to tell users how to properly install Habana DeepSpeed.
> Change the way to setup Habana DeepSpeed

- Makefile
See https://github.com/huggingface/optimum/pull/357
> Fix broken source links in documentation

- README.md
- docs/source/accelerate_training.mdx
- docs/source/deepspeed.mdx
- docs/source/distributed.mdx
- docs/source/gaudi_config.mdx
- docs/source/index.mdx
- docs/source/quickstart.mdx
- docs/source/single_hpu.mdx
- docs/source/trainer.mdx
> Fix broken links in documentation

- setup.py
This PR removes unnecessary dependencies or moves them to the `"tests"` extra if some tests require them.
> Fix setup.py dependencies

- examples/language-modeling/README.md
The README  of the language-modeling example is modified: the example with overridden configuration is modified.
> Fix config override in LM example README

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature-request.yml
This PR adds issue templates inspired by [the ones of Optimum](https://github.com/huggingface/optimum/issues/new/choose):
- bug report
- feature request
- link to the Hub documentation Github repo
- link to the forum
> Add issue templates

- README.md
- docs/source/index.mdx
This PR adds in the README and in the doc a comment to say on which SynapseAI version the current codebase has been validated.
> Add comment about the currently validated SynapseAI version

- notebooks/AI_HW_Summit_2022.ipynb
A conclusion and a link to the documentation is added at the end of the DeepSpeed demo notebook.
> Add conclusion to DeepSpeed demo notebook

- examples/image-classification/run_image_classification.py
- examples/language-modeling/run_clm.py
- examples/language-modeling/run_mlm.py
- examples/question-answering/run_qa.py
- examples/summarization/run_summarization.py
- examples/text-classification/run_glue.py
- examples/translation/run_translation.py
- optimum/habana/generation_utils.py
- optimum/habana/training_args.py
- tests/baselines/gpt2_xl.json
- tests/baselines/vit_base_patch16_224_in21k.json
- tests/example_diff/run_clm.txt
- tests/example_diff/run_glue.txt
This PR updates Optimum Habana to Transformers 4.23.
> Update to Transformers 4.23

- tests/example_diff/run_mlm.txt
- tests/example_diff/run_qa.txt
This PR fixes the diff files used for assessing the differences between Transformers' examples and Optimum Habana's ones in CI.
> Fix diff files for testing examples

- README.md
- docs/source/package_reference/trainer.mdx
- docs/source/quickstart.mdx
- docs/source/tutorials/accelerate_training.mdx
- docs/source/usage_guides/deepspeed.mdx
- docs/source/usage_guides/distributed.mdx
- docs/source/usage_guides/single_hpu.mdx
- examples/image-classification/README.md
- examples/language-modeling/README.md
- examples/question-answering/README.md
- examples/summarization/README.md
- examples/text-classification/README.md
- examples/translation/README.md
- notebooks/AI_HW_Summit_2022.ipynb
This PR updates all the documentation links.
> Update documentation links

- docs/source/_redirects.yml
- tests/baselines/roberta_base.json
- tests/baselines/roberta_large.json
This PR adds `--ddp_find_unused_parameters True` to the two following CI runs because it speeds them up:
- test_run_mlm_roberta-base_multi_card
- test_run_mlm_roberta-large_multi_card
> Add ddp_find_unused_parameters to some CI runs

- .github/workflows/build_pr_documentation.yml
- .github/workflows/fast_tests.yml
Some CI tests are sometimes executed while they are not needed because they don't cover a part of the repository that got modified by the current PR. This PR adds filters to avoid this.
> Adjust CI workflows to not execute unnecessary tests

- examples/image-classification/run_image_classification.py
- examples/language-modeling/run_clm.py
- examples/language-modeling/run_mlm.py
- examples/question-answering/run_qa.py
- examples/speech-recognition/run_speech_recognition_ctc.py
- examples/summarization/run_summarization.py
- examples/text-classification/run_glue.py
- examples/translation/run_translation.py
- tests/example_diff/run_audio_classification.txt
- tests/example_diff/run_clm.txt
- tests/example_diff/run_glue.txt
- tests/example_diff/run_image_classification.txt
- tests/example_diff/run_mlm.txt
- tests/example_diff/run_qa.txt
- tests/example_diff/run_speech_recognition_ctc.txt
- tests/example_diff/run_summarization.txt
- tests/example_diff/run_translation.txt
This PR replaces Transformers' `set_seed` by Optimum Habana's `set_seed` in examples.
> Use Optimum Habana's set_seed in examples

- examples/audio-classification/run_audio_classification.py
- examples/image-classification/run_image_classification.py
- examples/language-modeling/run_clm.py
- examples/language-modeling/run_mlm.py
- examples/question-answering/run_qa.py
- examples/question-answering/trainer_qa.py
- examples/speech-recognition/run_speech_recognition_ctc.py
- examples/summarization/run_summarization.py
- examples/text-classification/run_glue.py
- examples/translation/run_translation.py
- optimum/habana/generation_utils.py
- optimum/habana/trainer.py
- optimum/habana/trainer_seq2seq.py
- optimum/habana/training_args.py
This PR updates the repo with the latest changes from Transformers v4.24.0.
> Update to Transformers 4.24.0

- .github/workflows/build_pr_documentation.yml
- .github/workflows/delete_doc_comment.yml
This PR enables to trigger the PR doc build/deletion workflows when the following files are modified:
- `.github/workflows/build_pr_documentation.yml`,
- `.github/workflows/delete_doc_comment.yml`.
> Adjsut Github workflows for building/deleting PR doc

- .github/workflows/fast_tests.yml
- .github/workflows/slow_tests.yml
- Makefile
- README.md
- docs/Dockerfile
- docs/source/installation.mdx
- docs/source/usage_guides/deepspeed.mdx
- examples/audio-classification/README.md
- examples/speech-recognition/README.md
- notebooks/AI_HW_Summit_2022.ipynb
- optimum/habana/trainer.py
- optimum/habana/training_args.py
- tests/baselines/albert_large_v2.json
- tests/baselines/albert_xxlarge_v1.json
- tests/baselines/bert_base_uncased.json
- tests/baselines/bert_large_uncased_whole_word_masking.json
- tests/baselines/distilbert_base_uncased.json
- tests/baselines/gpt2.json
- tests/baselines/gpt2_xl.json
- tests/baselines/roberta_base.json
- tests/baselines/roberta_large.json
- tests/baselines/t5_small.json
- tests/baselines/vit_base_patch16_224_in21k.json
- tests/baselines/wav2vec2_base.json
This PR updates the repository for Synapse 1.7.0:
- CI is updated (AMI IDs and baselines)
- all links to SynapseAI's documentation are updated
- the command to install Habana's DeepSpeed is updated
- Torch DDP initialization is improved
> Update to SynapseAI 1.7.0

- optimum/habana/version.py
- setup.py
This PR bumps the version of the `main` branch to `1.4.0.dev` since v1.3.0 just got released.
> Bump version

- README.md
- docs/source/quickstart.mdx
- docs/source/usage_guides/stable_diffusion.mdx
This PR removes `from optimum.habana import GaudiConfig` in the Stable Diffusion code snippets in the documentation and README since it is not used in these examples.
> Remove GaudiConfig in Stable Diffusion code snippets

- examples/audio-classification/run_audio_classification.py
- examples/image-classification/run_image_classification.py
- examples/language-modeling/run_clm.py
- examples/language-modeling/run_mlm.py
- examples/question-answering/run_qa.py
- examples/speech-recognition/run_speech_recognition_ctc.py
- examples/summarization/run_summarization.py
- examples/text-classification/run_glue.py
- examples/translation/run_translation.py
- optimum/habana/transformers/generation/__init__.py
- optimum/habana/transformers/generation/utils.py
- optimum/habana/transformers/modeling_utils.py
- optimum/habana/transformers/trainer.py
- optimum/habana/transformers/training_args.py
- tests/example_diff/run_clm.txt
- tests/example_diff/run_image_classification.txt
- tests/example_diff/run_mlm.txt
- tests/example_diff/run_summarization.txt
- tests/example_diff/run_translation.txt
This PR brings the changes brought by Transformers 4.25.1.
> Update to Transformers 4.25.1

- .github/workflows/slow_tests.yml
- docs/source/_toctree.yml
- setup.py
This PR adds various small changes:
- Sections of the documentation will now appear folded by default in the side-bar.
- The constraint `transformers >= 4.25.0` is added to `setup.py` (see why in https://github.com/huggingface/optimum-habana/pull/136).
- A condition is added to the Stable Diffusion CI regression test so that it is executed even if previous tests failed.
> Fold sections in doc by default

- examples/speech-recognition/run_speech_recognition_ctc.py
- examples/text-classification/run_glue.py
- optimum/habana/diffusers/pipeline_utils.py
- optimum/habana/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py
- optimum/habana/diffusers/schedulers/scheduling_ddim.py
- optimum/habana/transformers/generation/utils.py
- optimum/habana/transformers/trainer.py
- optimum/habana/transformers/training_args.py
- tests/test_diffusers.py
- tests/test_examples.py
This PR integrates minor changes brought by Diffusers v0.10.0.
> Update to Diffusers 0.10.0

- Makefile
- optimum/habana/transformers/trainer.py
This PR integrates and automatically enables DeepSpeed activation checkpointing when using DeepSpeed.
> Enable DeepSpeed activation checkpointing

- .github/workflows/fast_tests.yml
- .github/workflows/slow_tests.yml
- Makefile
- README.md
- docs/Dockerfile
- docs/source/installation.mdx
- docs/source/usage_guides/deepspeed.mdx
- examples/audio-classification/README.md
- examples/speech-recognition/README.md
- notebooks/AI_HW_Summit_2022.ipynb
With the new release of SynapseAI v1.7.1, this PR updates the CI Docker images and the DeepSpeed version to install.
> Upgrade to SynapseAI v1.7.1

- optimum/habana/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py
This PR integrates changes from the latest release of the Diffusers library (v0.11.1).
> Update to Diffusers 0.11

- docs/source/usage_guides/multi_node_training.mdx
- examples/multi-node-training/README.md
This PR fix some typos in the READMEs and in the documentation.
> Fix typos in READMEs and documentation

- examples/image-classification/README.md
- tests/baselines/swin_base_patch4_window7_224_in22k.json
- tests/test_examples.py
- tests/utils.py
This PR adds instructions to run Swin in the image classification example. It also adds Swin to the regression tests for image classification.
> Add instructions for running Swin in the image classification example

- docs/source/package_reference/stable_diffusion_pipeline.mdx
- optimum/habana/diffusers/__init__.py
- optimum/habana/diffusers/pipelines/pipeline_utils.py
- optimum/habana/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py
- tests/test_diffusers.py
This PR adds the changes brought by the latest release of Diffusers (v0.12.1).
> Update to Diffusers v0.12

- setup.py
Change the minimum compatible version of Diffusers in `setup.py` following https://github.com/huggingface/optimum-habana/pull/153.
> Change min Diffusers version in setup.py

- README.md
This PR updates the homepage of this Github repository following https://github.com/huggingface/optimum-habana/pull/147.
> Update GH homepage

- examples/language-modeling/README.md
- examples/language-modeling/run_clm.py
- examples/language-modeling/run_mlm.py
- examples/question-answering/utils_qa.py
- optimum/habana/transformers/trainer.py
- tests/example_diff/run_clm.txt
- tests/example_diff/run_mlm.txt
This PR updates the CLM and MLM examples to add support for streaming datasets.
> Update the CLM and MLM examples

- setup.py
This PR updates the description in `setup.py` so that it is consistent with the README and the documentation.
> Change the description field in setup.py

- examples/multi-node-training/README.md
In the README of the multi-node training example, the name of the Docker image that is created and the name of the one that is run are not consistent. This PR fixes this.
> Fix a typo in the README of the multi-node training example

- examples/language-modeling/run_clm.py
- examples/summarization/run_summarization.py
- examples/translation/run_translation.py
- tests/baselines/gpt2.json
- tests/baselines/gpt2_xl.json
- tests/example_diff/run_clm.txt
- tests/example_diff/run_summarization.txt
- tests/example_diff/run_translation.txt
For (encoder-)decoder models, the following warning message will be displayed when using gradient checkpointing:
```
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`...
```
In order to prevent it, this PR automatically sets `use_cache` to `False` when gradient checkpointing is used in the language-modeling, summarization and translation examples (other examples involve encoder models which are not affected by this).
> Set `use_cache=False` automatically if gradient_checkpointing is used

- examples/speech-recognition/run_speech_recognition_ctc.py
- tests/example_diff/run_speech_recognition_ctc.txt
This PR updates the speech recognition example and its associated diff file.
> Update speech recognition example

- examples/speech-recognition/run_speech_recognition_ctc.py
- optimum/habana/transformers/modeling_utils.py
- optimum/habana/transformers/trainer.py
- tests/baselines/wav2vec2_large_lv60.json
- tests/example_diff/run_speech_recognition_ctc.txt
This PR updates the CI baselines for Wav2Vec2 for speech recognition.
It also enrich the error message that is raised when an operator must be executed on CPU while using HPU graphs. Those are not compatible with each other so it suggests the user to use lazy mode for inference.
> Update CI baseline for speech recognition

- examples/audio-classification/run_audio_classification.py
- examples/image-classification/run_image_classification.py
- examples/language-modeling/run_clm.py
- examples/language-modeling/run_mlm.py
- examples/question-answering/run_qa.py
- examples/speech-recognition/run_speech_recognition_ctc.py
- examples/summarization/run_summarization.py
- examples/text-classification/run_glue.py
- examples/translation/run_translation.py
- optimum/habana/diffusers/schedulers/scheduling_ddim.py
- optimum/habana/transformers/deepspeed.py
- pyproject.toml
- tests/create_diff_file_for_example.py
- tests/example_diff/run_audio_classification.txt
- tests/example_diff/run_clm.txt
- tests/example_diff/run_glue.txt
- tests/example_diff/run_image_classification.txt
- tests/example_diff/run_mlm.txt
- tests/example_diff/run_qa.txt
- tests/example_diff/run_summarization.txt
- tests/example_diff/run_translation.txt
- tests/test_trainer.py
This PR adds an option to auto-format list/dict comprehension with ruff as it is now done in Transformers: https://github.com/huggingface/transformers/pull/21694 and https://github.com/huggingface/transformers/commit/ee6e71e29cbe8c6df45dd42993c345001788ed9d.
It also adds a method to automatically update all example diff files.
> Update formatting rules for ruff

- examples/audio-classification/run_audio_classification.py
- tests/example_diff/run_audio_classification.txt
This PR updates the audio classification example following https://github.com/huggingface/transformers/pull/21756.
> Update audio classification example

- optimum/habana/diffusers/pipelines/pipeline_utils.py
- optimum/habana/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py
- optimum/habana/diffusers/schedulers/scheduling_ddim.py
- tests/test_diffusers.py
This PR updates the codebase with the changes brought by Diffusers v0.13.
> Update to Diffusers v0.13

- tests/baselines/albert_large_v2.json
- tests/baselines/albert_xxlarge_v1.json
- tests/baselines/bert_base_uncased.json
- tests/baselines/bert_large_uncased_whole_word_masking.json
- tests/baselines/distilbert_base_uncased.json
- tests/baselines/gpt2.json
- tests/baselines/gpt2_xl.json
- tests/baselines/roberta_base.json
- tests/baselines/roberta_large.json
- tests/baselines/t5_small.json
- tests/baselines/vit_base_patch16_224_in21k.json
- tests/baselines/wav2vec2_base.json
This PR updates CI baselines following #152 which should improve throughput and runtime.
> Update CI baselines

- examples/summarization/run_summarization.py
- tests/example_diff/run_summarization.txt
This PR updates the summarization example following https://github.com/huggingface/transformers/pull/21740.
> Update summarization example

- tests/test_diffusers.py
This PR updates the throughput baseline for Stable Diffusion.
> Update Stable Diffusion CI baseline

- docs/source/concept_guides/hpu.mdx
- examples/gaudi_spawn.py
- examples/multi-node-training/README.md
- optimum/habana/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py
- optimum/habana/diffusers/schedulers/scheduling_ddim.py
- optimum/habana/distributed/distributed_runner.py
- optimum/habana/transformers/deepspeed.py
- optimum/habana/transformers/gaudi_configuration.py
- optimum/habana/transformers/gradient_checkpointing.py
- optimum/habana/transformers/modeling_utils.py
- optimum/habana/transformers/models/albert/modeling_albert.py
- optimum/habana/transformers/models/modeling_all_models.py
- optimum/habana/transformers/models/vit/modeling_vit.py
- optimum/habana/transformers/models/wav2vec2/modeling_wav2vec2.py
- optimum/habana/transformers/trainer.py
- optimum/habana/transformers/trainer_seq2seq.py
- optimum/habana/transformers/training_args.py
- optimum/habana/transformers/training_args_seq2seq.py
- optimum/habana/version.py
- setup.py
- tests/test_diffusers.py
- tests/test_trainer_distributed.py
This PR adds copyrights to files in which they were missing.
> Add copyrights

- optimum/habana/transformers/models/t5/__init__.py
- optimum/habana/transformers/models/t5/modeling_t5.py
- optimum/habana/transformers/trainer.py
- optimum/habana/transformers/trainer_seq2seq.py
- tests/test_trainer_distributed.py
This PR follows #151 and enables HPU graphs for distributed runs and text generation.
> Enable HPU graphs for distributed runs and generation

- README.md
- docs/source/usage_guides/accelerate_inference.mdx
This PR removes a deprecated comment about HPU graphs since they have been enabled for distributed runs and text generation (cf. #179).
> Remove deprecated comment

- optimum/habana/transformers/generation/utils.py
Following a change in Transformers that drops support for older versions of PyTorch (see https://github.com/huggingface/transformers/pull/22291), this PR replaces `transformers.pytorch_utils.torch_int_div` by `torch.div`.
> Replace torch_int_div by torch.div

- examples/language-modeling/run_clm.py
- examples/language-modeling/run_mlm.py
- examples/summarization/run_summarization.py
- tests/example_diff/run_clm.txt
- tests/example_diff/run_mlm.txt
- tests/example_diff/run_summarization.txt
> Update run_clm, run_mlm and run_summarization examples

- README.md
- docs/source/quickstart.mdx
- docs/source/tutorials/stable_diffusion.mdx
- docs/source/usage_guides/accelerate_inference.mdx
- examples/stable-diffusion/README.md
- examples/stable-diffusion/text_to_image_generation.py
- tests/test_diffusers.py
This PR replaces `CompVis/stable-diffusion-v1-4` by `runwayml/stable-diffusion-v1-5` in the documentation and in examples.
> Update Stable Diffusion examples

- examples/image-classification/README.md
- examples/summarization/run_summarization.py
- examples/translation/run_translation.py
- tests/example_diff/run_summarization.txt
- tests/example_diff/run_translation.txt
This PR updates the summarization and translation examples following https://github.com/huggingface/transformers/pull/22693.
> Update run_summarization.py and run_translation.py

- optimum/habana/diffusers/pipelines/pipeline_utils.py
- optimum/habana/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py
- optimum/habana/diffusers/schedulers/scheduling_ddim.py
- tests/test_diffusers.py
This PR upgrades the repo to the recently released Diffusers v0.15.0, which fixes #199.
> Upgrade to Diffusers 0.15.0

- optimum/habana/version.py
- setup.py
This PR bumps up the dev version and removes the install from source for `hf_doc_builder` (no need for it anymore, it can be installed from PyPI).
> Bump dev version

- tests/baselines/albert_large_v2.json
- tests/baselines/albert_xxlarge_v1.json
- tests/baselines/bert_base_uncased.json
- tests/baselines/bert_large_uncased_whole_word_masking.json
- tests/baselines/distilbert_base_uncased.json
- tests/baselines/gpt2.json
- tests/baselines/gpt2_xl.json
- tests/baselines/roberta_base.json
- tests/baselines/roberta_large.json
- tests/baselines/swin_base_patch4_window7_224_in22k.json
- tests/baselines/t5_small.json
- tests/baselines/vit_base_patch16_224_in21k.json
- tests/baselines/wav2vec2_base.json
- tests/baselines/wav2vec2_large_lv60.json
- tests/test_diffusers.py
- tests/test_trainer_seq2seq.py
This PR updates CI baselines following the release and support of SynapseAI 1.9.0.
> Update CI baselines for SynapseAI 1.9.0

- README.md
This PR is used to add the contributor guide which is linked to the  `CONTRIBUTING.md` of Huggingface transformers.
> add the contributor guide

- docs/source/package_reference/trainer.mdx
- docs/source/usage_guides/accelerate_training.mdx
- optimum/habana/transformers/training_args.py
- optimum/habana/transformers/training_args_seq2seq.py
This PR updates the documentation with these two features lately added:
- Use `dataloader_num_workers` in some use cases #188 
- Use non-blocking data copy #211 
It also adds a section about training arguments in the [*Reference* section](https://huggingface.co/docs/optimum/habana/package_reference/trainer).
> Update the documentation

- optimum/habana/diffusers/pipelines/pipeline_utils.py
- optimum/habana/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py
> Upgrade to Diffusers v0.16

- tests/example_diff/run_seq2seq_qa.txt
This PR adds an example diff file (Transformers compared to Optimum Habana) for the seq2seq QA example following #221.
> Add example diff file for run_seq2seq_qa.py

- docs/source/_toctree.yml
- docs/source/tutorials/inference.mdx
- docs/source/tutorials/overview.mdx
- examples/audio-classification/README.md
- examples/contrastive-image-text/README.md
- examples/contrastive-image-text/run_clip.py
- examples/image-classification/README.md
- examples/language-modeling/README.md
- examples/question-answering/README.md
- examples/speech-recognition/README.md
- examples/speech-recognition/run_speech_recognition_ctc.py
- examples/summarization/README.md
- examples/text-classification/README.md
- examples/translation/README.md
This PR adds clearer explanations about how to run inference.
> Enrich documentation for inference

- examples/text-classification/run_glue.py
- tests/example_diff/run_generation.txt
- tests/example_diff/run_glue.txt
- tests/example_diff/run_speech_recognition_ctc.txt
This PR updates the GLUE example and a few example diff files.
> Update `run_glue.py` and diff files

- examples/text-generation/README.md
- examples/text-generation/run_generation.py
As title, user could use `sampling` algo for text-generation with args `--do_sample True`
> text-generation support sampling algo

- setup.py
This PR updates `setup.py` so that the latest release of Transformers is not installed when installing Optimum Habana.
> Add constraint Transformers < 4.29.0

- README.md
- docs/source/index.mdx
> Add ESMFold and StarCoder to the table of validated models

- examples/text-generation/run_generation.py
- optimum/habana/transformers/generation/utils.py
- optimum/habana/transformers/modeling_utils.py
This PR fixes #240 and adds a `seed` argument to the text-generation example to be able to reproduce sampling results.
> Fix sampling in the text-generation example

- README.md
- docs/source/package_reference/gaudi_config.mdx
- docs/source/quickstart.mdx
- docs/source/tutorials/single_hpu.mdx
- optimum/habana/transformers/generation/utils.py
> Refine doc and README

- examples/text-generation/checkpoint_utils.py
- examples/text-generation/run_generation.py
- optimum/habana/transformers/modeling_utils.py
- optimum/habana/transformers/models/__init__.py
- optimum/habana/transformers/models/gpt2/__init__.py
- optimum/habana/transformers/models/gpt2/modeling_gpt2.py
as title
with this PR, text-generation with GPT2 could generate meaningful outputs
> fix text-generation gpt2 bug

- examples/text-generation/checkpoint_utils.py
- optimum/habana/transformers/modeling_utils.py
- optimum/habana/transformers/models/__init__.py
- optimum/habana/transformers/models/opt/__init__.py
- optimum/habana/transformers/models/opt/modeling_opt.py
as title
- opt-125m fp32 outputs
> cmd line : ` python run_generation.py --model_name_or_path facebook/opt-125m  --batch_size 1 --max_new_tokens 100  --use_kv_cache --use_hpu_graphs`
- opt-15b fp32 outputs
> cmd line : ` python run_generation.py --model_name_or_path facebook/opt-13b  --batch_size 1 --max_new_tokens 100  --use_kv_cache --use_hpu_graphs`
> enable opt

- docs/source/usage_guides/accelerate_inference.mdx
> Improve doc about accelerating inference

- examples/text-generation/checkpoint_utils.py
- optimum/habana/transformers/modeling_utils.py
- optimum/habana/transformers/models/__init__.py
- optimum/habana/transformers/models/gpt_neox/__init__.py
- optimum/habana/transformers/models/gpt_neox/modeling_gpt_neox.py
> Enable GPTNeoX

- examples/text-generation/run_generation.py
- optimum/habana/transformers/generation/utils.py
- optimum/habana/transformers/trainer.py
- optimum/habana/transformers/training_args.py
- optimum/habana/utils.py
Adding profiling into `GaudiTrainer` and `text-generation`
#245
> Enable profiling

- examples/text-generation/run_generation.py
as title
How to use:
```shell
python run_generation.py --model_name_or_path gpt2  --batch_size 1 --max_new_tokens 100 --use_hpu_graphs --bf16 --prompt "I am a student from"
```
> Text generation supports user input prompt

- examples/text-generation/README.md
- examples/text-generation/run_generation.py
> Update text-generation README

- optimum/habana/transformers/generation/utils.py
> Optimize early stop check

- examples/text-generation/run_generation.py
logging memory stats is very important since user could estimate how many tokens and bs they could use when running text-generation
with opt-1.3B
max_new_tokens = 100
max_new_tokens = 1000
> text-generation logging memory stats

- examples/gaudi_spawn.py
> fix ds inference with user prompt for text-generation

- .github/workflows/build_pr_documentation.yml
- .github/workflows/delete_doc_comment.yml
- .github/workflows/delete_doc_comment_trigger.yml
- docs/source/index.mdx
- examples/text-generation/checkpoint_utils.py
> Update doc workflows

- .github/workflows/build_pr_documentation.yml
> Remove unused variable in GH workflow

- .github/workflows/build_pr_documentation.yml
- .github/workflows/upload_pr_documentation.yml
- docs/source/index.mdx
> Fix PR doc build from fork

- examples/text-generation/run_generation.py
- optimum/habana/transformers/generation/utils.py
> enable beam_search path for text-generation

- docs/source/usage_guides/accelerate_training.mdx
- examples/audio-classification/README.md
- examples/audio-classification/run_audio_classification.py
- examples/contrastive-image-text/README.md
- examples/contrastive-image-text/run_clip.py
- examples/image-classification/README.md
- examples/image-classification/run_image_classification.py
- examples/language-modeling/README.md
- examples/language-modeling/run_clm.py
- examples/language-modeling/run_mlm.py
- examples/question-answering/README.md
- examples/question-answering/run_qa.py
- examples/question-answering/run_seq2seq_qa.py
- examples/speech-recognition/README.md
- examples/speech-recognition/run_speech_recognition_ctc.py
- examples/summarization/README.md
- examples/summarization/run_summarization.py
- examples/text-classification/README.md
- examples/text-classification/run_glue.py
- examples/translation/README.md
- examples/translation/run_translation.py
- optimum/habana/transformers/gaudi_configuration.py
- optimum/habana/transformers/trainer.py
- optimum/habana/transformers/training_args.py
- tests/test_gaudi_configuration.py
- tests/test_trainer.py
> Add test and doc for Torch Autocast

- optimum/habana/transformers/deepspeed.py
- optimum/habana/transformers/trainer.py
- tests/baselines/gpt2_xl.json
This PR improves DeepSpeed support on HPU:
- FusedAdamW is not automatically disabled anymore when using DeepSpeed
- HMP is turned off when using DeepSpeed
- The DS regression test is updated accordingly
> Improve DeepSpeed support

- README.md
- docs/source/index.mdx
- examples/text-generation/README.md
- examples/text-generation/run_generation.py
> Improve text-generation doc

- examples/contrastive-image-text/README.md
- examples/contrastive-image-text/clip_media_pipe.py
- examples/contrastive-image-text/clip_mediapipe_dataloader.py
- examples/contrastive-image-text/habana_dataloader_trainer.py
- examples/contrastive-image-text/run_clip.py
- optimum/habana/transformers/trainer.py
Improves Clip performance on Gaudi2. Below is the performance of batch size 512 removing checkpoint saving time, which is measured using Habana 1.10 release docker version on Gaudi2.
> Clip perf tune

- examples/contrastive-image-text/README.md
- examples/contrastive-image-text/run_clip.py
I am verifying CLIP using latest optimum habana. Disable fused adam is no long necessary after enabling hpu graph for training and media dataloader.
> Remove use_fused_adam config in clip

- optimum/habana/transformers/modeling_utils.py
- optimum/habana/transformers/models/__init__.py
- optimum/habana/transformers/models/esm/__init__.py
- optimum/habana/transformers/models/esm/modeling_esm.py
> Add support for ESM

- examples/text-generation/run_generation.py
- optimum/habana/transformers/modeling_utils.py
- optimum/habana/transformers/models/__init__.py
- optimum/habana/transformers/models/bloom/__init__.py
- optimum/habana/transformers/models/bloom/modeling_bloom.py
> Update BLOOM modeling for SynapseAI 1.10

- docs/source/tutorials/stable_diffusion.mdx
- examples/stable-diffusion/README.md
- examples/stable-diffusion/text_to_image_generation.py
- optimum/habana/diffusers/pipelines/pipeline_utils.py
- optimum/habana/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py
- tests/test_diffusers.py
> Add Torch autocast and full bf16 to GaudiStableDiffusionPipeline

- examples/text-generation/checkpoint_utils.py
- examples/text-generation/run_generation.py
- optimum/habana/transformers/generation/utils.py
> Only download PyTorch weights in text-generation example

- examples/text-generation/run_generation.py
temporary enable opt-66b(ds mode).
> support opt-66b

- README.md
> Replace crosses in README model table

- optimum/habana/diffusers/pipelines/pipeline_utils.py
- optimum/habana/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py
- optimum/habana/diffusers/schedulers/scheduling_ddim.py
- setup.py
- tests/test_diffusers.py
> Upgrade to Diffusers v0.18.0

- optimum/habana/transformers/models/albert/modeling_albert.py
- optimum/habana/transformers/models/modeling_all_models.py
This PR addresses nan issue appeared in loss computation for BERT family.
JH...!
> Scope out autocast for mult in extended atten mask gen

- examples/text-generation/checkpoint_utils.py
In the text-generation example, only `*.safetensors` files are downloaded if `safetensors` is installed. However, some model repos may not contain any `.safetensor` file leading to not downloading any weights.
This PR fixes this by checking before downloading if the model repo contains any `.safetensor` file and reverting to `*.bin` if not.
> Fix download of .safetensors file in text-generation example

- examples/summarization/run_summarization.py
- examples/text-generation/checkpoint_utils.py
- examples/text-generation/run_generation.py
- optimum/habana/transformers/generation/__init__.py
- optimum/habana/transformers/generation/configuration_utils.py
- optimum/habana/transformers/generation/utils.py
- optimum/habana/transformers/modeling_utils.py
- optimum/habana/transformers/trainer_seq2seq.py
- optimum/habana/transformers/training_args_seq2seq.py
> Add `GaudiGenerationConfig`

- optimum/habana/transformers/models/bloom/modeling_bloom.py
The custom modeling code for BLOOM was suited for inference with tensor parallelism and DeepSpeed-inference. This PR introduces a fall back to the original code from Transformers when the model is being trained.
> Fix BLOOM training

- README.md
- docs/source/index.mdx
> Add Llama to table in README/doc

- examples/text-generation/checkpoint_utils.py
enable deepspeed for llama in text generation
> add deepspeed TP policy for llama

- optimum/habana/transformers/gradient_checkpointing.py
As per title. Inspired from: https://github.com/pytorch/pytorch/blob/e9ebda29d87ce0916ab08c06ab26fd3766a870e5/torch/utils/checkpoint.py#L61C39-L61C66
> Add support for autocast in gradient checkpointing

- examples/language-modeling/README.md
- examples/language-modeling/requirements.txt
- examples/language-modeling/run_lora_clm.py
- examples/text-generation/README.md
- examples/text-generation/requirements.txt
- examples/text-generation/run_generation.py
> add lora example for clm and text generation

- notebooks/AI_HW_Summit_2022.ipynb
- optimum/habana/transformers/models/t5/modeling_t5.py
For T5 inference, don't wrap dropout with mark_step as it causes performance issue.
> Fix T5 inference performance regression

- optimum/habana/transformers/modeling_utils.py
- optimum/habana/transformers/models/__init__.py
- optimum/habana/transformers/models/gptj/__init__.py
- optimum/habana/transformers/models/gptj/modeling_gptj.py
> fix gptj HCCL issue occured in DDP

- README.md
- docs/source/index.mdx
Add StableLM to optimum-habana documentation
> Add StableLM to documentation

- README.md
- docs/source/index.mdx
> Replace "Llama" by "Llama 2" in table

- examples/summarization/ds_flan_t5_z3_config_bf16.json
> Modify flan-t5 deepspeed configuration

- examples/text-generation/README.md
- examples/text-generation/run_generation.py
As per title.
This PR also contains a temporary hack so that users can use Falcon as any other model. I'll remove this hack when the config of the hub repos is updated.
> Add `token` and `model_revision` args for the text-generation example

- tests/example_diff/run_generation.txt
> Update example diff file for text generation

- examples/language-modeling/README.md
Adds commands for finetuning GPTJ-6b and GPTNEOX-20b on wikitext data set.
Here are the details : 
GPTJ-6b was fine tuned for Language modelling with Wikitext data set on 8 Gaudi2 cards 
GPTNEOX-20b was finetuned for Language modelling with Wikitext data set on 16  Gaudi2 cards
> Add commands for gptj and gptneox

- optimum/habana/transformers/models/llama/modeling_llama.py
> disable FusedRMSNorm for training

- examples/contrastive-image-text/README.md
- examples/contrastive-image-text/clip_media_pipe.py
- examples/contrastive-image-text/clip_mediapipe_dataloader.py
- examples/contrastive-image-text/habana_dataloader_trainer.py
- examples/contrastive-image-text/run_bridgetower.py
This PR fixes some issues related to data samples in the media pipe used in the BridgeTower example.
> Fix BridgeTower example

- optimum/habana/transformers/models/opt/modeling_opt.py
> fix opt bug

- Makefile
Fixes external links in the documentation ; `doc-builder` uses `library_name` (optimum.habana) for Github external links when `repo_name` is not explicitly given.
> Correct Github external links in Doc

- optimum/habana/transformers/models/falcon/modeling_falcon.py
This change fixes the size mismatch between position_ids and cos when batch size > 1.
> Fix graph compilation error from Falcon when batch size>1

- Makefile
- optimum/habana/accelerate/accelerator.py
- optimum/habana/accelerate/state.py
- optimum/habana/transformers/trainer.py
- optimum/habana/utils.py
> Upgrade to Accelerate v0.22

- examples/language-modeling/README.md
- examples/language-modeling/run_clm.py
- examples/language-modeling/run_mlm.py
- tests/example_diff/run_clm.txt
- tests/example_diff/run_mlm.txt
Fixes for streaming dataset mode
A customer reported seeing errors when using --streaming.
Made a fix to get rid of TypeError: object of type 'IterableDataset' has no len().
Updated Readme with an example command that demonstrates correct use of --streaming. with --max_steps specified.
> Fixes for streaming dataset mode

- optimum/habana/transformers/generation/utils.py
- optimum/habana/transformers/modeling_utils.py
- optimum/habana/transformers/models/__init__.py
- optimum/habana/transformers/models/mpt/__init__.py
- optimum/habana/transformers/models/mpt/modeling_mpt.py
- tests/test_text_generation_example.py
> add mpt optimization for gaudi

- optimum/habana/transformers/generation/utils.py
Also update cur_len with token_idx.item() and use that to slice the input_ids when calling beam_scorer.process().
The logic will work when token idx is None too.
> Fix beam search output

- optimum/habana/transformers/models/llama/modeling_llama.py
Batch size > 1 not working with FusedRoPE.
Graph compilation error.
> Temporary disable FusedRoPE for llama.

- optimum/habana/transformers/models/llama/modeling_llama.py
> Re enable fused RoPE for llama.

- setup.py
> Update version constraints in `setup.py`

- examples/text-generation/checkpoint_utils.py
- examples/text-generation/run_generation.py
When generate text with DeepSpeed library, this PR loads llama ckpt to meta to work around OOM issue on CPU.
> Load llama ckpt to meta to work around OOM issue on CPU

- text-generation-inference/server/text_generation_server/models/causal_lm.py
> style fixes

- text-generation-inference/Dockerfile
- text-generation-inference/server/text_generation_server/utils/logits_process.py
Fixes # (HPU graph is not enabled)
> Enable hpu graph

- text-generation-inference/server/text_generation_server/models/causal_lm.py
> add other optimized models to TGI like llama

- optimum/habana/transformers/models/mpt/modeling_mpt.py
- tests/test_text_generation_example.py
This change improves DmaMemcpy time of MPT inference by using the code taken from modeling_falcon.py
> Improve MPT inference performance

- text-generation-inference/README.md
> Update TGI readme

- .github/workflows/check_code_quality.yml
- .github/workflows/pr_is_mergeable.yml
Add a new workflow to know if all tests passed or not.
> Add new CI workflow

- text-generation-inference/server/text_generation_server/models/causal_lm.py
also if there's pad left in input token, token_idx is wrong calculated.
fix issue that's found in multi-request enabling
> accelerate the inference when input prompt length changes in TGI

- examples/text-generation/run_generation.py
> add warmup arg and move stats printing to the end

- optimum/habana/transformers/modeling_utils.py
- optimum/habana/transformers/models/__init__.py
- optimum/habana/transformers/models/t5/__init__.py
- optimum/habana/transformers/models/t5/modeling_t5.py
> Fix T5 DeepSpeed ZeRO-3

- examples/language-modeling/run_lora_clm.py
> Fix gradient checkpointing in LoRA example

- text-generation-inference/server/text_generation_server/models/causal_lm.py
- text-generation-inference/server/text_generation_server/server.py
add static shape support in concatenate and filter
> support static shape in concatenate and filter in TGI

- optimum/habana/diffusers/pipelines/pipeline_utils.py
> Fix import from Diffusers

- optimum/habana/transformers/models/llama/modeling_llama.py
Also update repeat KV logic when number of KV heads is 1 as the hidden states can be broadcasted during matmuls.
> Allocate KV cache in contiguous memory for HPU performance

- examples/text-generation/README.md
- examples/text-generation/run_generation.py
- optimum/habana/transformers/generation/configuration_utils.py
- optimum/habana/transformers/generation/utils.py
- optimum/habana/transformers/models/llama/modeling_llama.py
> Add support for attention softmax in BF16 such as for llama.

- examples/text-generation/run_generation.py
- optimum/habana/transformers/generation/configuration_utils.py
- optimum/habana/transformers/generation/utils.py
- optimum/habana/transformers/models/llama/modeling_llama.py
Add trim logit logic to reduce maximum memory usage for Llama inference
> add trim logit logic to reduce maximum memory usage for Llama inference

- tests/baselines/vit_base_patch16_224_in21k.json
> Update ViT CI baseline

- text-generation-inference/server/text_generation_server/utils/logits_process.py
> fix error in logits process in hpu graph

- text-generation-inference/server/text_generation_server/models/causal_lm.py
- text-generation-inference/server/text_generation_server/utils/logits_process.py
> Fix first token

- optimum/habana/transformers/models/falcon/modeling_falcon.py
- optimum/habana/transformers/models/gpt_neox/modeling_gpt_neox.py
- optimum/habana/transformers/models/llama/modeling_llama.py
Fixes #403.
Same fix for Llama and Falcon.
> Fix GPT-NeoX training

- optimum/habana/transformers/models/falcon/modeling_falcon.py
- optimum/habana/transformers/models/llama/modeling_llama.py
Revert #410 for Llama and Falcon.
> Revert FusedRoPE changes in Llama and Falcon

- optimum/habana/transformers/generation/utils.py
> Setting ignore_eos to lazy_mode

- optimum/habana/transformers/models/gpt2/modeling_gpt2.py
change tensor to contiguous after split heads and before attention for gpt2
> gpt2 contiguous fix

- examples/text-generation/run_generation.py
> Add a configurable max input tokens parameter

- tests/test_encoder_decoder_text_summarization.py
> Adding BART test

- docs/source/index.mdx
> Fix links in doc tiles

- examples/text-generation/README.md
> Update readme for max input tokens and trim logits

- examples/text-generation/run_generation.py
We used to need a hack to target the right commit to download the right model configurations for Falcon models. This is no longer needed so it is removed in this PR.
> Remove Falcon hack

- examples/language-modeling/README.md
> Remove model revision for Falcon training

- tests/transformers/tests/models/falcon/test_modeling_falcon.py
- tests/transformers/tests/models/vit/test_modeling_vit.py
Adding Falcon and VIT  TCs from :  
https://github.com/huggingface/transformers/tree/main/tests 
To run on Gaudi devices.
@regisss , @ZhaiFeiyue   : Please help merge these.
> Add Falcom and VIT TCs from transformers/tests

- examples/text-generation/run_generation.py
Currently for dataset run, the dataset will be cropped to fixed len. Add option to not crop
> option to not crop in dataset run

- optimum/habana/transformers/models/falcon/modeling_falcon.py
Changes to Falcon's modeling following the release of Transformers v4.34.
> Fix for Falcon

- text-generation-inference/README.md
- text-generation-inference/server/text_generation_server/models/causal_lm.py
The current default value for `max_total_tokens` is 2048. Let's switch to 512.
> Temporary fix in TGI for max total tokens

- examples/text-generation/checkpoint_utils.py
> Enable auto tensor parallelism for Falcon

- examples/multi-node-training/README.md
- optimum/habana/transformers/models/gpt_neox/modeling_gpt_neox.py
- optimum/habana/transformers/models/t5/modeling_t5.py
This PR enables FusedRoPE for training in GPT-NeoX modeling and FusedRMSNorm for training in T5 modeling.
It also adds a comment about OFI in the README of the multi-node example.
> Enable FusedRoPE for training in GPT-NeoX modeling

- optimum/habana/transformers/models/llama/modeling_llama.py
Llama inference:temp fix for deepspeed@1.11.0 didn't enable num_key_v…
> revert of #411

- optimum/habana/transformers/models/gpt2/modeling_gpt2.py
As per title as text-generation with GPT2-XL fails on Gaudi2.
> Add workaround for GPT2 inference on Gaudi2

- notebooks/AI_HW_Summit_2022.ipynb
- optimum/habana/diffusers/pipelines/pipeline_utils.py
- optimum/habana/transformers/trainer.py
As per title + remove HMP deprecation warnings as those are now logged by SynapseAI
> Update GPT2-XL notebook

- examples/language-modeling/run_lora_clm.py
Fixes SegFault during FT for Falcon 40b
> Fix for SegFault during FT

- tests/transformers/tests/models/albert/test_modeling_albert.py
- tests/transformers/tests/models/bert/test_modeling_bert.py
- tests/transformers/tests/models/distilbert/test_modeling_distilbert.py
- tests/transformers/tests/models/roberta/test_modeling_roberta.py
Adding bert family of models from 
https://github.com/huggingface/transformers/tree/main/tests
To run on Gaudi devices.
@regisss  : could you please help with the  review and merge. I have already done the style check .
> Add bert family of models to transformers/tests

- optimum/habana/transformers/generation/utils.py
- optimum/habana/transformers/trainer_seq2seq.py
- optimum/habana/transformers/training_args.py
> Adding ignore_eos flag to use in generation

- tests/transformers/tests/models/swin/test_modeling_swin.py
- tests/transformers/tests/models/wav2vec2/test_modeling_wav2vec2.py
Adding swin and wav2vec2.  from https://github.com/huggingface/transformers/tree/main/tests for gaudi devices
This completes the  inclusion of all models listed in  : 
https://github.com/huggingface/optimum-habana#validated-models
@regisss  : please help with the review and merge , thanks.
> Add swin and wav2vec2

- examples/language-modeling/run_lora_clm.py
> Fix validate dataset problem for openassistant-guanaco

- examples/audio-classification/run_audio_classification.py
- optimum/habana/transformers/modeling_utils.py
- optimum/habana/transformers/models/__init__.py
- optimum/habana/transformers/models/wav2vec2/__init__.py
- optimum/habana/transformers/models/wav2vec2/modeling_wav2vec2.py
Modifies modeling_wav2vec2.py code to get it ready for enabling HPU graphs during training phase. Performance of Wav2Vec2 AC and ASR tasks on HPU are currently limited by Host time (more visible on 1x configurations), this also results in run to run performance variations (depending on loading of Host if it is shared by other processes). Enabling HPU graphs will improve performance and give more stable results.   
> Hpu graph changes

- optimum/habana/accelerate/data_loader.py
Related to https://github.com/huggingface/accelerate/pull/2057.
> Fix for Accelerate

- optimum/habana/transformers/modeling_utils.py
#494 introduced a drop in accuracy for audio classification with Wav2Vec2: from 80.15% to 78.63%.
> Revert changes to Wav2Vec2

- docs/Dockerfile
The doc build currently fails because of nodejs installation. This PR fixes it.
> Fix doc build

- setup.py
Transformers v4.35, which will be released soon, is currently not supported by Optimum Habana.
> Update Transformers dependency in setup.py

- optimum/habana/transformers/trainer.py
- optimum/habana/transformers/training_args.py
- tests/test_trainer.py
> add maximum hpugraphs and disable_tensor_cache arguments to GaudiTrainer

- tests/test_trainer_seq2seq.py
In `test_trainer_seq2seq.py`, the model is instantiated before training args are set and thus before the method `adapt_transformers_to_gaudi` is called. This leads to an error when this test is executed alone. This PR fixes that.
> Fix `test_trainer_seq2seq.py`

- text-generation-inference/README.md
> Add link to TGI license

- examples/text-generation/run_generation.py
> Merge LoRA model before initializing DS inference in text-generation example

- tests/example_diff/run_generation.txt
> Update text-generation example diff file

- optimum/habana/transformers/models/falcon/modeling_falcon.py
> fixing FusedSDPA recompute bug

- optimum/habana/diffusers/models/unet_2d_condition.py
- optimum/habana/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py
- optimum/habana/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_ldm3d.py
- optimum/habana/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_upscale.py
- tests/test_diffusers.py
As per title + add CI for Gaudi2
> Upgrade to Diffusers 0.23

- examples/language-modeling/run_clm.py
- examples/summarization/run_summarization.py
- examples/translation/run_translation.py
- tests/example_diff/run_clm.txt
See https://github.com/huggingface/transformers/pull/27499.
> Fix missing max_position_embeddings in model config in `run_clm.py`

- examples/language-modeling/run_lora_clm.py
Add --load_meta_device option to reduce host RAM for falcon40b
> Add load_meta_device option to reduce host RAM

- tests/test_trainer.py
This PR uncomments `test_dynamic_shapes` to include it in the CI.
> Refine `test_trainer.py`

- optimum/habana/transformers/generation/utils.py
- optimum/habana/transformers/models/llama/modeling_llama.py
> Improve llama performance and reduce memory consumption by updating sin/cos cache when inferring more than max position embeddings (4096) 

- examples/text-generation/run_generation.py
- examples/text-generation/utils.py
- optimum/habana/checkpoint_utils.py
- optimum/habana/utils.py
> refactor run generation

- Makefile
- examples/text-generation/README.md
- examples/text-generation/run_generation.py
- optimum/habana/utils.py
- tests/test_text_generation_example.py
Synapse 1.13.0 change for falcon inference
> Add hash_with_views arg for Falcon inference perf

- examples/contrastive-image-text/run_bridgetower.py
- examples/contrastive-image-text/run_clip.py
- examples/language-modeling/run_clm.py
- examples/language-modeling/run_mlm.py
- examples/question-answering/run_qa.py
- examples/question-answering/run_seq2seq_qa.py
- examples/summarization/README.md
- examples/summarization/run_summarization.py
- examples/text-classification/run_glue.py
- examples/text-generation/run_generation.py
- examples/translation/README.md
- tests/example_diff/run_generation.txt
With #523, results are written in the given output folder by all processes, which can lead to race conditions. This PR fixes that by allowing the main process only to write results.
> Fix text generation CI

- examples/text-generation/run_generation.py
- examples/text-generation/utils.py
> Fix loading on meta device for PEFT models with DS-inference

- examples/text-generation/README.md
- examples/text-generation/utils.py
In the text-generation example, the argument `skip_hash_with_views` is automatically set to True if the model is a Falcon model.
> Automate skip_hash_with_views for text generation with Falcon

- examples/translation/run_translation.py
- tests/example_diff/run_generation.txt
- tests/example_diff/run_translation.txt
> Fix run generation and translation CI

- examples/text-generation/run_generation.py
Reuse cache is independent of HPU graphs enablement. 
Remove forcefully setting reuse cache to False when HPU graphs is disabled.
> Fix setting of reuse cache

- .github/workflows/slow_tests.yml
- .github/workflows/slow_tests_gaudi2.yml
> Add Gaudi2 regression test workflow

- .github/workflows/build_pr_documentation.yml
- .github/workflows/check_code_quality.yml
- Makefile
- examples/text-generation/run_generation.py
- pyproject.toml
- setup.py
- tests/test_trainer.py
- tests/transformers/tests/models/gpt2/test_modeling_gpt2.py
- tests/transformers/tests/models/gptj/test_modeling_gptj.py
- tests/transformers/tests/models/llama/test_modeling_llama.py
Similar to https://github.com/huggingface/transformers/pull/27144.
> Remove black and use ruff for code formatting

- .github/workflows/slow_tests_gaudi2.yml
A previously removed job was still mentionned in the Gaudi2 CI workflow, this PR fixes that.
> Fix Gaudi2 CI workflow

- text-generation-inference/server/text_generation_server/models/causal_lm.py
LIMIT_HPU_GRAPH=True is only meaningful when ENABLE_HPU_GRAPH is true. 
Added further checking to set the "bypass_hpu_graph" based on these two flag.
> enable LIMIT_HPU_GRAPH only when ENABLE_HPU_GRAPH is true

- tests/example_diff/run_generation.txt
Update the diff file for the text-generation example.
> Fix example diff CI

- examples/contrastive-image-text/README.md
- examples/contrastive-image-text/run_bridgetower.py
- tests/baselines/bridgetower_large_itm_mlm_itc.json
The format of the dataset used in the BridgeTower example changed a bit a few days ago. This PR adds a `--dataset_revision` argument so that it is possible to use a previous version of a dataset to solve this issue.
> Update BridgeTower example

- examples/text-generation/README.md
- examples/text-generation/run_generation.py
- examples/text-generation/utils.py
- optimum/habana/transformers/generation/configuration_utils.py
- optimum/habana/transformers/generation/utils.py
- optimum/habana/transformers/models/llama/modeling_llama.py
Add llamav2 fp8 inference
adding kv cache in fp8 option
> Add llamav2 fp8 inference

- examples/text-generation/README.md
- examples/text-generation/lm_eval.py
- examples/text-generation/requirements_lm_eval.txt
- examples/text-generation/run_lm_eval.py
> adding lm eval script

- README.md
- optimum/habana/transformers/training_args.py
> remove mention of eager in readme. set use_lazy_mode to true by default

- setup.py
As per title, to avoid installing unwanted dependencies like Transformers 4.33 or 4.35.
> Pin Diffusers

- examples/language-modeling/README.md
- examples/language-modeling/ds_falcon_180b_z3.json
- examples/language-modeling/run_lora_clm.py
This PR enables Falcon 180B Finetuning.
> Enable Falcon 180B

- Makefile
The current command `slow_tests_text_generation_example` calls `pytest` twice, which means that the second call will not happen if a test fails during the 1st call.
This PR just move the 2nd test (2nd `pytest` call) to the 1st call so that the encoder-decoder text-generation test is run whatever happens with previous tests.
> Improve command for text generation CI

- examples/language-modeling/README.md
> Fix messed up README for llama2-70b

- text-generation-inference/server/pyproject.toml
> update tokenizer for tgi

- examples/text-classification/run_glue.py
- tests/baselines/gpt2.json
> Update GPT2 CI baselines

- tests/example_diff/run_glue.txt
> Update `run_glue.py` diff file

- tests/transformers/tests/generation/test_utils.py
- tests/transformers/tests/test_modeling_common.py
1. Skip tests that are slow
2. Include HPU related arguments such as limit_hpu_graphs
@regisss  : could you help with the review and merge, thank you!
> misc changes for transformers tests

- examples/text-generation/README.md
A `\` is missing at the end of the first line of the fp8 command in the text-generation README.
> Fix fp8 command in text-generation README

- examples/language-modeling/requirements.txt
Temporary fix for #590 while we determine the reason for higher memory consumption with PEFT v0.7.0.
> Pin PEFT for the languge-modeling example

- optimum/habana/transformers/models/gptj/modeling_gptj.py
Fix training runtime error caused by lack of sin and cos value missing when load from checkpoint.
> fix gptj training issue

- tests/example_diff/run_audio_classification.txt
- tests/example_diff/run_clip.txt
- tests/example_diff/run_clm.txt
- tests/example_diff/run_glue.txt
- tests/example_diff/run_image_classification.txt
- tests/example_diff/run_mlm.txt
- tests/example_diff/run_qa.txt
- tests/example_diff/run_seq2seq_qa.txt
- tests/example_diff/run_speech_recognition_ctc.txt
- tests/example_diff/run_summarization.txt
- tests/example_diff/run_translation.txt
> Update example diff files in CI

- README.md
> Change Synapse validated version in README

- tests/example_diff/run_generation.txt
- tests/example_diff/run_summarization.txt
> Update CI diff files

- tests/test_encoder_decoder_text_summarization.py
> Update BART CI baseline

- optimum/habana/transformers/trainer.py
to reduce the storage size and also save the time of checkpoint saving while using deepspeed for training
> In peft, only the trainable parameters need to be saved

- Makefile
Regression tests fail with Diffusers' main branch. Disable it till it's solved.
> Temporary fix for Diffusers CI

- examples/text-generation/utils.py
> Update generation config to enable flash attention for inference

- optimum/habana/transformers/models/llama/modeling_llama.py
> Fix flash attention output for llama for padded batched inputs

- examples/stable-diffusion/README.md
- examples/stable-diffusion/text_to_image_generation.py
- tests/test_diffusers.py
> update for SDXL Turbo support

- examples/language-modeling/README.md
> Add use_flash_attention to Llama2-70B finetuning command in README

- examples/stable-diffusion/text_to_image_generation.py
The call to `set_seed` in the SD example has to be moved so that custom bf16 ops can be used with autocast.
> Fix SD example so that custom bf16 ops can be used

- README.md
This is to modify README.md to include TRL DPO.
> Add DPO of TRL in README.md

- optimum/habana/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py
See https://github.com/huggingface/optimum-habana/actions/runs/7659207180/job/20880538868
> Fix SDXL test

- examples/stable-diffusion/run.sh
https://github.com/huggingface/diffusers/blob/v0.25.1/examples/text_to_image/README_sdxl.md#training
> Update run script parameters matched with official 0.25.1 run

- examples/stable-diffusion/plot_loss_curve.py
- examples/stable-diffusion/train_text_to_image_sdxl.py
> Save the inference output images

- examples/stable-diffusion/text_to_image_generation.py
- optimum/habana/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py
Add habana profiling to stable diffusion
> Add habana profiling to stable diffusion

- optimum/habana/version.py
> Update dev version

- examples/text-generation/utils.py
> Bring back workaround for Falcon with SynapseAI 1.13

- tests/example_diff/run_image_classification.txt
> Update example diff file for image classification

- tests/example_diff/run_image_classification.txt
Following https://github.com/huggingface/transformers/pull/28974.
> Update diff file

- Makefile
- setup.py
The main branch of Accelerate currently makes the CI fail: https://github.com/huggingface/optimum-habana/actions/runs/7907333063
This PR pins the current version of Accelerate to make sure that v0.28 will not be installed as a dependency when it is released. Install from main is also removed from CI till this is fixed.
> Pin Accelerate

- tests/test_text_generation_example.py
This PR moves the env variables declaration into a dedicated dictionary for each test. This ensures that env variables that are declared for one test are not declared anymore for the following tests.
> Small `test_text_generation_example.py` refacto

- optimum/habana/transformers/generation/utils.py
- optimum/habana/transformers/modeling_utils.py
- optimum/habana/transformers/models/__init__.py
- optimum/habana/transformers/models/blip/__init__.py
- optimum/habana/transformers/models/blip/modeling_blip.py
- optimum/habana/transformers/models/blip/modeling_blip_text.py
> add optimization for blip text model generation

- optimum/habana/transformers/modeling_utils.py
- optimum/habana/transformers/models/__init__.py
- optimum/habana/transformers/models/mistral/__init__.py
- optimum/habana/transformers/models/mistral/modeling_mistral.py
- Update the naming as suggested in [PR#716 ](https://github.com/huggingface/optimum-habana/pull/716)
gaudi_mistral_attn_forward -> gaudi_mistral_attention_forward
> Update the Mistral model naming

- optimum/habana/accelerate/utils/dataclasses.py
AOT_HPU_TRAINING_BACKEND for torch compile shall be deprecated soon, will be replaced by HPU_BACKEND. Therefore add support for new HPU backend.
> Changing backend name

- README.md
> Update latest stable release version in README

- examples/trl/reward_modeling.py
- examples/trl/sft.py
> add seed in sft example, make sft result reproducable

- examples/language-modeling/run_lora_clm.py
This is the same change as PR #711 but for different script.
> Adding a flag whether to save checkpoint or not in run_lora_clm.py

- examples/contrastive-image-text/clip_media_pipe.py
- examples/speech-recognition/run_speech_recognition_seq2seq.py
- optimum/habana/transformers/modeling_utils.py
- optimum/habana/transformers/models/__init__.py
- optimum/habana/transformers/models/llama/__init__.py
- optimum/habana/transformers/models/llama/modeling_llama.py
- optimum/habana/transformers/models/modeling_all_models.py
- optimum/habana/transformers/trainer.py
Cherry-pick "disable sdpa" to transformer_4.38 branch.
> Cherry-pick other changes needed for transformer_4.38 branch.

- examples/stable-diffusion/training/README.md
This PR fixes the 8x example command and the inference example for ControlNet.
> Fix ControlNet README

- examples/text-to-speech/README.md
- examples/text-to-speech/requirements.txt
- examples/text-to-speech/run_pipeline.py
- optimum/habana/transformers/modeling_utils.py
- optimum/habana/transformers/models/__init__.py
- optimum/habana/transformers/models/speecht5/__init__.py
- optimum/habana/transformers/models/speecht5/modeling_speecht5.py
> speecht5 optimization

- README.md
- docs/source/index.mdx
> Add Whisper and SpeechT5 to model table

- tests/test_encoder_decoder.py
`max_source_length` must be specified for "opus-mt-zh-en" following https://github.com/huggingface/optimum-habana/commit/7ef84d87ce6a62d4e3fe8237bba2d411ae5c19ec.
The default is 1024 and it has to be set to 512.
> Fix test_encoder_decoder.py for opus-mt-zh-en

- optimum/habana/transformers/generation/utils.py
> Fix redundant bucket internal and hpu graph setting

- .github/workflows/slow_tests_gaudi2.yml
- Makefile
- examples/language-modeling/README.md
- tests/test_fsdp_examples.py
> Add Llama test for fsdp

- examples/protein-folding/run_esmfold.py
> enable dynamic shapes for esmfold

- optimum/habana/transformers/modeling_utils.py
- optimum/habana/transformers/models/__init__.py
- optimum/habana/transformers/models/wav2vec2/__init__.py
- optimum/habana/transformers/models/wav2vec2/modeling_wav2vec2.py
> Revert Wav2Vec2 TDNNLayer forward function same as transformer v4.37.2

- optimum/habana/transformers/models/llama/modeling_llama.py
Fixes graph break due to fused_rms_norm check
> RMS Norm Graph break fix torch compile

- tests/test_fsdp_examples.py
Clean-up flags from bert-base FSDP flags.
> Clean-up BERT-BASE FSDP test

- tests/test_diffusers.py
Skipping the SDXL test in CI for now since the dataset used in the test is not available at the moment (more information [here](https://huggingface.co/datasets/lambdalabs/pokemon-blip-captions/discussions/11)).
Also removing the LoRA SDXL test since LoRA is not usable in the SDXL training example anymore.
> Skip SDXL test in CI

- optimum/habana/transformers/models/falcon/modeling_falcon.py
- optimum/habana/transformers/models/llama/modeling_llama.py
- tests/transformers/tests/models/falcon/test_modeling_falcon.py
> Synapse 1.15 addition2

- Makefile
This PR removes the line in the CI where Diffusers `main` is installed as it is leading to an issue in the ControlNet test (see [here](https://github.com/huggingface/optimum-habana/actions/runs/8458571829/job/23176366293#step:4:3924)).
> Remove installation from source for Diffusers in CI

- optimum/habana/transformers/models/falcon/modeling_falcon.py
- optimum/habana/transformers/models/llama/modeling_llama.py
Fix llama/falcon pytest when token_idx is None
> Synapse 1.15addition4

- tests/test_examples.py
Avoids Dataset re-download for reducing overall CI times.
> Avoid dataset re-download.

- tests/test_examples.py
This PR fixes issues with #848.
> Fix PR #848

- examples/text-generation/text-generation-pipeline/pipeline.py
- examples/text-generation/text-generation-pipeline/run_pipeline.py
- added batched input support
- added support of iterations
- improved output and throughput calculation
This aligns options utilized by run_pipeline.py with those in run_generation.py
Since these two scripts share same argument parser it is quite expected that all command line options should work the same for both scripts, which is not true now. Options like batch_size and n_iterations were not supported by run_pipeline.py, but these are quite valuable options for performance measurements
> text generation pipeline: Extended functionality to align with run_generation script

- setup.py
Fixes #847. Moves `pytest` dependency so that it is a hard dependency.
> Move pytest dependency

- examples/trl/dpo.py
- examples/trl/sft.py
- tests/baselines/llama_7b.json
- tests/test_examples.py
> add ci test for SFT and DPO

- examples/text-generation/run_lm_eval.py
Fixed a bug which adds the "reuse_cache" flag regardless of the model type
> Fixed "reuse_cache" Bug

- tests/baselines/llama_7b.json
- tests/test_examples.py
> Fix SFT, DPO CI on Gaudi1

- README.md
- docs/source/index.mdx
> Add SDXL in README

- optimum/habana/transformers/modeling_utils.py
- optimum/habana/transformers/models/__init__.py
- optimum/habana/transformers/models/falcon/__init__.py
- optimum/habana/transformers/models/falcon/modeling_falcon.py
> fix falcon 180b oom issue if peft > 0.6.2

- tests/baselines/CodeLlama_13b_Instruct_hf.json
- tests/test_encoder_decoder.py
- tests/test_examples.py
- tests/test_text_generation_example.py
- tests/utils.py
Enabled CodeLlama finetune(13b) and inference(34b), StableLM and T5-small inference models in CI.
> Enabled additional models in CI

- examples/stable-diffusion/text_to_image_generation.py
- optimum/habana/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py
- optimum/habana/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py
Add profiling to pipeline_stable_diffusion and pipeline_stable_diffusion_xl and update text_to_image_generateion.py accordingly.
> Add HabanaProfile to Stable Diffusion and XL

- tests/transformers/tests/models/falcon/test_modeling_falcon.py
- tests/transformers/tests/models/gpt2/test_modeling_gpt2.py
- tests/transformers/tests/models/t5/test_modeling_t5.py
Reference task: [GS-114](https://habana.atlassian.net/browse/GS-114)
“Falcon” and “T5” produce a deterministic result. Expected output has been updated.
”GPT2” produces each time a different result.
All three models produce deterministic token length.
> Pytest accuracy updates for Falcon, T5, GPT2

- tests/transformers/tests/models/wav2vec2/test_modeling_wav2vec2.py
Fix the data type for compute mask in wav2vec2 test. 
> Fix for wav2vec2 test cases

- optimum/habana/checkpoint_utils.py
This PR provide more reasonable error in case of loading non-Pytorch model. Otherwise user sees following exception, which may be considered as script logic issue: ```UnboundLocalError: local variable 'allow_patterns' referenced before assignment```
> utils: return more reasonable error in case of attempt of non-PyTorch model loading

- examples/text-generation/text-generation-pipeline/README.md
- examples/text-generation/text-generation-pipeline/pipeline.py
- examples/text-generation/text-generation-pipeline/run_pipeline_langchain.py
Added LangChain script with Q&A example, which supports the same command line options as other generation scripts
> text generation: added langchain pipeline script

- examples/audio-classification/run_audio_classification.py
- examples/speech-recognition/README.md
- tests/baselines/ast_finetuned_speech_commands_v2.json
- tests/test_examples.py
- tests/utils.py
- Fix for `MIT/ast-finetuned-speech-commands-v2` with run_audio_classification.py which fails with `AttributeError: 'ASTForAudioClassification' object has no attribute 'freeze_feature_encoder'`
- Typo fix in README
- Added test `test_run_audio_classification_ast-finetuned-speech-commands-v2_multi_card`: 3.50 min to run on Gaudi2
> Fix for AST models

- tests/transformers/tests/models/t5/test_modeling_t5.py
resolve unable to create tensor issue for PYTEST-t5 test_summarization
> Fix ValueError for test_summarization

- examples/audio-classification/README.md
Adding information to the README file in the audio-classification examples about using the extra parameter "--ddp_find_unused_parameters" to fix issues with distributed training for models with unused parameters.
> Add information to the audio-classification examples README about  --ddp_find_unused_parameters parameter

- tests/test_text_generation_example.py
> Added Llama-2 fp8 text-generation test cases

- .github/workflows/slow_tests.yml
- .github/workflows/slow_tests_gaudi2.yml
- tests/ci/sentence_transformers.sh
- tests/test_sentence_transformers.py
> Add Gaudi CI for Sentence Transformers

- tests/test_diffusers.py
- tests/test_examples.py
This PR adds a `IS_GAUDI2` variable at the top of CI scripts to avoid calling `os.environ.get("GAUDI2_CI", "0")` multiple times.
> Small CI refacto

- examples/text-generation/utils.py
> llama70b one card to infer device map with max memory limitation 

- examples/language-modeling/run_lora_clm.py
- optimum/habana/peft/__init__.py
- optimum/habana/peft/layer.py
> fix fsdp lora torch compile issue

- examples/text-generation/run_generation.py
> Warn user when using --disk_offload without hqt 

- examples/stable-diffusion/text_to_image_generation.py
- optimum/habana/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py
- optimum/habana/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_ldm3d.py
- optimum/habana/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_upscale.py
- optimum/habana/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py
- optimum/habana/utils.py
Fixes throughput calculation for diffusers when `batch size < throughput_warmup_steps`
> Fix warmup for diffusers when batch size < throughput_warmup_steps

- examples/language-modeling/README.md
Added instructions in README for enabling torch.compile mode with Roberta-Large model.
> Add torch.compile instructions for Roberta-Large

- optimum/habana/transformers/models/gpt_neox/modeling_gpt_neox.py
> Fix gpt_neox, stablelm inference regression caused by RoPE dtype

- examples/language-modeling/README.md
- tests/test_fp8_examples.py
> Initial commit for fp8 CI

- examples/text-generation/run_generation.py
- optimum/habana/transformers/generation/__init__.py
- optimum/habana/transformers/generation/stopping_criteria.py
- optimum/habana/transformers/generation/utils.py
- optimum/habana/transformers/modeling_utils.py
> Sasarkar/transformers 4.40 patches for stopping criteria

- optimum/habana/transformers/generation/stopping_criteria.py
- optimum/habana/transformers/generation/utils.py
> fix eos problem

- optimum/habana/transformers/models/mistral/modeling_mistral.py
Fix performance issue in mistral on the first token generation
> fix performance issue in mistral (#181)

- examples/text-generation/README.md
Add unifier script and disk offload flag usages to README
Readme cr fixes
small fix
more fixes
> Add unifier script and disk offload flag usages to README.

- examples/text-generation/README.md
- optimum/habana/checkpoint_utils.py
Mixtral-8x22b model loading needs to be on meta dueto host memory limitation.
> Add mixtral for meta device load due to mixtral-8x22b model size

- examples/text-generation/quantization_tools/unify_measurements.py
> Update unifier script

- tests/test_text_generation_example.py
> Update text-generation CI configuration for falcon and Mixtral

- examples/multi-node-training/README.md
> Update multi-node README to check ssh connection issue

- tests/test_text_generation_example.py
` python3 run_generation.py --model_name_or_path Qwen/Qwen1.5-7B --batch_size 4 --use_kv_cache --max_new_tokens 100 --use_hpu_graphs --bf16` produces 488 tps
(this is pytest cmd line)
`run_generation.py --model_name_or_path Qwen/Qwen1.5-7B --batch_size 4 --use_kv_cache --max_new_tokens 100 --use_hpu_graphs --bf16  --trim_logits --attn_softmax_bf16 --use_flash` produces 513 tps
> sasarkar/Update test_text_generation_example.py

- examples/question-answering/README.md
- tests/test_examples.py
README update for migrating to torch.compile
> BERT training migrated to torch.compile (#203)

- tests/test_examples.py
creating pr on behalf of @yeonsily 
> sarkar/Update test_examples.py

- optimum/habana/transformers/models/llama/modeling_llama.py
On behalf of @libinta 
fixes deepspeed codellama
> sarkar/Update modeling_llama.py: deepspeed fix for codellama

- tests/test_examples.py
> Change the way to unset environemt variable for gpt-neox ci

- examples/question-answering/README.md
> Updating batch_size of Albert-XXL in README (#238)

- examples/text-generation/text-generation-pipeline/README.md
- examples/text-generation/text-generation-pipeline/pipeline.py
- tests/test_text_generation_example.py
python run_pipeline.py --model_name_or_path mistralai/Mistral-7B-v0.3  --use_kv_cache --max_new_tokens 20 --prompt "He is working on"
Fix the following error:
06/09/2024 04:11:28 - INFO - __main__ - device: hpu, n_hpu: 0, bf16: False
06/09/2024 04:11:28 - INFO - __main__ - Model initialization took 10.879s
File "/workspace/optimum-habana/examples/text-generation/text-generation-pipeline/run_pipeline.py", line 63, in <module>
main()
File "/workspace/optimum-habana/examples/text-generation/text-generation-pipeline/run_pipeline.py", line 44, in main
pipe = GaudiTextGenerationPipeline(args, logger)
File "/workspace/optimum-habana/examples/text-generation/text-generation-pipeline/pipeline.py", line 8, in __init__
self.model, self.tokenizer, …
> Fix the error of running run_pipeline.py of text_generation example

- examples/text-generation/README.md
* Fixed the command line for `run_lm_eval.py` help message displaying
* Updated flash attention example command line
> Fix text-generation example README.md

- examples/text-generation/text-generation-pipeline/README.md
- examples/trl/dpo.py
- examples/trl/ppo.py
- examples/trl/reward_modeling.py
- examples/trl/sft.py
- optimum/habana/transformers/models/llama/configuration_llama.py
- optimum/habana/transformers/models/llama/modeling_llama.py
- optimum/habana/trl/trainer/ppo_trainer.py
Avoid nan issue in TRL by bypassing fusedrope
Fix compute_rewards outputs in ppo_trainer.py
> sarkar/Fix TRL training issues

- examples/summarization/run_summarization.py
- examples/text-generation/README.md
Fix the readme for disk_offload with better instructions.
Fix the readme validation for run_summarization with beam_search 1
> Fix issues during readme validation

- optimum/habana/transformers/models/mixtral/modeling_mixtral.py
> Mixtral typo fix

- examples/text-generation/utils.py
fix for selective seq length test with batch size 1.
Propagation from OHF https://github.com/HabanaAI/optimum-habana-fork/commit/175256e12df2e650dae5b21a2b8022f542acb088
> fix for selective seq length test with batch size 1 

- optimum/habana/transformers/models/gpt_neox/modeling_gpt_neox.py
> Enable FusedRoPE using float32 for gpt-neox model

- examples/language-modeling/run_lora_clm.py
- tests/baselines/falcon_40b.json
- tests/baselines/llama_7b.json
- tests/test_examples.py
> fix nan loss of gemma and crash if dataset_concatenation is not set

- examples/audio-classification/README.md
- examples/image-classification/README.md
- examples/language-modeling/README.md
- examples/question-answering/README.md
- examples/stable-diffusion/README.md
- examples/text-classification/README.md
- examples/text-generation/README.md
Update examples' batchsize referring to [Performance Data](https://developer.habana.ai/get-started/habana-models-performance/) and validation.
> Update examples batchsize in README

- examples/stable-diffusion/training/train_text_to_image_sdxl.py
Fixes OOM issue during validation in SDXL fine-tuning script
Out Of Memory issue observed after several validation cycles in SDXL fine-tuning script:
```
File "/usr/local/lib/python3.10/dist-packages/habana_frameworks/torch/hpu/graphs.py", line 51, in replay
_hpu_C.replay(self.hpu_graph, asynchronous)
RuntimeError: [Rank:0] FATAL ERROR :: MODULE:PT_SYNHELPER workspace Allocation of size ::6450192384 failed!
```
After this fix full training with validation finishes successfully.
> Fix OOM error in SDXL Fine-Tuning validation stage

- examples/text-generation/run_generation.py
> generation example: print number of warmup iterations

- optimum/habana/distributed/tensorparallel.py
Workaround to overcome the accuracy/output correctness issue in torch.compile all_reduce for batch sizes greater than 124.
This is a temporary fix and needs to be addressed properly in future updates.
> Disable torch.compile for all_reduce when parallel_strategy is set to "tp"

- optimum/habana/accelerate/accelerator.py
- optimum/habana/accelerate/utils/dataclasses.py
1) Return a ``torch.device`` for the specified ``device_id`` (This change is required for FSDP).
2) Similar to CUDA variant [_get_device_from_device_id](https://github.com/pytorch/pytorch/blob/main/torch/distributed/fsdp/_init_utils.py#L795).  
> Change the device_id for FSDP plugin

- optimum/habana/transformers/models/falcon/modeling_falcon.py
- optimum/habana/transformers/models/llama/modeling_llama.py
This solves torch compile issue related to using self argument in HQT patched module
> Set KV Cache update as static method

- optimum/habana/transformers/generation/utils.py
use the tensor containing scalar instead of 1-D tensor. this would avoid "one of the tensors on CPU" error.
> To fix CPU tensor issue

- optimum/habana/transformers/generation/utils.py
fix data-type mismatch for mlperf_inference accuracy test
> fix data-type mismatch for mlperf_inference accuracy test

- examples/text-generation/requirements_lm_eval.txt
- examples/text-generation/run_lm_eval.py
https://github.com/HabanaAI/optimum-habana-fork/pull/274
> fix spawn MP context, limit cpu and download data

- examples/stable-diffusion/README.md
- examples/stable-diffusion/text_to_image_generation.py
- optimum/habana/diffusers/pipelines/stable_diffusion_3/pipeline_stable_diffusion_3.py
- Removed duplicate code function in SD3 which can be inherited
- Added default scheduler in text-to-image sample (SD3 uses default `FlowMatchEulerDiscreteScheduler`)
> Refactor SD3

- optimum/habana/transformers/models/llama/modeling_llama.py
PR 1202 is breaking Mixtral since it doesn't pass config.
This change fixes  both for Mixtral and Llama.
> Fix max_position_embedding error for Mixtral

- tests/test_diffusers.py
> Fix diffusers. From PR 1208

- optimum/habana/transformers/modeling_utils.py
fixes the generic error
```
FAILED tests/transformers/tests/models/gpt_neox/test_modeling_gpt_neox.py::GPTNeoXModelTest::test_retain_grad_hidden_states_attentions - TypeError: GPTNeoXSdpaAttention.forward() got an unexpected keyword argument 'token_idx'
```
tested locally and it works as expcted. 
> fea(): fixed pytest errors for gptneox

- tests/transformers/tests/test_modeling_common.py
Fix: `RUN_SLOW=true  GAUDI2_CI=1 python -m pytest tests/transformers/tests/models/g
pt2/test_modeling_gpt2.py  -v -s -k test_torch_fx`
> Sarkar/transformers 4.43 fixes for gpt2 test_torch_fx

- optimum/habana/transformers/models/gpt_bigcode/modeling_gpt_bigcode.py
Today customers want to use StarCoder + tgi-gaudi. tgi-gaudi disables tensor cache by default, this behavior is not going to be changed as several models are optimized with this.
When tensor cache is disabled and we set `--use_hpu_graphs`, `--use_kv_cache`, the Starcoder model (`gpt_bigcode`) gave an `Empty tensor optional` error.
When tensor cache is disabled, hpu graphs don't track intermediate tensors- they only track inputs and outputs of functions.
On debugging with SW team, we rootcaused the issue to an in place operation `torch.index_add_()` done on an intermediate tensor (not input or output). Replacing this with the out of memory equivalent resolves the issue.
Ideally we would wrap this in a conditional (i.e run the in memory index_add_() when tensor cache is not disabled) but in …
> Resolve "empty tensor optional" error with hpu_graphs + kv cache for StarCoder

- optimum/habana/transformers/models/wav2vec2/modeling_wav2vec2.py
- tests/transformers/tests/test_modeling_common.py
Fix some VIT tests, explain failure of wav2vec test
```
[31mFAILED[0m tests/transformers/tests/models/vit/test_modeling_vit.py::[1mViTModelTest::test_attention_outputs[0m - AttributeError: 'NoneType' object has no attribute 'shape'
[31mFAILED[0m tests/transformers/tests/models/vit/test_modeling_vit.py::[1mViTModelTest::test_retain_grad_hidden_states_attentions[0m - AttributeError: 'NoneType' object has no attribute 'retain_grad'
```
> sarkar/Fix VIT, add wav2vec comment

- optimum/habana/transformers/models/llama/modeling_llama.py
In modeling_llama.py, the position_embedding check along with logger.warning_once causes the graph recompilation during decoding phase. As we are not using position_embeddings, remove the logic to check position_embeddings for now.
> work around llama torch.compile performance issue

- tests/transformers/tests/generation/test_utils.py
Fixes contrastive search tests for bert and roberta
RUN_SLOW=true  GAUDI2_CI=1 python -m pytest tests/transformers/tests/models/bert/test_modeling_bert.py -v -s -k test_contrastive_generate_dynamic_shapes
RUN_SLOW=true  GAUDI2_CI=1 python -m pytest tests/transformers/tests/models/roberta/test_modeling_roberta.py -v -s -k test_contrastive_generate_dynamic_shapes
> Fix bert/roberta contrastive search tests

- .github/workflows/check_code_quality.yml
- optimum/habana/transformers/gaudi_configuration.py
The style check workflow now automatically posts a comment asking to run `make style` if the style check failed.
> Improve style check workflow

- examples/stable-diffusion/training/train_text_to_image_sdxl.py
- Support scheduler option selection in train_text_to_image.py  for fine-tuning.
> Added scheduler selection for SDXL fine-tuning

- .github/workflows/fast_tests.yml
- .github/workflows/slow_tests.yml
- .github/workflows/slow_tests_gaudi2.yml
- Makefile
- README.md
- docs/Dockerfile
- docs/source/installation.mdx
- docs/source/usage_guides/deepspeed.mdx
- examples/audio-classification/README.md
- examples/gaudi_spawn.py
- examples/kubernetes/Dockerfile
- examples/kubernetes/README.md
- examples/kubernetes/README.md.gotmpl
- examples/kubernetes/docker-compose.yaml
- examples/multi-node-training/EFA/Dockerfile
- examples/multi-node-training/GaudiNIC/Dockerfile
- examples/speech-recognition/README.md
- examples/text-generation/README.md
- examples/text-generation/text-generation-pipeline/README.md
- notebooks/AI_HW_Summit_2022.ipynb
- optimum/habana/accelerate/accelerator.py
- optimum/habana/accelerate/state.py
- optimum/habana/transformers/models/llama/modeling_llama.py
- optimum/habana/utils.py
- tests/baselines/flan_t5_xxl.json
- tests/baselines/gpt2_xl.json
- tests/baselines/gpt_neox_20b.json
- tests/baselines/roberta_base.json
- tests/baselines/roberta_large.json
- tests/test_image_to_text_example.py
> Upgrade SynapseAI version to 1.17.0

- .github/workflows/check_code_quality.yml
The current workflow `check_code_quality.yml` workflow is triggered for the `pull_request` event. However, posting a comment in the PR using `peter-evans/create-or-update-comment` will not work in that case for PRs coming from forks. See [here](https://github.com/peter-evans/create-or-update-comment?tab=readme-ov-file#action-inputs) and [there](https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#restrictions-on-repository-forks) for more information.
> Change triggering event for code style check

- optimum/habana/transformers/models/gptj/modeling_gptj.py
this PR fixes the following test cases failure
`RUN_SLOW=true  GAUDI2_CI=1 python -m pytest tests/transformers/tests/models/gptj/test_modeling_gptj.py  -v -s -k test_greedy_generate_dict_outputs_use_cache`
`GAUDI2_CI=1 RUN_SLOW=1 python -m pytest tests/transformers/tests/models/gptj/test_modeling_gptj.py -s -v  -k test_gptj_gradient_checkpointing`
> gptj: fix missing token_idx

- examples/summarization/requirements.txt
Fixes the following error in `run_summarization.py` example
```
[12-08-24 19:39:03.412425 ] [rank4]:   File "/root/repos/optimum-habana/examples/summarization/run_summarization.py", line 737, in postprocess_text
[12-08-24 19:39:03.412430 ] [rank4]:     preds = ["\n".join(nltk.sent_tokenize(pred)) for pred in preds]
[12-08-24 19:39:03.412435 ] [rank4]:   File "/root/repos/optimum-habana/examples/summarization/run_summarization.py", line 737, in <listcomp>
[12-08-24 19:39:03.412440 ] [rank4]:     preds = ["\n".join(nltk.sent_tokenize(pred)) for pred in preds]
[12-08-24 19:39:03.412445 ] [rank4]:   File "/tmp/.tox/t5small/lib/python3.10/site-packages/nltk/tokenize/{}init{}.py", line 106, in sent_tokenize
[12-08-24 19:39:03.412450 ] [rank4]:     tokenizer = PunktTokenizer(language)
[12-08-24 …
```
> fix(nltk): fixed the version to working one

- tests/ci/sentence_transformers.sh
Updating script so it can be directly used by CI.
> Updating to avoid hardcoding tests in CI framework

- optimum/habana/transformers/models/llama/modeling_llama.py
fix “casual” to  "causal", make it the same name with torch sdpa paranmeters name.
https://pytorch.org/docs/stable/generated/torch.nn.functional.scaled_dot_product_attention.html
> Fix spelling errors

- optimum/habana/accelerate/state.py
Change-Id: Ice7ac501ba758d7eb2f9dcd7a348703056e23a98
> [SW-196669] Set HLS_MODULE_ID only if it wasn't set previously

- examples/summarization/requirements.txt
- examples/summarization/run_summarization.py
- notebooks/AI_HW_Summit_2022.ipynb
- Reverts #1247 
- Fixes the nltk download issue. 
```
GAUDI2_CI=1 RUN_SLOW=1 python -m pytest tests/test_encoder_decoder.py -s -v -k test_text_summarization_bf16[token0-facebook/bart-large-cnn-Habana/bart-3.9-28.9801-2-2]
============================================================================================= 1 passed, 5 deselected in 97.13s (0:01:37) ==============================================================================================
```
```
GAUDI2_CI=1 RUN_SLOW=1 python -m pytest tests/test_encoder_decoder.py -s -v -k  test_text_summarization_bf16[token0-t5-3b-Habana/t5-2.955-21.8877-2-1] 
============================================================================================= 1 passed, 5 deselected in 258.55s (0:04:18) …
```
> [SW_196667] fix(nltk): Revert 1247. Updated the version. added the punkt_tab download

- examples/text-generation/README.md
- examples/text-generation/run_generation.py
- examples/text-generation/utils.py
- optimum/habana/transformers/models/mixtral/modeling_mixtral.py
> Gpt bigcode fused sdpa

- .github/workflows/check_code_quality.yml
- .github/workflows/failed_code_quality_check_comment.yml
- optimum/habana/version.py
> Fix failed code quality check comment workflow

- examples/audio-classification/README.md
- tests/baselines/ast_finetuned_speech_commands_v2.json
- tests/test_examples.py
Add trust_remote_code to README and CI tests.
- x Did you make sure to update the documentation with your changes?
- [x ] Did you write any new necessary tests?
> Add trust_remote_code to audio classification CI tests and README.

- optimum/habana/transformers/generation/utils.py
> remove _expand_inputs_for_generation for greedy_Search

- examples/audio-classification/README.md
Follow up on #1262 with one more `--trust_remote_code True` fix. 
> fix(ac): Added trust_remote in README inference

- optimum/habana/diffusers/pipelines/stable_diffusion_3/pipeline_stable_diffusion_3.py
> Add profiler to SD3

- optimum/habana/transformers/models/llama/modeling_llama.py
> Fix memory regression for modeling llama

- optimum/habana/transformers/generation/utils.py
Profile step should be taken after device execution finished for that step.
> Fix profiling step with device finish execution for text-generation

- optimum/habana/transformers/models/mixtral/modeling_mixtral.py
Originally the mark_step change was ported from https://github.com/HabanaAI/optimum-habana-fork/pull/260
But reverting the change as OHF decided to revert it.
> Revert mark_step in mixtral model from PR #1260

- optimum/habana/transformers/generation/utils.py
> Add missing condtion check in tensor creation in greedy search

- optimum/habana/transformers/generation/utils.py
> Remove clone() to improve performance

- optimum/habana/transformers/models/gpt_bigcode/modeling_gpt_bigcode.py
According to the https://docs.habana.ai/en/latest/PyTorch/Reference/Python_Packages.html#hpex-kernels-fusedsdpa , 
we should pass 'recompute_mode' as API parameters.
> Update FusedSDPA calling method as Gaudi documentation

- tests/test_text_generation_example.py
- Added Mixtral fp8 with 2 rank and mixstral-specific quant file. 
- Updated the perf based on new results. 
- Notes:
- The 4 added tests, adds about 40min to text-gen CI whic is <8% of current text-gen total runtime. 
- [SW-196653] Mixtral fp8 perf was tagged by RD team during 1.13 release to be revisited. It is wise to be added here. 
All 5 modified tests have ran locally and passed:
```
============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-7.4.4, pluggy-1.5.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /root/optimum-habana
configfile: setup.cfg
collecting ... collected 38 items / 33 deselected / 5 selected
tests/test_text_generation_example.py::test_text_generation_fp8[token0-mistralai/Mixtral-8x7B-v0.1-1-1-Tru …
```
> [SW-196653] Ig/Mixtral fp8

- .github/workflows/failed_code_quality_check_comment.yml
- optimum/habana/version.py
It seems there is an issue with `actions/download-artifact@v4`, now doing something similar to https://github.com/huggingface/doc-builder/blob/fcea09086f6dec68ef9ce419f164c6c33e8fb5f4/.github/workflows/upload_pr_documentation.yml#L48.
> Potential fix for the failed code quality check comment workflow

- optimum/habana/checkpoint_utils.py
> Add the deepspeed injection_policy of mistral

- examples/text-generation/run_lm_eval.py
I add `with torch.no_grad():` before evaluating, because I I encountered memory increase when not using hpu graph.
> Fix text-generation example lm_eval evaluation

- README.md
This PR adds a small section to the README to explain how to use our Transformers development branch.
> Add section to README about Transformers development branch

- optimum/habana/transformers/trainer.py
Change-Id: I49d2dafefd4d34f8c0165855611720fd7beecd4d
> use native checkpointing under compile mode

- examples/language-modeling/README.md
- examples/language-modeling/run_lora_clm.py
- examples/text-generation/utils.py
> fix eos issue in finetune/generation

- optimum/habana/sentence_transformers/st_gaudi_trainer.py
Checks for PEFT Model in _wrap_model to fix crash detailed below.
Sentence Transformer training script modified to train with LoRA crashed when using use_hpu_graphs_for_training is True.
```
model = SentenceTransformer(model_name)
peft_config = LoraConfig(
r=16,
lora_alpha=64,
lora_dropout=0.05,
bias="none",
inference_mode=False,
target_modules=["key", "query", "value"],
)
model = get_peft_model(model, peft_config)
..
args = SentenceTransformerGaudiTrainingArguments(
..
use_hpu_graphs_for_training=True,
)
```
Crash
```
File "/root/optimum-habana/examples/sentence-transformers-training/nli/training_peft.py", line 206, in <module>
main()
File "/root/optimum-habana/examples/sentence-transformers-training/nli/training_peft.py", line 194, in main …
```
> Fix Sentence Transformer HPU graphs for training with PEFT model

- optimum/habana/transformers/generation/utils.py
Fixes ZeroDivisionError in constrained beam search for models with static shapes
`python examples/text-generation/run_generation.py --model_name_or_path openai-community/gpt2 --use_kv_cache --max_new_tokens 20  --use_hpu_graph --bf16 --no-ignore_eos --prompt "The weather" --force_words "hot " --num_beams 10`
```
File "/root/optimum-habana/examples/text-generation/run_generation.py", line 692, in <module>
main()
File "/root/optimum-habana/examples/text-generation/run_generation.py", line 461, in main
generate(None, args.reduce_recompile)
File "/root/optimum-habana/examples/text-generation/run_generation.py", line 432, in generate
outputs = model.generate(
File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in …
```
> Fix ZeroDivisionError in constrained beam search with static shapes

- optimum/habana/transformers/models/falcon/modeling_falcon.py
> Falcon inference crash fix for falcon-40b model

- examples/image-to-text/README.md
- examples/image-to-text/run_pipeline.py
- optimum/habana/transformers/models/clip/modeling_clip.py
Enable INC for llava models and change softmax to use torch.nn.functional.softmax  as its supported module by INC.
https://docs.habana.ai/en/latest/PyTorch/Inference_on_PyTorch/Inference_Using_FP8.html#supported-functions
> Enable INC for llava models and change softmax to use torch.nn.functional.softmax as its supported module by INC

- optimum/habana/transformers/models/modeling_all_models.py
disable sdpa for wav2vec2 for now, as it does not give acceptable performance.
> use eager attention for wav2vec2

- optimum/habana/transformers/models/modeling_all_models.py
> switch roberta from sdpa to eager attn

- optimum/habana/transformers/trainer.py
This reverts commit c39a0b7d778eaf53a3b605e4260c4a742b5905a2.
Change-Id: Iafaacd11faf5eff6bd68ed146b2978683e295a9b
> Revert "[SW-199559] use native checkpointing under compile mode"

- examples/text-generation/run_generation.py
As part of UX enhancement drive,  got feedback to make this flag completely optional and not needing explicit  True/False when used.
> Minor UX enhancement

- optimum/habana/transformers/models/gpt_bigcode/modeling_gpt_bigcode.py
This PR fixes wrong indentations brought by PR https://github.com/huggingface/optimum-habana/pull/1282 (result of autorebase)
> gpt_bigcode: fixed wrong indentation

- optimum/habana/transformers/models/bart/modeling_bart.py
- optimum/habana/transformers/trainer_seq2seq.py
Fix graph breaks for BART in torch.compile mode.
> Fix graph breaks for BART in torch.compile mode.

- examples/text-generation/utils.py
Support for transformers without self.model to torch.compile
> Support for transformers without self.model to torch.compile

- optimum/habana/transformers/gradient_checkpointing.py
This PR is a minor fix and removing unnecessary class, since we limited this module to PyTorch > 2.1
> Clean up the code and remove unnecessary class

- tests/transformers/tests/models/llama/test_modeling_llama.py
- tests/transformers/tests/models/mistral/test_modeling_mistral.py
- tests/transformers/tests/models/mixtral/test_modeling_mixtral.py
- tests/transformers/tests/models/vit/test_modeling_vit.py
- tests/transformers/tests/models/wav2vec2/test_modeling_wav2vec2.py
updating optimum-habana-fork model test as per the transformers test suite.
adding has done for mistral, mixtral, llama, vit and wav2vec2 test models.
> Enhance transformers test suite in Optimum-habana-4.43.4 Auto pr 07654de

- tests/transformers/tests/models/bert/test_modeling_bert.py
- tests/transformers/tests/models/bridgetower/test_modeling_bridgetower.py
- tests/transformers/tests/models/falcon/test_modeling_falcon.py
- tests/transformers/tests/models/gpt2/test_modeling_gpt2.py
updating optimum-habana-fork model test as per the transformers test suite.
adding has done for bert, bridgetower, gpt2 and falcon  test models.
> Enhance transformers test suite in Optimum-habana-4.43.4 (auto PR 8926a4b)

- tests/transformers/tests/models/gpt_neox/test_modeling_gpt_neox.py
- tests/transformers/tests/models/gptj/test_modeling_gptj.py
- tests/transformers/tests/models/swin/test_modeling_swin.py
updating optimum-habana test models as per the transformers test suite.
adding changes for swin, gptj and gptneox test suite.
> Enhance Optimum-habana as per transformers-4.43.4

- optimum/habana/transformers/models/llama/modeling_llama.py
Truncate the cached max seq len
> Truncate the cached max seq len

- optimum/habana/transformers/models/gpt_neox/modeling_gpt_neox.py
> Fix gpt-neox training accuracy issue.

- examples/text-generation/quantization_tools/unify_measurements.py
Change-Id: Ia23b3049bd54dd18c8ae779e027901cf0cd1de8b
This PR supports a case we have measurements in PCQ mode and we have multi weights and outputs values
> unify_measurements.py script support to unify PCQ 70B 8x

- examples/text-generation/quantization_config/maxabs_quant_scalar_scales.json
Utilizes scales as scalar optimization
Change-Id: I90b345d571f91adf2e20f7a9ffce14f84e8bdffd
> Add quantization config for low bs case

- optimum/habana/transformers/models/starcoder2/modeling_starcoder2.py
Description of the issue and fix in https://github.com/huggingface/optimum-habana/pull/1149#issuecomment-2272936561.
> Fix StarCoder2 inference

- optimum/habana/diffusers/models/unet_2d_condition.py
Move import of `habana_frameworks.torch.core` to fix the text-to-image example.
> Fix text-to-image example

- .github/workflows/fast_tests.yml
- .github/workflows/slow_tests.yml
- .github/workflows/slow_tests_gaudi2.yml
- Makefile
- README.md
- docs/Dockerfile
- docs/source/installation.mdx
- docs/source/usage_guides/deepspeed.mdx
- examples/audio-classification/README.md
- examples/gaudi_spawn.py
- examples/kubernetes/Dockerfile
- examples/kubernetes/README.md
- examples/kubernetes/README.md.gotmpl
- examples/kubernetes/docker-compose.yaml
- examples/multi-node-training/EFA/Dockerfile
- examples/multi-node-training/GaudiNIC/Dockerfile
- examples/speech-recognition/README.md
- examples/text-generation/README.md
- examples/text-generation/text-generation-pipeline/README.md
- notebooks/AI_HW_Summit_2022.ipynb
- optimum/habana/accelerate/accelerator.py
- optimum/habana/accelerate/state.py
- optimum/habana/utils.py
> Upgrade to SynapseAI 1.18.0

- optimum/habana/transformers/generation/utils.py
- optimum/habana/transformers/models/gemma/modeling_gemma.py
This function call was missing so we get an error if run with --use_kv_cache and --reuse_cache .
> Added missing allocate_kv_cache() call in CausalLM class

- examples/text-generation/README.md
Update text-gen README.md to add auto-gptq fork install steps
> Update text-gen README.md to add auto-gptq fork install steps

- setup.py
This PR is to upgrade the sentence transformer package to latest version v3.2.1. 
There are three test places related to sentence transformer package and have tested these three test places and all passed. 
Welcome for any comments!
Thanks.
> update sentence transformer to v3.2.1

- examples/language-modeling/README.md
> readme: replace tabs with spaces

- .github/workflows/fast_tests.yml
> Move fast tests to Gaudi2

- examples/stable-diffusion/training/README.md
- examples/stable-diffusion/training/textual_inversion_sdxl.py
- tests/test_diffusers.py
This PR adds a script to run Textual Inversion fine-tuning on Gaudi for XL diffusion models, such as "stabilityai/stable-diffusion-xl-base-1.0", "cagliostrolab/animagine-xl-3.1", and so on.  README doc is updated accordingly.
> Add textual inversion XL for Gaudi

- examples/text-generation/utils.py
keep_input_mutations is now True by default
> Remove keep_input_mutations

- examples/stable-diffusion/text_to_image_generation.py
- optimum/habana/diffusers/models/attention_processor.py
- optimum/habana/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_mlperf.py
Add support for MLPERF SD XL pipeline
> Add support for MLPERF optimized pipeline from example

- examples/text-generation/utils.py
- optimum/habana/utils.py
add check_neural_compressor_min_version for 4 bit loading behavior to fix [SW-195965].
It is fixed when INC version >= 3.2
> add check_neural_compressor_min_version for 4 bit behavior

- tests/test_functional_text_generation_example.py
Fail gracefully in case of variable ```GAUDI2_CI``` not set.
Before fix:
```
============================================================================================================================================= test session starts =============================================================================================================================================
platform linux -- Python 3.10.12, pytest-8.3.3, pluggy-1.5.0
rootdir: /var/work/optimum-habana
configfile: setup.cfg
collected 0 items / 1 error …
```
> test_text_generation: fix non-Gaudi2 case

- examples/text-generation/run_generation.py
> text-generation: improve output printing

- README.md
- docs/source/index.mdx
- examples/language-modeling/run_clm.py
- examples/text-generation/run_lm_eval.py
- optimum/habana/transformers/generation/utils.py
- optimum/habana/transformers/modeling_utils.py
- optimum/habana/transformers/models/__init__.py
- optimum/habana/transformers/models/baichuan/__init__.py
- optimum/habana/transformers/models/baichuan/configuration_baichuan.py
- optimum/habana/transformers/models/baichuan/generation_utils.py
- optimum/habana/transformers/models/baichuan/modeling_baichuan.py
- optimum/habana/transformers/models/baichuan/tokenization_baichuan.py
- optimum/habana/transformers/trainer.py
- tests/test_text_generation_example.py
This PR added the Baichuan2 model (a custom model), including Baichuan2-7B-Chat and Baichuan2-13B-Chat. [1][2]
[1] https://huggingface.co/baichuan-inc/Baichuan2-7B-Chat
[1] https://huggingface.co/baichuan-inc/Baichuan2-13B-Chat
> Add support for Baichuan2

- optimum/habana/transformers/generation/utils.py
fix failure in tests.test_peft_inference.
> fix tests.test_peft_inference failure

- optimum/habana/transformers/models/baichuan/tokenization_baichuan.py
The Sentencepiece library is required for running Baichuan. This import actually make the whole text-generation example fail if Sentencepiece is not installed.
This PR adds a check so that other models are not impacted.
> Fix bad import in Baichuan code

- examples/image-to-text/README.md
- tests/test_image_to_text_example.py
Seeing regression on 1.19 for llava model accuracy with fp8. 
Using scale mode to fix the issue. 
Updated readme and tests to use maxabs_quant_scale_format_const.json for llava models/ 
Current output:
11/26/2024 00:56:50 - INFO - _main_ - result = [[\{'generated_text': 'USER:  \nWhat is shown in this image? ASSISTANT:'}]]
11/26/2024 00:56:50 - INFO - _main_ - time = 160.23870641365647ms, Throughput (including tokenization) = -12.481378842618692 tokens/second
output after fix: 
11/26/2024 00:52:23 - INFO - {}main{} - result = [[
{'generated_text': 'USER:  \nWhat is shown in this image? ASSISTANT: The image shows a pier extending out over a body of water, with a mountain in the background.'}
]]
11/26/2024 00:52:23 - INFO - {}main{} - time = 160.74028802104294ms, Throughput …
> Fix for llava models not generating text with test failures in 1.19

- tests/baselines/albert_xxlarge_v1.json
- tests/test_examples.py
As internal CI running this model as torch.compile mode, following the same.
> Run albert-xxlarge-v1 CI as torch.compile mode

- examples/contrastive-image-text/README.md
- examples/question-answering/README.md
- examples/speech-recognition/README.md
- examples/text-classification/README.md
As PR https://github.com/huggingface/optimum-habana/pull/1514, updated model run commands which need to use --sdp_on_bf16 parameter.
> Update README commands for the models to use --sdp_on_bf16

- examples/text-generation/utils.py
This PR patches an example for `MiniCPM3` model enabled by #1342. Previously test command below would fail.
Test command: `GAUDI2_CI=1  RUN_SLOW=1 python3.10 -m pytest tests/test_text_generation_example.py -s -v -k MiniCPM 
`
> Minicpm patch

- optimum/habana/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py
fix import error in sdxl diffusers pipeline
> fix diffusers import

- examples/image-to-text/README.md
- examples/question-answering/README.md
- examples/speech-recognition/README.md
- examples/text-classification/README.md
- examples/text-generation/README.md
- tests/test_text_generation_example.py
> Update README commands for more models to use --sdp_on_bf16

- tests/baselines/llama_7b.json
> style: removed tabs

- examples/text-generation/requirements_lm_eval.txt
- examples/text-generation/run_lm_eval.py
> Revert PR #1473

- README.md
- docs/source/index.mdx
- examples/language-modeling/README.md
I verified baichuan2 training on Gaudi2, hence updated the corresponding documents.
> Update docs for baichuan2 training

- tests/baselines/bert_large_uncased_whole_word_masking.json
- tests/baselines/roberta_large.json
- tests/test_text_generation_example.py
> adjust bert and roberta targets

- examples/text-generation/README.md
> update text-gen readme for autogptq

- optimum/habana/transformers/models/gpt_neox/modeling_gpt_neox.py
- Correct the datatype during training used for rotary positional embedding calculation.
- Remove unused function
Note: The accuracy issue was identified to be caused by a previous pull request (#1148)
Note: This PR is re-opened instead of https://github.com/huggingface/optimum-habana/pull/1583
```sh
>>> GAUDI2_CI=1  RUN_SLOW=1 python3.10 -m pytest tests/test_examples.py -s -v  -k test_run_clm_gpt-neox-20b_deepspeed
_***** train metrics *****
epoch                       =         2.0
max_memory_allocated (GB)   =       94.48
memory_allocated (GB)       =       76.75
total_flos                  = 541209984GF
total_memory_available (GB) =       94.62
train_loss                  =       6.887
train_runtime               =  0:11:05.74
train_samples               =        2334 …
```
> Fix Accuracy Calculation Issue in GPT-NeoX

- examples/text-generation/README.md
> readme update for llama-405B

- tests/test_text_generation_example.py
The falcon-180b model in CI test fails with below device critical error:
```
/home/jenkins/workspace/cdsoftwarebuilder/create-binaries-from-sw-sources---bp-dt/repos/hcl/src/platform/gen2_arch_common/signals/manager.cpp::843(DFA): The condition [ false ] failed.  
/home/jenkins/workspace/cdsoftwarebuilder/create-binaries-from-sw-sources---bp-dt/repos/hcl/src/platform/gen2_arch_common/signals/manager.cpp::843(DFA): The condition [ false ] failed.  
/home/jenkins/workspace/cdsoftwarebuilder/create-binaries-from-sw-sources---bp-dt/repos/hcl/src/platform/gen2_arch_common/signals/manager.cpp::843(DFA): The condition [ false ] failed.  
/home/jenkins/workspace/cdsoftwarebuilder/create-binaries-from-sw-sources---bp-dt/repos/hcl/src/platform/gen2_arch_common/signals/manager.cpp::843(DFA): The …
```
> Add WA flag for falcon-180b to resolve text-gen critical reset error during tests

- tests/test_diffusers.py
- tests/test_examples.py
adjust CI tests to add sdp_on_bf16 flag corresponding to https://github.com/huggingface/optimum-habana/pull/1555
> add sdp_on_bf16 option to diffusers and image/audio classicifation tests

- tests/test_text_generation_example.py
If a developer only sets check_output to True like so:
```
("state-spaces/mamba-130m-hf", 1536, False, 5385.511100161605, True),
```
but forgets to update MODEL_OUTPUTS, they will see error
```
>       assert model_name in MODEL_OUTPUTS, f"Failed functional testing, missing expected output in MODEL_OUTPUTS for model {model_name}"
E       AssertionError: Failed functional testing, missing expected output in MODEL_OUTPUTS for model state-spaces/mamba-130m-hf
E       assert 'state-spaces/mamba-130m-hf' in {'Qwen/Qwen2-7B': 'DeepSpeed is a machine learning framework that provides a unified interface for training deep learning models. It is designed to be easy to use and to provide high performance. DeepSpeed is built on top of PyTorch and TensorFlow, and it supports a wide range of models, …
```
> Verify model output is provided when check_output is enabled

- examples/image-classification/requirements.txt
- examples/language-modeling/requirements.txt
- examples/protein-folding/requirements.txt
- examples/text-classification/requirements.txt
- examples/trl/requirements.txt
python3 ../gaudi_spawn.py --world_size 8 --use_mpi run_multitask_prompt_tuning.py \
--model_name_or_path google/flan-t5-base \
--do_train \
--report_to=none \
--num_train_epochs 3 \
--output_dir out_multi_peft \
--use_habana \
--use_lazy_mode \
--evaluation_strategy "steps" \
--eval_steps 500 \
--save_strategy "no" \
--learning_rate 1e-4  \
--per_device_train_batch_size 8 \
--per_device_eval_batch_size 8 \
--use_hpu_graphs_for_inference \
--use_hpu_graphs_for_training \
--bf16 \
crash like
[rank1]: Traceback (most recent call last):
[rank1]:   File "/yyoon/huggingface/optimum-habana/release/optimum-habana/examples/language-modeling/run_multitask_prompt_tuning.py", line 421, in <module>
[rank1]:     main()
[rank1]:   File "/yyoon/huggingface/optimum-habana/release/optimum-habana/examples/la …
> fix scikit-learn to 1.5.2 to fix f1 evaluation crash in 1.6.0

- examples/audio-classification/README.md
Readme command update for audio-classification
> update readme for audio-classification example

- tests/test_text_generation_example.py
> skip certain tests for G1 with empty param list

- examples/audio-classification/README.md
update audio-classification readme command for inference
> audio classification readme update

- examples/trl/README.md
PR from main (https://github.com/huggingface/optimum-habana/pull/1621)
> Fix run_generation test commands for TRL out usage example

- examples/text-generation/quantization_config/maxabs_quant_arbitrary.json
Port new scale file(arbitrary scale) from OHF.
> Add arbitrary scales (#15)

- examples/trl/README.md
Added to use SDPA to avoid OOM for Qwen2. 
> Modify Qwen2 TRL command to avoid OOM. 

- optimum/habana/diffusers/pipelines/pipeline_utils.py
Fixes saving lora weights for diffuser pipelines which do not support text_encoder_2 layers.
For example,
```
python examples/trl/ddpo.py \
--num_epochs=200 \
--train_gradient_accumulation_steps=1 \
--sample_num_steps=50 \
--sample_batch_size=6 \
--train_batch_size=3 \
--sample_num_batches_per_epoch=4 \
--per_prompt_stat_tracking=True \
--per_prompt_stat_tracking_buffer_size=32 \
--train_learning_rate=1e-05 \
--tracker_project_name="stable_diffusion_training" \
--log_with="tensorboard" \
--use_habana \
--bf16 \
--hf_hub_model_id="ddpo-finetuned-stable-diffusion" \
--push_to_hub False
```
File "/root/tf/optimum-habana-new/examples/trl/ddpo.py", line 245, in <module>
trainer.train()
File "/usr/local/lib/python3.10/dist-packages/trl/trainer/ddpo_trainer.py", line 604, in …
> Update save lora weights for diffusers with text_encoder_2 layers

- examples/stable-diffusion/text_to_image_generation.py
Quick WA fix for issue mentioned in PR #1631
> Quick fix for quantization/custom op list loading

- optimum/habana/sentence_transformers/st_gaudi_trainer.py
This PR will solve the issue from the running of ST trainer over multiple HPU cards as shown in the readme file as 
https://github.com/huggingface/optimum-habana/tree/main/examples/sentence-transformers-training/nli
the command as
HABANA_VISIBLE_MODULES="2,3" python ../../gaudi_spawn.py --use_deepspeed --world_size 2 training_nli.py bert-base-uncased
Error happened as below
Now it is solved and no error with multiple HPU cards for ST trainer and verified. 
Thanks. 
> Fix distributed issue for ST Trainer

- examples/multi-node-training/GaudiNIC/Dockerfile
Update docker and deepspeed version
> Update multi-node test dockerfile

- examples/stable-diffusion/README.md
- examples/text-generation/run_lm_eval.py
- examples/text-generation/utils.py
- optimum/habana/transformers/modeling_utils.py
- optimum/habana/transformers/models/__init__.py
- optimum/habana/transformers/models/llama/modeling_llama.py
- optimum/habana/transformers/models/mixtral/__init__.py
- optimum/habana/transformers/models/mixtral/modeling_mixtral.py
- tests/test_text_generation_example.py
This PR includes the following changes
1. add ouput json to log file
2. change stable diffusin readme
3. make style fixes
> Fixes on OH 1.15 pre release

- examples/multi-node-training/EFA/Dockerfile
> Update EFA dockerfile to SynapseAI 1.19.0

- examples/language-modeling/llama3_ds_zero1_config.json
Change-Id: Ide19261f0830ba32e6d3ddf1ec662bfc097ff4ba
> Adding Deepspeed zero1 config

- tests/baselines/Llama_3_2_11B_Vision_Instruct.json
- tests/baselines/falcon_40b.json
- tests/baselines/gpt_neox_20b.json
- tests/utils.py
Remove some old model CI tests for training, and also reduce the training epochs for some models to 1 to reduce total test time.
> Update training pytests to reduce total time

- tests/test_text_generation_example.py
Added Unit test for Gemma2-27b model for Gaudi2.
> Added Unit Test for Gemma-2-27b model

- optimum/habana/accelerate/accelerator.py
- optimum/habana/accelerate/state.py
- optimum/habana/accelerate/utils/transformer_engine.py
- optimum/habana/transformers/training_args.py
* Enabling minimize memory for zero3 runs
* Adding minimize_memory flag to args
* Changing help message
> Enabling minimize memory for zero3 runs (#67)

- .github/workflows/slow_tests_gaudi2.yml
- tests/ci/slow_tests_diffusers.sh
- tests/test_diffusers.py
Adding support for running gated models in diffusers CI
> Add gated models to diffusers CI tests

- tests/transformers/tests/models/falcon/test_modeling_falcon.py
- tests/transformers/tests/models/gpt_neox/test_modeling_gpt_neox.py
- tests/transformers/tests/models/gptj/test_modeling_gptj.py
I made the upstream changes in 
https://github.com/huggingface/transformers/pull/34858
https://github.com/huggingface/transformers/pull/35358/files 
> fixes for v4.48 pytest

- tests/transformers/tests/models/falcon/test_modeling_falcon.py
- tests/transformers/tests/models/gpt_neox/test_modeling_gpt_neox.py
Fixes some CI issues after applying upstream changes: https://github.com/huggingface/transformers/pull/35235 
> fea(): Applied changes in HF #35235

- examples/text-generation/quantization_config/pow2_quant.json
- examples/text-generation/quantization_config/weight_opt_quant.json
Adding new quant config files for new scenarios - scale methods
> Added quant config files for new scenarios

- examples/language-modeling/README.md
> Removing HL_DS_DISTRIBUTED_ATTENTION_SEQ_DIM as it's not needed from 1.20

- optimum/habana/transformers/models/t5/modeling_t5.py
FLAN-T5 doesn't work with regional compilation using module.compile.
> [SW_212175] FLAN-T5 has bad performance when using regional compilation

- examples/sentence-transformers-training/sts/README.md
- examples/sentence-transformers-training/sts/requirements.txt
This PR adds the requirements to run the examples in the README of sentence transformers training STS.
> Add requirements.txt to sentence transformer training sts

- Makefile
- examples/text-generation/README.md
- examples/text-generation/requirements_awq.txt
- optimum/habana/transformers/integrations/awq.py
pip install autoawq downgrades transformers to 4.47. so added transformers>=4.48.2 too
> Fix the issue with --load_quantized_model_with_autoawq

- optimum/habana/transformers/models/llama/modeling_llama.py
> Fix llama attr

- examples/sentence-transformers-training/nli/README.md
- examples/sentence-transformers-training/nli/requirements.txt
> Add requirements.txt to sentence transformers nli example

- examples/text-generation/utils.py
Assert if user has not set 'PT_HPU_LAZY_MODE=0' on command line while using --use_torch_compile
> UX code change

- Makefile
- examples/text-generation/README.md
- examples/text-generation/requirements_awq.txt
to merge https://github.com/huggingface/optimum-habana/pull/1747 to main branch
> fix dependency issue with --load_quantized_model_with_autoawq

- optimum/habana/transformers/models/llama/modeling_llama.py
Use super class self.scaling for scale.
> update llama scaling

- optimum/habana/transformers/trainer.py
Fixes loss calculation when gradient accumulation is on.
The fix is a work around and will be fixed (by regiss) in a future update based on changes in transformers.
- [n ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [n ] Did you make sure to update the documentation with your changes?
- [n ] Did you write any new necessary tests?
> Fix loss calculation (Workaround), final fix TBD

- examples/text-generation/README.md
> Simplify text-gen readme

- tests/test_examples.py
Related to https://github.com/huggingface/optimum-habana/pull/1757
Adds --attn_implementation sdpa to wav2vec slow tests.
> Add --attn_implementation to wav2vec2 slow tests

- examples/text-to-speech/requirements.txt
missing dependency requirements : sentencepiece
> add sentencepiece to the requirements

- examples/stable-diffusion/text_to_image_generation.py
> Fix LoRA weights loading in text-to-image generation sample script

- examples/text-generation/README.md
- examples/text-generation/run_generation.py
Add trust_remote_code flag support.
> Add trust_remote_code

- examples/audio-classification/README.md
- examples/text-generation/README.md
adding exp flags for certain models acc issues and regressions
> exp flags for acc issues

- examples/text-generation/README.md
Updated README:
added `DEEPSPEED_USE_HABANA_FRAMEWORKS_DETERMINISTIC_API=true` for Llama3-405B
related to this change: https://github.com/huggingface/optimum-habana/pull/1745
> v1.16 Llama3-405B text-generation. Added DEEPSPEED_USE_HABANA_FRAMEWORKS_DETERMINISTIC_API flag.

- examples/question-answering/run_qa.py
- optimum/habana/accelerate/accelerator.py
port https://github.com/huggingface/optimum-habana/pull/1801 to v1.16-release branch
> Move model to device before wrapping with FSDP

- tests/baselines/llama_7b.json
> Update warmup ratio for adalora

- optimum/habana/transformers/modeling_utils.py
- optimum/habana/transformers/models/modeling_all_models.py
Remove default eager attention in wav2vec.
> Fix for attention selection in wav2vec2

- examples/text-generation/requirements_lm_eval.txt
- examples/text-generation/run_lm_eval.py
This reverts commit 5fb6c0ac368ac4d0fe69c316b45017d80ea1922a.
> Revert "Lm eval upgraded to 0.4.7 (#1692)"

- examples/summarization/run_summarization.py
When running with deepspeed, summarizaion/run_summarization.py example failed due to a race condition when downloading nltk punkt tokenizer.
> Fix race condition when downloading nltk tokenizer

- tests/baselines/fixture/tests/test_examples.json
> test_examples: add missing clip-roberta baseline

- optimum/habana/transformers/models/gpt_neox/modeling_gpt_neox.py
Fixes # (issue) : https://github.com/huggingface/transformers/issues/35838
https://github.com/huggingface/transformers/issues/36074
Reproducing with gpt_neox model :
pytest tests/test_examples.py::DeepspeedCausalLanguageModelingExampleTester::test_run_clm_gpt-neox-20b_deepspeed
> Fix unexpected 'num_items_in_batch' argument in GPT-NeoX forward

- tests/baselines/fixture/tests/test_sentence_transformers.json
- tests/test_sentence_transformers.py
This PR will update the measurement methodology of sentence transformer using the average for measure to improve the validation stability and also update some Ref number in test_senetence_transformer.json with this method. Tested with Gaudi nodes it passed. Thanks.
> Update Sentence Transformer CI/Ref

- examples/text-generation/README.md
- optimum/habana/transformers/models/llama/modeling_llama.py
- tests/baselines/fixture/tests/test_text_generation_example.json
- tests/test_text_generation_example.py
fix merge typo
lower batch size of distributed tp example
matches CI test params with readme for distributed tp example
> fix typo in modeling llama

- tests/transformers/tests/models/mistral/test_modeling_mistral.py
- tests/transformers/tests/models/mixtral/test_modeling_mixtral.py
Updated the skipped tests from the RD side as of 03/18/2025. 
have ran the following tests, and they all behave as expected. 
```
RUN_SLOW=true python -m pytest --device gaudi2 tests/transformers/tests/models/mistral -s -v
RUN_SLOW=true python -m pytest --device gaudi2 tests/transformers/tests/models/mixtral -s -v
```
> fea(): Added the updated skip list for mistral/mixtral tests

- tests/baselines/fixture/tests/test_examples.json
Fix regression for test_run_image2text_lora_finetune_idefics2-8b_multi_card
> Fix regression for test_run_image2text_lora_finetune_idefics2-8b_multi_card

- .github/workflows/build_pr_documentation.yml
The `ubuntu-20.04` workflow image is going to be deprecated, switch to `ubuntu-22.04`.
> Update PR doc build workflow

- optimum/habana/transformers/models/t5/modeling_t5.py
Fix the training issue with an unexpected keyword argument 'num_items_in_batch'
> Fix the flant5-xl training issue 

- optimum/habana/transformers/models/qwen2_vl/modeling_qwen2_vl.py
> Add G3 perf WA for Qwen2VL

- optimum/habana/transformers/models/mpt/modeling_mpt.py
Remove softmax wrapping class to fix MPT inference regression.
> Fix MPT regression

- optimum/habana/accelerate/accelerator.py
Change-Id: I8cd89a0f2e58e94582c603f3d936a6d013c7c125
we also need to compile the leaf modules when regional compilation is enabled.
> fix lost modules in regional compilation

- optimum/habana/transformers/models/qwen2/modeling_qwen2.py
Followed modeling_llama.py, integrating Deepseed's DistributedAttention to support Context Parallelism
This PR adds support to enable Context Parallelism for Qwen2 models using deepspeed.
This feature can be enabled by using context_parallel_size flag.
verified with Qwen2-7B-Instruct for finetuning for 32K seq length on 8 ranks using this feature.
commandline:
python3 ../gaudi_spawn.py   --world_size 8 --use_deepspeed run_lora_clm.py --dataset_name tatsu-lab/alpaca --bf16 True --dataset_concatenation --max_seq_len 32768 --validation_split_percentage 4 --save_strategy no --warmup_ratio 0.03 --lr_scheduler_type \"constant\" --logging_steps 10 --do_train --use_habana --throughput_warmup_steps 3 --use_flash_attention True --flash_attention_causal_mask True --num_train_epochs 8 --lora_alpha 16 …
> Integrate DistributedAttention for Qwen2

- optimum/habana/transformers/models/llama/modeling_llama.py
DeepSpeed module doesn't handle keyword arguments and throws a RuntimeError when OH calls it with kwargs. This is a workaround for this issue in Llama.
> Workaround for DS issue in Llama

- examples/text-generation/requirements_lm_eval.txt
- examples/text-generation/run_lm_eval.py
Based on original PR: https://github.com/huggingface/optimum-habana/pull/1692 by @12010486 
This PR fixes accuracy issues found in R&D test infrastructure
> Upgrade LM Eval to 0.4.7

- examples/language-modeling/llama3_ds_zero3_4k.json
* Adding Deepspeed config for Llama3 Fine Tuning
* Addressing review comments
Parameter count of Llama 3 70B nodes.
input_layernorm.weight: (8192)
mlp.down_proj.weight: (8192 * 28672 = 234881024)
mlp.gate_proj.weight: (28672 * 8192 = 234881024)
mlp.up_proj.weight: (28672 * 8192 = 234881024)
post_attention_layernorm.weight: (8192)
self_attn.k_proj.weight: (1024 * 8192 = 8388608)
self_attn.o_proj.weight: (8192 * 8192 = 67108864)
self_attn.q_proj.weight: (8192 * 8192 = 67108864)
self_attn.v_proj.weight: (1024 * 8192 = 8388608)
Total = 855,638016 (234881024 + 234881024 + 234881024 + 8388608 + 67108864 + 67108864 + 8388608)
In Deepspeed, params less than 10000 are not sharded by default.
Hence, if we count remaining nodes, parameter size will be 855,638016 and that is exactly what we have to …
> Adding Deepspeed config for Llama3 Fine Tuning (#165)

- optimum/habana/transformers/models/deepseek_v3/modeling_deepseek_v3.py
trim_logits support in deepseekV3 OH
> Add trim_logits support in deepseekV3 (#180)

- tests/test_bnb_inference.py
- tests/test_bnb_qlora.py
1) Enable QLoRA tests with torch.compile mode
2) Set PT_HPU_LAZY_MODE=0 in script (for torch.compile mode)
> [SW-221482] Enable QLoRA tests with torch.compile mode

- optimum/habana/accelerate/accelerator.py
- optimum/habana/transformers/trainer.py
- optimum/habana/transformers/training_args.py
Add code required to enable compiled_autograd using "use_compiled_autograd" (in training args) when using deepspeed (for training).
> Add flag to enable compiled_autograd with Deepspeed for training (#147)

- optimum/habana/diffusers/pipelines/controlnet/pipeline_controlnet.py
- optimum/habana/diffusers/pipelines/flux/pipeline_flux.py
- optimum/habana/diffusers/pipelines/stable_diffusion_3/pipeline_stable_diffusion_3.py
- setup.py
- tests/test_diffusers.py
This PR is a mirror of #1877  for the `main` branch. 
the same tests apply. 
--
Co-authored-by: Daniel Socek daniel.socek@intel.com
> fea(diffusers): Upgraded to version 0.32.0 (mirror of #1877)

- examples/speech-recognition/README.md
- examples/text-generation/README.md
Running on a bare (aka no data) Intel Tiber Cloud G2 machine, I have encountered running to this generic error  for following tests:
```
Please pass the argument `trust_remote_code=True` to allow custom code to be run.
```
- speech-recognition example using `librispeech_asr` dataset
- text-gen examples with `run_lm_eval.py` using `hellaswag` dataset
for each, the proper `--trust_remote_code` arg is added: 
- `run_speech_recognition_ctc.py` [here](https://github.com/huggingface/optimum-habana/blob/d63807415216d673adb0dd7981d5db3659a3666f/tests/configs/examples/wav2vec2_large_lv60.json#L27)
- `run_eval_lm.py` [here](https://github.com/huggingface/optimum-habana/blob/v1.17.0/examples/text-generation/run_lm_eval.py#L248)
which seems to be resolving the issue. 
@libinta  @sidgog  FYI. 
Fixes # …
> fea(): ReadMe remote_trust fixes

- examples/sentence-transformers-training/nli/requirements.txt
- examples/sentence-transformers-training/paraphrases/requirements.txt
- examples/sentence-transformers-training/sts/requirements.txt
- examples/speech-recognition/requirements.txt
> Update datasets requirement in examples

- examples/text-generation/requirements.txt
- examples/text-generation/requirements_lm_eval.txt
Adding sentencepiece package to requirements that is required for vicuna models
```
python3 run_generation.py --model_name_or_path lmsys/vicuna-13b-v1.1 --batch_size 1 --max_new_tokens 100 --use_hpu_graphs --use_kv_cache --num_return_sequences 1 --temperature 0 --prompt "Alice and Bob" --sdp_on_bf16
```
> Add sentencepiece to requirements to support vicuna text generation

- examples/stable-diffusion/training/README.md
Updating a missing `--sdp_on_bf16` for textual inversion with 2.5+PT. 
| Tests | Perf. on 1x G2  |
|:------------------|:--------------|
| example as is      | `Throughput = 2.147452363662043 samples/s`      |  
| example with `--sdp_on_bf16` |  `Throughput = 2.347851652688481 samples/s`      |  
> fea(): Added the --sdp_on_bf16 to textual inversion example

- Makefile
> Update makefile for explicit lazy mode

- optimum/habana/transformers/training_args.py
> Fix deepspeed zero3

- examples/language-modeling/README.md
- tests/baselines/fixture/tests/test_fp8_examples.json
- tests/test_fp8_examples.py
> README changes for Llama3.1 8B Finetuning with LoRA

- examples/text-generation/quantization_tools/pt2e.py
- examples/text-generation/run_generation.py
- examples/text-generation/run_lm_eval.py
- examples/text-generation/utils.py
- pt2e quant changes in the main script with separate calibration and inference flow.
- common argument --pt2e_quant_dtype, options int8, fp8_143 (Default), fp8_152
calibrate + save args --pt2e_save --pt2e_path <path>
load + infer args --pt2e_path <path>
> pt2e quant changes into the main script (#191)

- .github/workflows/slow_tests_gaudi3.yml
Following #1953, Sentence Transformers slow tests don't work anymore. This PR fixes it.
> Fix sentence-transformers CI with new runners

- examples/text-generation/run_generation.py
This PR corrects the calculation of the e2e latency that was previously implemented incorrectly. The fix ensures accurate reporting of latency metrics for e2e. 
This addresses the issue discussed in #1952
> fix wrong calculation of e2e latency

- tests/baselines/fixture/tests/test_text_generation_example.json
Aligned test outputs with latest expected results
Reference: huggingface/optimum-habana#1839
```sh
>>> PT_HPU_LAZY_MODE=1 RUN_SLOW=true python -m pytest tests/test_text_generation_example.py -s -v -k test_text_generation_bf16_1x[mistralai/Mixtral-8x7B-v0.1-1-False-True]
```
the test will pass on both G2 and G3
> Update test baseline for mistralai/Mixtral-8x7B-v0.1

- examples/text-generation/README.md
Adds additional information about the usage and tests conducted for the attention batch split flag
> Add additional info about attn batch split flag

- examples/text-generation/README.md
- examples/text-generation/experimental/utils.py
- examples/text-generation/quantization_tools/pt2e.py
- examples/text-generation/requirements_lm_eval.txt
- examples/text-generation/run_generation.py
- examples/text-generation/run_lm_eval.py
- examples/text-generation/utils.py
- examples/trl/ppo.py
- optimum/habana/environment.py
- optimum/habana/feature_detection_utils.py
- optimum/habana/features.py
- optimum/habana/transformers/generation/utils.py
- optimum/habana/transformers/modeling_attn_mask_utils.py
- optimum/habana/transformers/models/llama/modeling_llama.py
- optimum/habana/transformers/models/mllama/modeling_mllama.py
- tests/test_bnb_inference.py
- tests/test_bnb_qlora.py
- tests/test_features.py
> This is diff between optimum-habana-fork and optimum-habana

- README.md
> Testing remote CI, please do not merge

- README.md
> Testing internal CI

- setup.py
> Pin latest optimum to force mutual updates

- .github/workflows/slow_tests_gaudi3.yml
- Makefile
> Add token to single card tests CI

- conftest.py
- tests/baselines/fixture/tests/test_bnb_inference.json
- tests/baselines/fixture/tests/test_bnb_qlora.json
- tests/test_bnb_inference.py
- tests/test_bnb_qlora.py
1) Configure qlora tests with additional arguments
2) Enable torch.compile mode
3) Install bitsandbytes from the main branch
> Configure qlora tests with additional arguments

- tests/baselines/fixture/tests/test_bnb_qlora.json
- tests/test_bnb_qlora.py
- tests/test_text_generation_example.py
1) Support for Llama3.1-70B finetuning with QLoRA & PT2.8.0
2) Enable regional compilation for Llama3.1 fine-tuning and inference
> 70B finetuning with QLoRA

- optimum/habana/transformers/models/deepseek_v3/configuration_deepseek_v3.py
This pull request introduces a small but impactful change to the `DeepSeekV3` model configuration in `configuration_deepseek_v3.py`. The change allows the number of hidden layers to be dynamically configured using an environment variable, enhancing flexibility for different deployment scenarios.
Dynamic configuration enhancement:
* [`optimum/habana/transformers/models/deepseek_v3/configuration_deepseek_v3.py`](diffhunk://#diff-50391d1745f520956d95aff40d1ade2b938b5aea11d03bef5e53481d8a68ff0dR5-R6): Added the `os` module import to support reading environment variables.
* [`optimum/habana/transformers/models/deepseek_v3/configuration_deepseek_v3.py`](diffhunk://#diff-50391d1745f520956d95aff40d1ade2b938b5aea11d03bef5e53481d8a68ff0dL174-R176): Modified the `num_hidden_layers` attribute in the …
> Extra Content: add support for reduced model

- optimum/habana/transformers/trainer.py
Noticed in today's nightly CI run https://github.com/huggingface/optimum-habana/actions/runs/15544633027/job/43768185586
There's something wrong in model preparation / unwrapping in the case of fsdp+torch.compile
I tried following the changes in https://github.com/huggingface/transformers/pull/37725 but they were not enough so I hot fixed it by unwrapping the model during saving.
> Hot fix compiled fsdp model saving failure

- examples/speech-recognition/README.md
Additional fixes to the README commands
> Unify --chars_to_ignore in speech recognition examples

- optimum/habana/transformers/trainer.py
This pull request refines the `Trainer` class in `optimum/habana/transformers/trainer.py` to improve compatibility with PyTorch's `torch.compile` feature and address issues with model wrapping and unwrapping in specific scenarios. The most important changes are focused on ensuring proper handling of `OptimizedModule` instances, adding the `keep_torch_compile` parameter for unwrapping models, and improving conditional logic in the evaluation loop.
* Modified `_wrap_model` to include the `keep_torch_compile=False` parameter when unwrapping models, ensuring compatibility with `torch.compile`. (`[optimum/habana/transformers/trainer.pyL461-R461](diffhunk://#diff-ea95ad7b4deeb797c4c72182ea73bedb0efc6e774f362d58e92f9272d05e63baL461-R461)`)
* Updated `_save` to use `keep_torch_compile=False` when …
> Hot fix compiled fsdp model saving failure (#2028)

- optimum/habana/transformers/models/llama/modeling_llama.py
(cherry picked from commit b4fe45731a6441260f73a5889a863a205b40268e)
> Fix passing return_dict to pre_attn() in Llama (#2102)

- examples/pytorch-image-models/README.md
- examples/pytorch-image-models/requirements.txt
This PR fixes/updates the timm readme file:
- package `timm` is installed via the clone step, so no need to duplicate it in the requirment.txt. 
- All changes are tested on both G2/G3 1x/8x. 
> fea(timm): Updated/Fixed the readme

- examples/text-generation/model_adapter.py
- examples/text-generation/run_lm_eval.py
This commit is a mirror of PR #2170, applied on top of v1.19-release branch. It was created anew instead of cherry-picking due to misaligned history between main and v1.19-release branches.
> Extract model adapter class from run_lm_eval.py to a new script file.

- optimum/habana/transformers/trainer.py
Small change that increases expression readability, fixes potential vulnerability and is reportedly a bit faster.
> Remove potential weakness reported by static code analysis -- CWE 569 -- in transformers/trainer.py

- docs/source/_toctree.yml
- docs/source/usage_guides/safe_softmax.mdx
Add markdown article explaining HPU-optimized safe_softmax benchmarking
Created a detailed markdown article comparing HPU-optimized safe_softmax with native PyTorch safe_softmax.
Included step-by-step explanation of the benchmarking script.
Added context about safe_softmax, its purpose, and use cases.
Clarified that safe_softmax works out-of-the-box without requiring special setup.
> Safe_softmax demonstration (#263)

- examples/text-generation/run_generation.py
This PR allows using preexisting data sources for prompt creation. It isn't caching the data source as it's downloading it, because that happens in multiple processes in parallel, with separate files for each `pid`, but it allows user to present their own cached version of the file, and skip the download altogether.
> Allow usage of cached books from project Guttenberg.

- examples/text-generation/run_lm_eval.py
Add system_instruction for lm_eval in OH that helps to boost accuracy for mmlu tasks
> Add system_instruction support for lm_eval in OH

- optimum/habana/transformers/models/mixtral/modeling_mixtral.py
This PR addresses an issue where Intel Neural Compressor (INC) could not correctly apply FP8 quantization to the `GaudiMixtralSparseMoeBlock` module.
The problem was that the `hpu.mixture_of_experts` call was directly embedded within the forward method, making it difficult for INC to patch and replace for its quantization workflow.
- Extracted the custom op call logic into a new method, `call_dynamic_moe_op`.
- Modified the forward method to call this new function.
This change allows INC to successfully patch the `call_dynamic_moe_op` method, enabling correct FP8 quantization of the `GaudiMixtralSparseMoeBlock` layer.
Previously,
```sh
>>> TQDM_DISABLE=1 PT_HPU_LAZY_MODE=1 QUANT_CONFIG=/root/optimum-habana/examples/text-generation/quantization_config/maxabs_measure.json  python3 …
```
> Fix: INC FP8 quantization compatibility

- examples/text-generation/README.md
Changes to Readme.md to go along with system instructions for lm_eval
> Readme to go along with system instructions for lm_eval

- README.md
- docs/source/index.mdx
- examples/image-to-text/run_pipeline.py
- optimum/habana/transformers/generation/utils.py
- optimum/habana/transformers/modeling_utils.py
- optimum/habana/transformers/models/__init__.py
- optimum/habana/transformers/models/qwen2_5_vl/__init__.py
- optimum/habana/transformers/models/qwen2_5_vl/modeling_qwen2_5_vl.py
- tests/baselines/fixture/tests/test_image_to_text_example.json
- tests/test_image_to_text_example.py
Enable qwen2.5-vl model with gaudi-specific optimizations.
> Add Qwen2.5-VL
