.github/workflows/fast_tests.yml, .github/workflows/slow_tests.yml, Makefile, tests/ci/example_diff_tests.sh, tests/ci/slow_tests_1x.sh, tests/ci/slow_tests_8x.sh, tests/test_examples.py, tests/utils.py
This PR modifies CI/CD:
- ALBERT XXL 8x is now added to non-regression tests. 1x version is still filtered because it takes 6 hours, which is the maximum time a job can run in a Github workflow (so there is a risk that the job is interrupted right before the end).
- There is a better separation between 1x, 8x and example diff tests. Each kind of test now has its own command in the Makefile.
- Add *concurrency* to all workflows to manage computation resources better:
- if a fast test is run in a PR while there is already one running (from the same PR), the former one will be cancelled
- if a slow test is run while there is already one running, the most recent one will be queued
=> Add Albert XXL 8x and concurrency to CI/CD

examples/question-answering/README.md, examples/text-classification/README.md, optimum/habana/trainer.py, optimum/habana/trainer_utils.py, optimum/habana/training_args.py, tests/test_examples.py
This PR adds a new argument `throughput_warmup_steps` that enables to remove warmup steps from the throughput calculation at the end of the training (in lazy mode for instance).
This requires to override the `speed_metrics` method in `trainer_utils.py`.
Examples and tests have been updated accordingly.
=> Add a new argument for taking warmup steps into account in throughput calculation

examples/question-answering/run_qa.py, examples/question-answering/utils_qa.py, examples/text-classification/run_glue.py, optimum/habana/trainer.py, optimum/habana/training_args.py, optimum/habana/version.py, setup.py, tests/test_trainer.py
Make the repo up to date with Transformers 4.19.1.
=> Update the repo with changes brought by Transformers 4.19.1

README.md, optimum/habana/trainer.py, setup.py
The user does not have to instantiate a GaudiConfig object anymore, it will be done automatically based on the value of `gaudi_config_name` in the training arguments if no Gaudi configuration is given to the trainer.
The `huggingface_hub` dependency is also removed since it is now managed by Optimum.
=> Enable GaudiConfig instantiation from inside the trainer

tests/test_examples.py
This PR fixes an issue in the CI regression script. Some key names of the regression metrics dictionary were wrong and are corrected.
=> Fix key names in CI regression metrics dictionary

setup.py
This PR fixes an issue where cached objects used in the `map` method of the dataset lead to wrong results. This is linked to the version of `dill`. This is a temporary fix that should be removed when this [issue](https://github.com/huggingface/datasets/issues/4506) is solved.
=> Fix an issue with dill>=0.5.3

.github/workflows/slow_tests.yml, tests/test_examples.py
This PR enables to execute CI slow tests on a us-west-2 AWS instance. Issues with T5 happened in us-east-1 (which may be related to the lack of availability of DL1 instances in us-east-1). Enables T5 slow test again.
=> Move CI slow tests to AWS us-west-2 to be able to run T5

optimum/habana/modeling_utils.py, optimum/habana/trainer.py
ALBERT does not rely on the `get_extended_attention_mask` method so it needs its own fix for disabling HMP when computing `extended_attention_mask = (1.0 - extended_attention_mask) * torch.finfo(self.dtype).min`.
=> Fix bug with HMP for ALBERT

.github/workflows/build_pr_documentation.yml, Makefile
The environment variable `COMMIT_SHA` collides with the one of Optimum when building the documentation of Optimum. Indeed, in that case, the variable `COMMIT_SHA` for generating the doc of Optimum Habana is supposed to be empty but it will actually be equal to the variable `COMMIT_SHA` defined in the PR documentation workflow, leading to an error because this commit exists in Optimum but not in Optimum Habana.
=> Fix variable name in make doc

optimum/habana/trainer.py, optimum/habana/training_args.py
This PR adds a check to make sure `torch.distributed` is not initialized twice.
It also adds some flexibility to Torch DDP to specify with training arguments:
- `find_unused_parameters`, which should be `True` for pretraining (default is `False`),
- `ddp_bucket_cap_mb`, default is 230.
=> Check if torch.distributed was already initialized in distributed mode

tests/baselines/bert_base_uncased.json
There is quite a lot of variance on the training time of `bert-base-uncased` fine-tuned on MRPC in distributed mode. This PR adjusts the corresponding baseline training time.
=> Update CI baseline (TTT) for BERT base MRPC 8x

Makefile
This PR adds a `make clean` to delete log files and folders generated by Gaudi during each run, such as `.graph_dumps/` or `habana_log.livealloc.log_*`.
=> Add make clean to delete log files/folders generated by runs on Gaudi

.github/workflows/fast_tests.yml, .github/workflows/slow_tests.yml, Makefile, tests/baselines/bert_base_uncased.json, tests/baselines/bert_large_uncased_whole_word_masking.json, tests/baselines/distilbert_base_uncased.json, tests/baselines/roberta_base.json, tests/baselines/vit_base_patch16_224_in21k.json, tests/ci/albert_xxl_1x.sh, tests/ci/example_diff_tests.sh, tests/ci/fast_tests.sh, tests/ci/slow_tests_1x.sh, tests/ci/slow_tests_8x.sh, tests/example_diff/run_image_classification.txt, tests/test_examples.py
Move the CI regression tests to on-prem Gaudi.
Fast (unit and integration) tests run for each commit and PR are still run on AWS instances to avoid collision with other fast tests or runs triggered by users. Since all those cannot be planned beforehand, it is better to run them on different AWS instances.
This PR also modifies the following:
- All the slow tests are now performed, whether one of these tests failed or not. Tests following a failed test used to be skipped.
- Update some CI baselines.
- Add a diff file for the `run_image_classification.py` example. It should have been added in #80.
=> Run CI regression tests on on-prem Gaudi

Makefile, docs/source/index.mdx
We would like to have a default clone URL to use when building the main documentation of Optimum. This is needed because in that case we cannot retrieve the clone URL from any PR properties.
=> Add default clone URL to Makefile

optimum/habana/__init__.py, optimum/habana/generation_utils.py, optimum/habana/modeling_utils.py, optimum/habana/models/__init__.py, optimum/habana/models/albert/__init__.py, optimum/habana/models/albert/modeling_albert.py, optimum/habana/models/modeling_all_models.py, optimum/habana/trainer.py
Some forward methods (e.g. for ViT and ALBERT) and generation methods are tweaked so that they are optimized for running on Gaudi. The replacement logic with their Transformers' counterparts is currently done in the Trainer. This PR moves this logic in `modeling_utils.py` so that only one call is needed in the Trainer.
The way these methods are replaced is not the most elegant one, but it will be much easier to maintain and will profit all models from Transformers (not only the one we validated). For instance, before this PR, only GPT2 and T5 benefit from the optimized generation methods. With this PR, all the models that have a `generate` method will benefit from them.
=> Refactor how optimized methods for Gaudi replace their counterparts in Transformers

optimum/habana/trainer.py
Loading the best model at the end of training with `--load_best_model_at_end` fails with the current version of Habana DeepSpeed (0.6.1, see https://github.com/huggingface/transformers/issues/17114).
This PR brings a temporary workaround where the best model at the end of training is loaded as a regular PyTorch model and not as a DeepSpeed engine. This should not be an issue since the best model is loaded for inference only and ZeRO-3 has not been validated yet (see [here](https://docs.habana.ai/en/v1.6.0/PyTorch/DeepSpeed/DeepSpeed_User_Guide.html#deepspeed-validated-configurations)) while ZeRO-1/2 are useful for training only.
=> Temporary workaround for loading best model at end with DeepSpeed

tests/test_examples.py
This PR reorder regression tests so that the multi-card summarization test with T5 is placed at the end. This may help when running CI on AWS instances because this test sometimes silently fails (only on AWS instances) and the reason is still unclear.
=> Reorder regression tests

.github/workflows/slow_tests.yml
CI workflows' jobs currently use `if: ${{ always() }}` so that all jobs are always executed (even if previous jobs failed). However, with this conditional statement, jobs are not cancellable (see [here](https://docs.github.com/en/actions/managing-workflow-runs/canceling-a-workflow#steps-github-takes-to-cancel-a-workflow-run)). This is annoying when the self-hosted runner cannot be found (for example because it could not be created when no DL1 instance is available on AWS) because in that case the job can spend days looking for the runner (see [here](https://stackoverflow.com/questions/70959954/error-waiting-for-a-runner-to-pick-up-this-job-using-github-actions)) while it can not be manually cancelled. This issue has been discussed …
=> Replace always() in CI workflows

.github/workflows/slow_tests.yml
The AMI ID for the CI workflow running regression tests was wrong, leading to insufficient memory for the running instance. This PR fixes this.
=> Fix wrong AMI ID in CI workflow

docs/source/tutorials/pretraining.mdx, examples/language-modeling/README.md, examples/language-modeling/run_mlm.py, examples/question-answering/run_qa.py, examples/question-answering/trainer_qa.py, optimum/habana/trainer.py, optimum/habana/training_args.py, tests/baselines/roberta_base.json, tests/baselines/roberta_large.json
This PR adds `model_tie_weights()` in the `__init__` method of the `GaudiTrainer` class so that there is no unused parameters in BERT/RoBERTa/ALBERT. `ddp_find_unused_parameters` had to be used before and it was not compatible with gradient checkpointing.
=> Fix gradient checkpointing for BERT/RoBERTa/ALBERT

optimum/habana/trainer.py, optimum/habana/training_args.py
This PR enables to set `ddp_find_unused_parameters` to `False` by default and set it to `True` in the `GaudiTrainer` only when the argument is explicitly passed with this value.
This was already done that way before https://github.com/huggingface/optimum-habana/pull/118, and we revert back to it because DDP's `find_unused_parameters` makes runs slower and it should not be necessary for models from the Transformers library.
=> Do not use DDP find_unused_parameters unless explicitly required

.github/workflows/slow_tests.yml
The starting time of daily regression tests was changed in #120 but the ALBERT XXL 1x test is still triggered when the previous schedule is different. This PR fixes it.
=> Fix CI schedule for ALBERT XXL 1x

.github/workflows/check_code_quality.yml, setup.py, tests/test_examples.py
This PR enables to display all the measured and reference metrics when one regression test fails in CI. This is useful because if one test fails, then the following regression tests will not be performed and not all regressing metrics will be displayed.
=> Add additional message when a regression test fails in CI

optimum/habana/transformers/deepspeed.py
The env variable `USE_DEEPSPEED_HPU` is set to `"true"` Habana's DeepSpeed launcher but it does not work for multi-node runs. This PR fixes this behaviour.
=> Set the env variable USE_DEEPSPEED_HPU to "true" in deepspeed.py

README.md, docs/source/package_reference/gaudi_config.mdx, docs/source/quickstart.mdx, docs/source/usage_guides/accelerate_training.mdx, optimum/habana/diffusers/pipelines/pipeline_utils.py, optimum/habana/transformers/gaudi_configuration.py, optimum/habana/transformers/trainer.py, optimum/habana/utils.py, tests/configs/gaudi_config_trainer_test.json, tests/test_gaudi_configuration.py
Removes `hmp_opt_level` in `GaudiConfig` as it is now recommended to not use it anymore.
Also removes `input_shape_hash`, `copy_to` and `CachedParams` in `utils.py` since those are now defined in `habana_frameworks.torch.hpu.graphs`.
=> Remove O1/O2 in Gaudi config

optimum/habana/diffusers/pipelines/pipeline_utils.py, optimum/habana/transformers/gaudi_configuration.py, optimum/habana/transformers/trainer.py
`hmp_opt_level` was removed in #169 because it is deprecated. This PR makes its use possible again but will display a warning if the given Gaudi config contains it. Will be removed in a future version.
=> Deprecate the usage of `hmp_opt_level` rather than remove it

examples/image-classification/README.md, tests/baselines/swin_base_patch4_window7_224_in22k.json, tests/baselines/vit_base_patch16_224_in21k.json
Add dataloader_num_workers  into example command line for ViT and Swin for better performance
here is the perfomrance data of ViT I measured in my local machine .
- Gaudi2
| dataloader_num_workers | 8X  |  1X  |
|--|--|--|
|0 (default)| 2040 | 508 |
|1| 3954| 797|
|2| 3894| 870|
|4| 3896| 985|
|8| 3831| 948|
-Gaudi
| dataloader_num_workers | 8X  |  1X  |
|--|--|--|
|0 (default) | 1605| 315|
|1| 2008| 316|
|2| 2030| 318|
|4| 1979| 332|
|8| 1911| 316|
```bash
python run_image_classification.py --model_name_or_path google/vit-base-patch16-224-in21k --dataset_name cifar10 --output_dir /tmp/outputs/  --remove_unused_columns False --do_train  --learning_rate 3e-5 --num_train_epochs 1 --per_device_train_batch_size 64 --evaluation_strategy no --save_strategy no --load_best_model_at_end no …
```
=> Adding dataloader_num_workers into example command for better performance

optimum/habana/transformers/trainer_utils.py
This PR improves the [`get_dtype`](https://github.com/huggingface/optimum-habana/blob/456096d9fd48f91b35fb82c860bb29a94158d93d/optimum/habana/transformers/trainer_utils.py#L22) method so that it can deal with dictionaries. It currently raises an error if it is provided a dictionary, which can happen as in #191.
=> Fix get_dtype in trainer_utils.py so that it can deal with dictionaries

optimum/habana/transformers/trainer_seq2seq.py
This PR fixes an issue introduced in #202  with the `GaudiSeq2SeqTrainer` class. The `gaudi_config` argument in the `__init__` method was missing, which triggered an error if `gaudi_config_name` is `None` in the training arguments.
=> Fix GaudiSeq2SeqTrainer

docs/source/usage_guides/accelerate_training.mdx, optimum/habana/transformers/trainer.py, optimum/habana/transformers/training_args.py, tests/baselines/swin_base_patch4_window7_224_in22k.json, tests/baselines/vit_base_patch16_224_in21k.json
improve Habana HPU performance by adding a new command line args `pipelining_fwd_bwd ` .
when running model on Habana HPU, it is very important to pipelining host graph building and device computing, this PR is to add an additional mark_step between `forward` and `backward` in `training_step` to pipeline the host graph building of backward and device computing of forward. 
profile is bellow:
disable `pipelining_fwd_bwd `
device fwd is after host bwd
enable `pipelining_fwd_bwd `
host bwd and device fwd is pipelined
the final time cost saving is the `cost of host bwd building graph`
here is the performance measured on my local Gaudi2 and Gaudi machine
-gaudi2
| pipelining_fwd_bwd        | 8x        | 1x        |
|                                        -|           -|           -|
|   True …
=> add mark_step between fwd and bwd for better performance

Makefile
The CI is run on the main branch of Transformers to catch changes/issues introduced in Transformers before they are released. Now that Transformers' Trainer relies on Accelerate (see https://github.com/huggingface/transformers/pull/22752), all regression tests relying on it fail (example [here](https://github.com/huggingface/optimum-habana/actions/runs/4725782013)). As a temporary workaround and till proper support for HPUs is integrated into Accelerate, the CI will be run with the latest release of Transformers from now on.
=> Run CI on Transformers' latest release

tests/test_examples.py, tests/utils.py
This PR adds commented blocks of code that can be uncommented to enable regression tests on the `run_speech_recognition_ctc.py` example script. The reason why they are disabled by default is that they take long enough to make the GH workflows reach the 6-hour timeout.
=> Add commented blocks in CI for speech recognition

examples/text-generation/README.md, examples/text-generation/run_generation.py
This PR adds the argument `bf16` to the text-generation script to be able to run generation in full bf16 precision. It removes the use of Gaudi config that would apply mixed precision.
=> Add `--bf16` to the text-generation example

examples/protein-folding/README.md, examples/protein-folding/run_esmfold.py, optimum/habana/transformers/modeling_utils.py, optimum/habana/transformers/models/__init__.py, optimum/habana/transformers/models/esm/__init__.py, optimum/habana/transformers/models/esm/modeling_esmfold.py
Add support of ESMFold on HPU
This PR modified some implementations on modeling_esmfold.py and modeling_utils.py to fit in HPU. These changes are either to optimize the performance on HPU, or make sure the model can run on HPU correctly.
A example demo was also created under example/esm folder to show how to do protein folding prediction with ESMFold on HPU. The content of this demo is same as the one from this link,  https://colab.research.google.com/github/huggingface/notebooks/blob/main/examples/protein_folding.ipynb, except adding several lines of code to run it on HPU with optimum-habana. The output of the demo is a pdb file. It contains the predicted 3D positions of the protein's atoms. The values of these positions have been verified with the values that got from GPU.
=> Add support of ESMFold on HPU

optimum/habana/transformers/trainer.py, optimum/habana/transformers/training_args.py, optimum/habana/utils.py
In the case that train time is very short, the distributed training throughput is greatly impacted by saving checkpoint time, and it gives misleading scaling effciency. This patch provides an option to remove the save checkpoint time from throughput calculation.
=> Added an option to remove save checkpoint time from throughput calculation

optimum/habana/transformers/trainer.py, optimum/habana/transformers/training_args.py, tests/test_trainer.py
The profiler is currently stopped at the end of the 1st epoch. This should be done after the last training iteration.
I also added a test to be able in the future to catch this kind of error before merging.
=> Fix profiling in GaudiTrainer

examples/text-generation/run_generation.py
This PR fixes an issue where multi-card text generation with DeepSpeed fails.
Basically, we need to move imports from `optimum.habana.xxx` after [this line](https://github.com/huggingface/optimum-habana/blob/fe3e10aa5a69ed4b53eba0cc5fabf2b554fa63f5/examples/text-generation/run_generation.py#L120) to make sure env variables are correctly set. Otherwise, it will probably import `habana_frameworks` at some point, which initializes env variables with a default value.
=> Fix text generation with DeepSpeed

examples/text-generation/checkpoint_utils.py, examples/text-generation/run_generation.py
facebook/opt-125m
ds mode
cmd 
```bash
python ../gaudi_spawn.py --use_deepspeed --world_size 1 run_generation.py --model_name_or_path facebook/opt-125m --batch_size 1 --use_hpu_graphs --use_kv_cache --max_new_tokens 100
```
outputs
non-ds mode
cmd
```bash
python run_generation.py --model_name_or_path facebook/opt-125m --batch_size 1 --use_hpu_graphs --use_kv_cache --max_new_tokens 100
```
outputs
know issue
- only support DS 1x, not support DS multi cards
- reasonable but different outputs of opt13B and bloom-560m between non-ds mode and ds mode, no sure if is a issue
=> OPT support DS 1x Inference

examples/text-generation/run_generation.py, optimum/habana/transformers/generation/utils.py
This PR exposes generation extra configuration knobs such as "bad_words_ids", "force_words_ids", "num_return_sequences" to user of run_generation.py.  Also adds code to support constrained_beam_search on HPU (must to support force_words_ids).
=> Add extra generation() configuration knobs to run_generation.py

examples/text-generation/checkpoint_utils.py, examples/text-generation/run_generation.py
This PR enables to download checkpoints with [`snapshot_download`](https://huggingface.co/docs/huggingface_hub/package_reference/file_download#huggingface_hub.snapshot_download) in all cases (it used to be the case for BLOOM only). This allows to have multiple downloads in parallel for sharded checkpoints, leading to shorter waiting times.
It also ensures that `snapshot_download` is not used if the checkpoint folder is local as it would raise an error.
=> Use `snapshot_download` whenever possible in the text-generation example

optimum/habana/transformers/models/gpt2/modeling_gpt2.py, optimum/habana/transformers/models/gpt_neox/modeling_gpt_neox.py, optimum/habana/transformers/models/gptj/modeling_gptj.py, optimum/habana/transformers/models/opt/modeling_opt.py
as title, `past_key.index_add_(2, token_idx - 1, key - torch.index_select(past_key, 2, token_idx - 1))` is used to WA HPU bug and has been fixed from  1.10.0, so could use `index_copy_` directly now
=> remove kv cache wa

optimum/habana/transformers/modeling_utils.py, optimum/habana/transformers/models/__init__.py, optimum/habana/transformers/models/gpt_neox/modeling_gpt_neox.py, optimum/habana/transformers/models/llama/__init__.py, optimum/habana/transformers/models/llama/modeling_llama.py
1. Improve Llama2 inference performance by using habana fused RoPE and RMSNorm
2. Improve gpt_neox inference performance by using habana fused RoPE
=> Improve Llama2 and gpt_neox performance with Habana fused RoPE and RMSNorm

.github/workflows/fast_tests.yml
Revert https://github.com/huggingface/optimum-habana/pull/313 as it is not a good solution given that it is not possible to disable notifications for review requests in github: https://github.com/orgs/community/discussions/14564. We do not want to get spammed by review requests at every commit.
The `authorize` job is run only when:
* The PR does not come from a fork ==> runs automatically ==> anybody with write access can still run workflows automatically
* The workflow is triggered not from `pull_request_target` event (e.g. rather `workflow_dispatch` that only people with write access can trigger)
* The PR is labeled `run-tests`, which triggers a `labeled` action type.
Note: this workflow is not susceptible to race condition on commits being added after the PR being labeled, given that …
=> Trigger workflows for external PRs on label

optimum/habana/transformers/models/llama/modeling_llama.py
Text generation with Llama2-70B currently fails because of a dimension issue in key/value layers when doing tensor parallelism.
You can test it on Gaudi2 with:
```bash
python ../gaudi_spawn.py --use_deepspeed --world_size 2 run_generation.py --model_name_or_path meta-llama/Llama-2-70b-hf --batch_size 1 --use_hpu_graphs --use_kv_cache --max_new_tokens 100
```
=> Fix inference with Llama-2-70B

optimum/habana/transformers/modeling_utils.py, optimum/habana/transformers/models/__init__.py, optimum/habana/transformers/models/t5/__init__.py, optimum/habana/transformers/models/t5/modeling_t5.py
Improve the performance of T5.
T5 layernorm is same with RMSNorm.
Test on run_translation
command:
generate 256 tokens for each sample
```python
python run_translation.py     --model_name_or_path t5-large     --do_eval     --source_lang en     --target_lang ro     --source_prefix "translate English to Romanian: "     --dataset_name wmt16     --dataset_config_name ro-en     --output_dir /tmp/tst-translation     --per_device_eval_batch_size 4    --overwrite_output_dir     --predict_with_generate     --use_habana     --use_lazy_mode     --use_hpu_graphs_for_inference     --gaudi_config_name Habana/t5     --ignore_pad_token_for_loss False     --pad_to_max_length --max_target_length=256 --dataloader_drop_last True
```
||before|after|
|-|-|-|
|eval loss|15.0345|15.0345| …
=> enable hpu rms fused kernel for t5

optimum/habana/transformers/modeling_utils.py, optimum/habana/transformers/models/__init__.py, optimum/habana/transformers/models/esm/__init__.py, optimum/habana/transformers/models/esm/modeling_esmfold.py
This PR removed 2 workarounds on esmfold scripts. These 2 workarounds were introduced before 1.10 release due to accuracy issue. 
I have verified that there is no accuracy issue on the generated pdb file after removing the 2 WAs.
=> remove two workarounds on esmfold after releasing 1.11.0

text-generation-inference/server/text_generation_server/models/causal_lm.py
run model EleutherAI/gpt-j-6b in TGI
curl 127.0.0.1:8080/generate \
-X POST \
-d '{"inputs":"What is DeepSpeed?","parameters":{"max_new_tokens":256, "do_sample": false}}' \
-H 'Content-Type: application/json'
~
{"generated_text":"QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ:QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ:QQQQQQQQQQQQQQQQQQQQQQQQQQQQQ:QDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD"
=> fix gptj incorrect output issue in TGI

examples/text-generation/README.md, examples/text-generation/run_generation.py, optimum/habana/transformers/generation/configuration_utils.py, optimum/habana/transformers/generation/utils.py, optimum/habana/transformers/modeling_utils.py
=> skip hpugraph usage for first token to save memory

optimum/habana/transformers/trainer.py, optimum/habana/transformers/training_args.py, optimum/habana/utils.py
The default argument of profiler ```record_shapes``` is ```True```. Enabling this may improve memory usage and may lead to some workload crashes with OOM when profiling is enabled. Setting ```record_shapes``` to ```False``` when it is not used could avoid these crashes and enable profiling.  
This pr makes the  ```record_shapes``` changeable.
=> makes the record_shapes of the profiler changeable.

examples/text-generation/run_generation.py, optimum/habana/transformers/generation/configuration_utils.py, optimum/habana/transformers/generation/utils.py, optimum/habana/transformers/models/llama/modeling_llama.py
Reuse cache pre allocates the KV cache. This can be further leveraged to slice the inputs till the token idx for the 1st token inference and improve perf and memory usage by running till the required seq len only rather than running full padded static input (input + max new tokens length). Memory usage and perf will vary according to the actual input seq len but will be better than running full static shapes.
Use torch.zeros to initialize KV cache rather than uninitialized torch.empty.
Also fix bool dtypes default values.
=> Improve perf and memory usage with reuse cache by slicing inputs till token idx for 1st token generation.

optimum/habana/accelerate/accelerator.py, optimum/habana/transformers/trainer.py
When I enable fast ddp with `--distribution_strategy fast_ddp`, the model is wrapped with `torch.nn.parallel.DistributedDataParallel` from `accelerator.prepare_model()`, this could be incorrect since fast ddp handles gradients all-reduce by itself. In this patch, it checks if it's not fast ddp before wrap with `torch.nn.parallel.DistributedDataParallel` in `accelerator`.
- no
- no need update doc 
- no need new tests
=> No need to wrap DDP when using Fast DDP

.github/workflows/fast_tests.yml, examples/text-generation/checkpoint_utils.py, optimum/habana/transformers/models/falcon/modeling_falcon.py
This patch fixes the error in falcon-40b with DeepSpeed, where the number of heads was updated by DeepSpeed and became too small. So the number of heads has been removed from the reshape and view ops. Instead, the correct number of heads is now inferred from other dim sizes
=> Fix falcon-40b error when DeepSpeed enabled

examples/text-generation/README.md
Update README with performance optimal command for LLaMAv2-70B text generation using deepspeed
Add LLaMAv2-70B text generation commands to README
=> Add LLaMAv2-70B text generation

optimum/habana/transformers/trainer.py, optimum/habana/transformers/trainer_seq2seq.py, optimum/habana/transformers/training_args.py
`sharded_ddp` is not used in Transformers anymore (see https://github.com/huggingface/transformers/pull/25702) and was never used on Gaudi anyway (since it's linked to Fairscale). Removing all occurrences.
=> Remove `sharded_ddp`

tests/test_trainer.py, tests/test_trainer_distributed.py
This change will fix the relative path in gaudi config. Instead uses the absolute path in the current execution env.
Errors caused by relative gaudi config path when test is triggered from a different path.
=> Fixing the relative path in config read

optimum/habana/transformers/models/bloom/modeling_bloom.py
Add suport for cases where tp_size != world size
we encountered a case during develoment of DS chat step 3 where the tp size for inference needs to be different than the world size. The  code in modeling_bloom.py assumes that tp size is always equal to world size in inference and this change allows to configure it differently.
Add suport for cases where tp_size != world size
we encountered a case during develoment of DS chat step 3 where the tp size for inference needs to be different than the world size. The  code in modeling_bloom.py assumes that tp size is always equal to world size in inference and this change allows to configure it differently.
=> Add support of tp_size != WORLD_SIZE to bloom

tests/transformers/tests/generation/test_utils.py
These are fixes for issues caught while executing the transformers tests. The issues are captured in https://github.com/huggingface/optimum-habana/issues/445 and
https://github.com/huggingface/optimum-habana/issues/446
Addressed based on suggestion give here : https://github.com/huggingface/optimum-habana/pull/470#issuecomment-1773121023
@regisss  : please help with the review 
TCs impacted ( listed for t5 but these are common TCs impacting all language models)
==============================================================
FAILED test_modeling_t5.py::T5ModelTest::test_beam_search_generate - KeyError: 'limit_hpu_graphs'
FAILED test_modeling_t5.py::T5ModelTest::test_beam_search_generate_dict_output - KeyError: 'limit_hpu_graphs'
FAILED …
=> Add default model_kwargs to Generation Tester

examples/language-modeling/run_lora_clm.py
If a dataset doesn't have validation subset, partial of data will be split into tokenized_datasets["validation"]. but later tokenized_datasets["test"] was used for eval.
=> Fix split validation dataset problem

optimum/habana/transformers/generation/utils.py
Some models have extra inputs, which need to be padded as well. This fix is for a gpt2 variant
token_type_ids information:
this is used if the model has 2 input sentences. for example to do classification on pairs of sentences, or question answering
https://huggingface.co/docs/transformers/glossary#token-type-ids
for regular generation `token_type_ids` is expected to be "0" always as far as i understand, because there is only 1 sentence type
=> Some models have extra inputs, pad them too

optimum/habana/accelerate/state.py
If using ray or torchrun to launch the distributed finetune or training with deepspeed, No need to check the torch.distributed.is_initialized, the deepspeed.ini_dist will check it and assign the TorchBackend to cdb
=> Fix deepspeed init issue when using external launcher.

optimum/habana/transformers/generation/utils.py, optimum/habana/transformers/models/llama/modeling_llama.py
fixing update method - avoid copy idx to cpu which splitting the graph
issue description:
in the update method when calling to 
prev[:, :, :idx, :].copy_(cur)
the split method is using scalars and not tensors, so pytorch convert the tensor to scalar and only then call to split..
so once we need to convert the tensor to scalar, the bridge is doing mark step and splitting the graph until this point..
=> fixing update method - avoid copy idx to cpu which splitting the graph

examples/language-modeling/run_lora_clm.py, optimum/habana/transformers/models/llama/modeling_llama.py, optimum/habana/transformers/trainer.py, tests/baselines/llama_7b.json
This PR adds an input arg to enable BF16 attention softmax layer for Llama finetuning.
=> Enable llama attention softmax in bf16

examples/language-modeling/run_lora_clm.py, optimum/habana/transformers/models/llama/modeling_llama.py, optimum/habana/transformers/trainer.py
This addresses an error from the attn_softmax_bf16 change in cases where self.model.generation_config exists but is 'None'.
=> Fix for attn_softmax_bf16 when generation_config is None

optimum/habana/utils.py
Example for a run:
====================================
output.stdout:
'habana-torch-plugin     1.14.0.71         \n'
====================================
output.stdout.split("\n")[0].split(" "):
['habana-torch-plugin', '', '', '', '', '1.14.0.71', '', '', '', '', '', '', '', '', '']
so taking the -1 will result in an empty string
====================================
output.stdout.split("\n")[0].split():
['habana-torch-plugin', '1.14.0.71']
so taking -1 will result in the version
=> Fix split by whitespaces not a single space

examples/text-generation/README.md, examples/text-generation/requirements.txt
model trl-lib/llama-7b-se-rm-peft(one of example in text_generation example) is not compatible with peft v.0.6.0.
Change the example model to other llama-7b-peft model which doesn't use old config parameter. 
https://huggingface.co/trl-lib/llama-7b-se-rm-peft/discussions/3
=> Update PEFT model example

text-generation-inference/README.md, text-generation-inference/server/text_generation_server/models/causal_lm.py
When sequence_length is large, we are getting out of memory on LLama70b for 8x. Adding an option to turn on/off HPU graph for just for the prefill. 
Environment variable "LIMIT_HPU_GRAPH=True" to be added to Docker run command  to enable this feature. 
command fails without this change with OOM error. 
text-generation-benchmark -t /mnt/weka/data/llama_inference/Llama-2-70b-hf/ --batch-size 32 -s 300 -d 212 -r 2
=> Add LIMIT_HPU_GRAPH option to save memory for prefill OOM issue

optimum/habana/transformers/models/codegen/modeling_codegen.py, optimum/habana/transformers/models/gpt_bigcode/modeling_gpt_bigcode.py
when using startcode and codegen for text generation, when --do_sample is enabled in the command line. error like
File "/intel-extension-for-transformers/optimum-habana/examples/text-generation/run_generation.py", line 484, in <module>
main()
File "/intel-extension-for-transformers/optimum-habana/examples/text-generation/run_generation.py", line 288, in main
generate()
File "/intel-extension-for-transformers/optimum-habana/examples/text-generation/run_generation.py", line 269, in generate
outputs = model.generate(
File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
return func(*args, **kwargs)
File "/intel-extension-for-transformers/optimum-habana/optimum/habana/transformers/generation/utils.py", line …
=> no need to unsqueeze input_id in prepare_inputs_for_generation

examples/text-generation/utils.py
The PEFT config contains the path to the base model but sometimes this path doesn't exist locally or remotely. This PR enables to fall back to the regular model argument which will be used as the base one.
=> Add fallback for PEFT when the base model doesn't exist

optimum/habana/transformers/trainer.py
GPT2 doesn't yield good accuracy with autocast enabled, but report nan-loss. 
Until the issue is fixed, we are enabling hmp for gpt2 model.
=> Add workaround for GPT2 gaudi config for autocast

examples/text-generation/utils.py, optimum/habana/utils.py
fix hash_with_views error
this api is no longer valid at next release
=>  fix hash_with_views error

examples/language-modeling/README.md, examples/language-modeling/llama2_ds_zero3_config.json, examples/language-modeling/run_lora_clm.py
=> add dataset disposal of b-mc2/sql-create-context for codegen and fix zero3 lora save issue

examples/text-generation/utils.py, optimum/habana/transformers/modeling_utils.py, optimum/habana/transformers/models/__init__.py, optimum/habana/transformers/models/llama/__init__.py, optimum/habana/transformers/models/llama/modeling_llama.py, optimum/habana/transformers/models/modeling_all_models.py
Module for scope linearAllreduce
this change allows better memory consumption and better optimizations in synapse when running llama 70b on deepspeed
=> Refactoring LLama Attention and mlp layers

examples/text-generation/run_generation.py, optimum/habana/transformers/generation/configuration_utils.py, optimum/habana/transformers/generation/utils.py, optimum/habana/transformers/models/llama/modeling_llama.py, optimum/habana/transformers/trainer.py
This PR introduces support for FusedSDPA operator (Flash Attention) in Llama2.
Below are preliminary results from this change:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">
<head>
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/wszczure/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/wszczure/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
</head>
<body link="#0563C1" vlink="#954F72">
Model | BS | Max input tokens | Max new tokens | Default performance   [tokens/second] | Performance with FusedSDPA …
=> Support for FlashAttention in Llama2

optimum/habana/transformers/modeling_utils.py, optimum/habana/transformers/models/codegen/modeling_codegen.py, optimum/habana/transformers/models/gpt2/modeling_gpt2.py, optimum/habana/transformers/models/gptj/modeling_gptj.py
See #181 and #318. Booleans seems to be now supported in HCCL.
=> Remove workarounds to have `causal_mask` in uint8 for GPT2, GPT-J and CodeGen

examples/language-modeling/run_lora_clm.py, optimum/habana/transformers/generation/configuration_utils.py, optimum/habana/transformers/generation/utils.py, optimum/habana/transformers/models/llama/modeling_llama.py, optimum/habana/transformers/trainer.py
=> Integrate Habana flash attention to Llama2-70B finetune

optimum/habana/accelerate/data_loader.py, optimum/habana/accelerate/utils/operations.py
TRL SFT trainer has used IterableDataset and DataLoaderDispatcher will be called. The data shape/tensor will be broadcasted from rank 0 to other rank in DDP.
=> fix DataLoaderDispatcher issue in Gaudi

optimum/habana/utils.py
After the PR #587, Falcon inference fails with Synapse 1.13.0 because this comparison in here always returns False.
https://github.com/huggingface/optimum-habana/blob/21238af3e2e4eff84d1db3315d977004c49b45b4/optimum/habana/utils.py#L343 
This is because get_habana_frameworks_version() returns 1.13.0.xxx whereas version.parse(req_version) is 1.13.0.
Thus this PR was created to compare the major and minor versions.
=> Fix for Falcon error from PR #587

optimum/habana/diffusers/pipelines/pipeline_utils.py, optimum/habana/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py, optimum/habana/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_ldm3d.py, optimum/habana/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_upscale.py
Make Gaudi pipleines inherit from Diffusers pipelines so that we have to maintain less code. We have to be careful here because of multiple inheritance.
=> Add inheritance in Diffusers pipelines

examples/trl/stack_llama_2/README.md, examples/trl/stack_llama_2/dpo_llama2.py, examples/trl/stack_llama_2/merge_peft_adapter.py, examples/trl/stack_llama_2/requirements.txt, examples/trl/stack_llama_2/sft_llama2.py, optimum/habana/trl/__init__.py, optimum/habana/trl/trainer/__init__.py, optimum/habana/trl/trainer/dpo_trainer.py, optimum/habana/trl/trainer/sft_trainer.py
=> add DPO and SFT of TRL support in Gaudi and example

optimum/habana/transformers/models/falcon/modeling_falcon.py
This add a code block from transformers to fix the gc error when bs>1
=> Falcon graph compilation error fix for when bs>1

optimum/habana/transformers/models/falcon/modeling_falcon.py
#607 fixed the graph compilation error for BS>1 but it degrades the perf when BS=1.
So an additional condition was added to apply the change in PR#607 only when BS>1
=> Avoid falcon perf drop from PR#607 when BS=1

examples/summarization/README.md, optimum/habana/transformers/trainer.py, optimum/habana/transformers/training_args.py, tests/test_encoder_decoder_text_summarization.py
=> Adding support for bf16_full_eval

optimum/habana/transformers/models/llama/modeling_llama.py
=> Enable fused rmsnorm in bf16 for llama

tests/example_diff/run_generation.txt
=> Update CI diff file

optimum/habana/transformers/models/llama/modeling_llama.py
I am enabling RLHF in habana, when enable reward model finetuning in 8 gaudi2 card using DDP. error happened in backward.
code like 
https://github.com/intel/intel-extension-for-transformers/blob/main/intel_extension_for_transformers/neural_chat/examples/finetuning/ppo_pipeline/reward_modeling.py
command like 
python ../instruction/gaudi_spawn.py --world_size 8 --use_mpi reward_modeling.py --model_name_or_path meta-llama/Llama-2-7b-hf  --log_level info  --num_train_epochs 3 --use_habana  --output_dir output --ddp_find_unused_parameters True   --logging_steps 10 --use_lazy_mode --evaluation_strategy="steps"
error like
File "/root/intel-extension-for-transformers/intel_extension_for_transformers/neural_chat/examples/finetuning/ppo_pipeline/reward_modeling.p …
=> fix backward error in DDP when running reward model finetune in RLHF

optimum/habana/trl/trainer/dpo_trainer.py, optimum/habana/trl/trainer/sft_trainer.py
fix graph compilation issue in evaluation
=> fix dpo graph compile error in evaluation

docs/Dockerfile, optimum/habana/transformers/training_args.py, tests/test_trainer.py
Cleanup code in training_args.py to remove setting of PT_HPU_LAZY_MODE=2 (this is not supported SynapseAI release 1.13.0 onwards).
=> Remove setting of PT_HPU_LAZY_MODE=2 in training_args.py

examples/image-classification/README.md, examples/image-classification/run_image_classification.py, tests/baselines/swin_base_patch4_window7_224_in22k.json, tests/baselines/vit_base_patch16_224_in21k.json
See https://github.com/huggingface/transformers/pull/28408.
=> Fix error in run_image_classification.py

optimum/habana/transformers/models/llama/modeling_llama.py
=> fix RLHF llama rewarding modeling backward issue

examples/gaudi_spawn.py, examples/text-generation/README.md, optimum/habana/distributed/distributed_runner.py
This PR adds a parameter to set `master_port` for DeepSpeed and MPI, which is motivated by running multiple DeepSpeed tasks simultaneously with each task using various parts of the HPUs.
=> enable master_port selecting for DeepSpeed and MPI

tests/example_diff/run_audio_classification.txt, tests/example_diff/run_clip.txt, tests/example_diff/run_clm.txt, tests/example_diff/run_glue.txt, tests/example_diff/run_image_classification.txt, tests/example_diff/run_mlm.txt, tests/example_diff/run_qa.txt, tests/example_diff/run_seq2seq_qa.txt, tests/example_diff/run_speech_recognition_ctc.txt, tests/example_diff/run_summarization.txt, tests/example_diff/run_translation.txt
=> Update example diff files

optimum/habana/transformers/models/llama/modeling_llama.py
=> Flash attention enhancement of repeatKV

examples/language-modeling/fsdp_config.json, examples/language-modeling/run_lora_clm.py, examples/question-answering/fsdp_config.json, examples/question-answering/gaudi_config.json, optimum/habana/accelerate/accelerator.py, optimum/habana/accelerate/state.py, optimum/habana/accelerate/utils/__init__.py, optimum/habana/accelerate/utils/dataclasses.py, optimum/habana/peft/__init__.py, optimum/habana/peft/layer.py, optimum/habana/transformers/models/llama/modeling_llama.py, optimum/habana/transformers/trainer.py, optimum/habana/transformers/training_args.py, tests/test_fsdp_examples.py
Add changes to support FSDP. BERT-Base enabled with FSDP as a toy example.
=> Add changes to support FSDP

examples/text-generation/run_generation.py, examples/text-generation/utils.py, tests/test_text_generation_example.py
=> Run Llama2 with torch.compile on Gaudi2

tests/example_diff/run_generation.txt
=> Update text-generation example diff file

optimum/habana/transformers/models/llama/modeling_llama.py
Fixing compile error seen with torch-compile option. 
File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/variables/base.py", line 225, in as_python_constant
raise NotImplementedError(f"{self} is not a constant")
torch._dynamo.exc.InternalTorchDynamoError: SymNodeVariable() is not a constant
524381 [2024-01-24T07:03:06.868Z] from user code:
524382 [2024-01-24T07:03:06.868Z]    File "/root/optimum-habana/optimum/habana/transformers/models/llama/modeling_llama.py", line 294, in <resume in pre_attn_forward>
524383 [2024-01-24T07:03:06.868Z]     if attn_weights.size() not in [
=> Fix compile error for torch_cmpile for llama

optimum/habana/transformers/generation/utils.py
Previously, if run_generation.py ran with other than "llama" model and --reuse_check there was an error:
```AttributeError: 'GaudiMistralForCausalLM' object has no attribute 'allocate_kv_cache'```
Now there is a more user-freindly message describing the problem:
```AssertionError: reuse_cache only supported by llama at the moment```
=> Added check if reuse_cache supported by selected model_type

.github/workflows/slow_tests_gaudi2.yml, Makefile, tests/test_fsdp_examples.py
=> Add FSDP test to Gaudi2 CI

optimum/habana/utils.py
=> Fix version check when console output is disabled

examples/text-generation/text-generation-pipeline/README.md, examples/text-generation/text-generation-pipeline/pipeline.py, examples/text-generation/text-generation-pipeline/run_pipeline.py
This PR includes some minor changes to the text-generation pipeline code for langchain==0.0.191 compatibility.
=> Patch for Gaudi Text-Generation Pipeline

tests/transformers/tests/test_modeling_common.py
Fixed two issues from tests.models.bert.test_modeling_bert.BertModelTest
1) test_model_weights_reload_no_missing_tied_weights
The script is updated same as https://github.com/huggingface/transformers/blob/v4.37.2/tests/test_modeling_common.py#L1912
2) test_save_load_fast_init_to_base
Change 'model.config.save_pretrained(tmpdirname)' to 'model.save_pretrained(tmpdirname)'
Referred from https://github.com/huggingface/transformers/issues/9517
=> Update transformer model test script to match with 4.37.1

tests/transformers/tests/models/falcon/test_modeling_falcon.py
Test failed with below error. 
E       AttributeError: 'GaudiFalconForCausalLM' object has no attribute '_convert_to_rw_cache'
_convert_to_rw_cache is no longer supported in transformer v4.37.2. Test case is removed.
=> Remove falcon model cache unit test 

examples/image-classification/requirements.txt, examples/image-classification/run_image_classification.py
This PR updates the dependency requirements for image-classification case.
The _run_image_classification.py_ script in the current implementation uses the _token_ parameter, which was introduced as of **datasets** version 2.14.0. Thus, using packages below the specified version may cause errors.
Please see the release link below:
https://github.com/huggingface/datasets/releases/tag/2.14.0
An example of using the argument _token_ in the _run_image_classification.py_ script is shown below:
```
if data_args.dataset_name is not None:
dataset = load_dataset(
data_args.dataset_name,
data_args.dataset_config_name,
cache_dir=model_args.cache_dir,
token=model_args.token,
)
```
https://github.com/huggingface/optimum-habana/blob/main/examples/image-classification/run_image_classification.py#L277
=> Updated requirements for image-classification samples: datasets>=2.14.0

README.md, examples/audio-classification/README.md
=> Add instruction in README to checkout latest stable release

optimum/habana/transformers/models/llama/modeling_llama.py
From Harshvardhan:
> I ran the llama2-70B FT command from README after the PR [#651](https://github.com/huggingface/optimum-habana/pull/651) was merged in master. I saw performance drop as shown below.
> 
> with PR:
> ***** train metrics *****
>   epoch                       =        2.0
>   max_memory_allocated (GB)   =      79.79
>   memory_allocated (GB)       =      37.25
>   total_memory_available (GB) =      94.62
>   train_loss                  =     0.8327
>   train_runtime               = 0:45:40.05
>   train_samples_per_second    =      2.376
>   train_steps_per_second      =       0.03
> 
> without PR:
> ***** train metrics *****
>   epoch                       =        2.0
>   max_memory_allocated (GB)   =       71.8
>   memory_allocated (GB)       =      26.61
> …
=> Fix Llama initialization

examples/text-generation/README.md, examples/text-generation/run_generation.py, examples/text-generation/utils.py, optimum/habana/transformers/generation/configuration_utils.py, optimum/habana/transformers/generation/utils.py, optimum/habana/transformers/models/llama/modeling_llama.py
To enhance throughput in scenarios with long new tokens, break down the KV cache into multiples of the bucket width. Use this to compute attention rather than using the entire KV cache.
LLaMA v2 70B (8x, max_input_tokens 128, max_new_tokens 2048, batch_size 240):
**5528 tps (original performance) -> 6378 tps (w/ internal bucket size 128)**
Add `--bucket_size=128 --bucket_internal` to the commands to enable the feature.
=> enable internal kv bucket in llama

optimum/habana/diffusers/pipelines/controlnet/pipeline_controlnet.py, optimum/habana/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py, optimum/habana/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_ldm3d.py, optimum/habana/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_upscale.py, optimum/habana/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py
Fixes the throughput calculation for stable diffusion models when using configurable warm-up steps.
=> Fix throughput calculation for diffusion models

optimum/habana/transformers/models/llama/modeling_llama.py
=> fix crash in llama mode in llava image-to-text generation

examples/text-generation/README.md
Update fp8 hqt example of mixtral-8x7b (1x) to README
**Test with bs16_output2048 on 1 card**:
Input/outputs:
input 1: ('DeepSpeed is a machine learning framework',)
output 1: ('DeepSpeed is a machine learning framework that enables training of large models on a single machine with a single GPU. It is designed to be easy to use and efficient, and it can be used to train models on a variety of tasks.\n\n## ...
input 2: ('He is working on',)
output 1: ("He is working on a new album, which is expected to be released in 2019.\n\n## ...
input 3: ('He has a',)
output 1: ('He has a new book out, and he’s on a book tour.\n\n ...
input 4: ('He got all',)
output 1: ('He got all the way to the top of the mountain, but he didn’t know what to do when he got there.\n\n ...
input 5: ('Everyone is happy …
=> Update Mixtral-8x7B fp8 hqt example

optimum/habana/transformers/trainer_utils.py
Fixes #754.
The fix consists in extracting the dtype of the first logit tensor and set it as the target dtype. We used to extract the dtypes of all logit tensors, leading to nested tuples that led to this issue. There is no reason for logits to have different dtypes, so we can simplify the dtype extraction logic.
=> Fix `get_dtype` and `convert_into_dtypes`

optimum/habana/transformers/modeling_utils.py, optimum/habana/transformers/models/__init__.py, optimum/habana/transformers/models/modeling_all_models.py
From torch 2.1 and above, SDPA attention is enabled by default. Due to this some models that we enabled are failing due to SDPA attention layer is not comparable with our code. Affected models are bart,gpt_bigcode,mistral and mixtral
TypeError: GPTBigCodeSdpaAttention.forward() got an unexpected keyword argument 'token_idx'
TypeError: BartSdpaAttention.forward() got an unexpected keyword argument 'token_idx'
We are overriding check sdpa method for Gaudi for these model to disable sdpa until we have fusedSDPA support for them. All other models will follow original implementation. 
https://github.com/huggingface/transformers/blob/v4.37.2/src/transformers/modeling_utils.py#L1542
=> Override sdpa option in Gaudi

examples/language-modeling/run_lora_clm.py, optimum/habana/transformers/training_args.py
When running large models with FSDP, if we try to load full model params to each card we will run out of CPU RAM (refer to this these PRs https://github.com/huggingface/transformers/pull/25107  https://github.com/huggingface/accelerate/pull/1777. This is avoided by loading model params only to card 0 and broadcasting params to other cards from card 0. Enabled CPU_RAM_EFFICIENT_LOADING configuration in accelerate to support above described functionality.
=> Fix Llama-70B-FSDP model loading issue

examples/language-modeling/run_lora_clm.py, optimum/habana/transformers/generation/configuration_utils.py, optimum/habana/transformers/generation/utils.py, optimum/habana/transformers/models/llama/modeling_llama.py, optimum/habana/transformers/trainer.py
Provide variable to enable/disable FusedRoPE. This may be useful for integrating new models or configurations where FusedRoPE may not work out of the box.
=> Expose Llama Fused OPs control from run_lora_clm.py

README.md, docs/source/index.mdx, examples/image-to-text/README.md, examples/image-to-text/run_pipeline.py, examples/visual-question-answering/README.md, examples/visual-question-answering/run_pipeline.py
=> add image-to-text and visual question answering example

optimum/habana/transformers/generation/utils.py, tests/transformers/tests/generation/test_utils.py
=> Fixing tests by making static_shapes False

optimum/habana/transformers/generation/utils.py, optimum/habana/transformers/models/llama/modeling_llama.py
Calculate kv cache sliding idx for the decode phase only. 
This PR has additional enhancements over https://github.com/huggingface/optimum-habana/pull/720. 
token_idx_cpu is introduced which is an integer rather than a tensor to keep track of buckets. And the switch of buckets happens after the prefill phase.
Assume input tokens as 128 and new tokens as 512.
Without bucketing and slicing changes in these 2 PRs, in the decode phase we used to calculate the attention scores by multiplying with full KV cache of size (512+128).
Now with the changes of these 2 PRs, we l consider KV caches as below:
Decode phases of tokens 128-256 -> sliced KV cache till seq len 256.
Decode phases of tokens 256-384 -> sliced KV cache till seq len 384.
Decode phases of tokens 384-512 -> sliced KV cache till seq …
=> Further fixes for performance with internal bucketing.

optimum/habana/transformers/modeling_utils.py, optimum/habana/transformers/models/__init__.py, optimum/habana/transformers/models/gpt_neox/__init__.py, optimum/habana/transformers/models/gpt_neox/modeling_gpt_neox.py, tests/baselines/gpt_neox_20b.json
When using DeepSpeed, the whole model is casted to bf16, including RoPE parameters. This makes the trained model performance much worse so this PR ensures RoPE parameters are computed in fp32.
=> Workaround for RoPE computed in bf16 for GPT-NeoX

examples/summarization/README.md
document change for Summarization. Removed statement "Only --num_beams 1 is supported for BART." as other options for num_beams are supported part of PR-627
=> Update summarization example README

optimum/habana/transformers/generation/utils.py, tests/transformers/tests/test_modeling_common.py
=> Block torchscript pytest because of seg fault issue

optimum/habana/transformers/modeling_utils.py, optimum/habana/transformers/models/__init__.py, optimum/habana/transformers/models/swin/__init__.py, optimum/habana/transformers/models/swin/modeling_swin.py
In certain 1x systems , we notice a drop in performance for swin models as get_attn_mask gets executed in cpu instead of hpu. This was seen after pytorch upgrade to 2.2
This fix allows img_mask in get_attn_mask() to be moved back hpu.
=> move img_mask@get_attn_mask() to hpu

examples/contrastive-image-text/clip_media_pipe.py
Replaces backend mediapipe API with newer one.
Tested for backward compatibility with synapse 1.14.
=> Replacing obsolete API for mediapipe

examples/contrastive-image-text/README.md, tests/baselines/bridgetower_large_itm_mlm_itc.json
As per title. The BridgeTower CI regression test fails without `--distribution_strategy fast_ddp`.
=> Add `--distribution_strategy fast_ddp` in contrastive-image-text README and BridgeTower test

optimum/habana/transformers/generation/utils.py, optimum/habana/transformers/models/llama/modeling_llama.py, optimum/habana/transformers/trainer.py
1. Fixes Graph Breaks in torch compile mode
2. Fixes comments in https://github.com/huggingface/optimum-habana/pull/751
=> Fix graph breaks in torch compile mode

optimum/habana/transformers/trainer.py
Fix FSDP ci test issue with "TypeError: Object of type Tensor is not JSON serializable"
Transformer 4.38 logs the grad_norm in log_history. But FSDP doesn't have global grad norm function. When logging non-scalar tensor, the .item fails. The solution now is not to log grad_norm in logging_history for FSDP.
=> Fix FSDP in transformer4.38

optimum/habana/transformers/models/mixtral/modeling_mixtral.py
We are seeing 2-3 secs total run time slowness with most of the mpi multicard tests with deepspeed installed compare to the one without.  We found this part is being called for every single model run which causing the slowdown. 
https://github.com/huggingface/optimum-habana/blob/main/optimum/habana/transformers/models/mixtral/modeling_mixtral.py#L65
=> Delay importing deepspeed comm due for perf

optimum/habana/transformers/models/llama/modeling_llama.py, optimum/habana/transformers/trainer.py
Transformer 4.38 changes the rotary embedding implementation, we changed rotaryembedding class to be the same as transformers4.37, but not apply_rotary_pos_emb. We should use apply_rotary_pos_emb as 4.37 too.
=> Fix llama rotary pos emb issue for transformers 4.38

optimum/habana/transformers/models/llama/modeling_llama.py
Text-generation tests with torch.compile currently fail, this PR fixes this issue.
=> Fix torch.compile for text generation

examples/question-answering/README.md, examples/question-answering/run_qa.py
Added Llama/Llama2 support in Question-Answering
=> Add Llama/Llama2 support in Question-Answering

optimum/habana/transformers/models/llama/modeling_llama.py
Fix torch.full issue below when running deepspeed z3 for llama. It's introduced by transformers 438 upgrade.
RuntimeErrorwork = default_pg.broadcast([tensor], opts) : 0 INTERNAL ASSERT FAILED at "/npu-stack/pytorch-fork/torch/csrc/jit/ir/alias_analysis.cpp":615, please report a bug to PyTorch. We don't have an op for aten::full but it isn't a special case.  Argument types: int[], bool, int, NoneType, Device, bool,
=> Fix torch.full issue below when running deepspeed z3 for llama

examples/language-modeling/run_mlm.py, tests/example_diff/run_mlm.txt
Following https://github.com/huggingface/transformers/pull/29776.
=> Update MLM example

examples/text-generation/quantization_config/act_maxabs_hw_weights_pcs_maxabs_pow2_quant.json, examples/text-generation/quantization_config/maxabs_measure.json, examples/text-generation/quantization_config/maxabs_quant.json, examples/text-generation/quantization_config/unit_scale_quant.json, tests/transformers/tests/test_modeling_common.py
Rename whitelist and blacklist to allowlist and blocklist
=> Rename whitelist & blacklist #71

examples/text-generation/run_generation.py, examples/text-generation/run_lm_eval.py, examples/text-generation/utils.py
Add disk_offload flag that controls device_map=auto. Setting this flag enbales weights offload to disk when cpu memory runs OOM.
Add const serialization path flag that gets a path for where to serialize const sections, so if there is no space on device to save all const sections they will be offloaded to disk.
This branch replaces the branch from PR #762
=> Enable Llama2 70B to run with hqt on single card (#50)

examples/text-generation/quantization_tools/unify_measurements.py
A tool that takes jsons with range measurements of tensors that were measured on multiple cards and unifies this measurements so we can run quantization with less cards than we measured.
Running example:
```
python optimum-habana/examples/text-generation/quantization_tools/unify_measurements.py  --measurements hqt_measured_folder --groups 01234567 --out hqt_measured_unified_folder 
```
=> Added hqt unify_measurement script for synapse1.15

optimum/habana/checkpoint_utils.py
:warning: **Do not merge this PR before Habana DeepSpeed 1.15 is released** :warning: 
The [TinyLlama model](https://huggingface.co/TinyLlama/TinyLlama-1.1B-Chat-v1.0) only has checkpoints in the form of `model.safetensors`. This checkpoint needs to be included in the list of checkpoints that is passed to DeepSpeed in order for the model to function properly when initialized with DeepSpeed.
This PR adds the safetensor checkpoints to the list of checkpoints passed to DeepSpeed.
**Note**: This change requires an [upstream commit in microsoft/DeepSpeed](https://github.com/microsoft/DeepSpeed/commit/c8c57b8c24ad761267ab43b0252fb62f0c30d289) to be merged downstream to HabanaAI/DeepSpeed in order for DeepSpeed to support the provided safetensor format.
=> add support for TinyLlama model

examples/language-modeling/README.md
This corrects the command for FSDP
=> Update README for FSDP

tests/baselines/llama_7b.json, tests/test_examples.py
=> Add Llama7b FSDP test for torch.compile mode

tests/test_diffusers.py
Enables saving of output images in Stable Diffusion CI test for offline analysis.
=> Save CI test output image

tests/test_trainer.py
Safe loading tests in CI are turned off because they fail with SynapseAI v1.15.
=> Disable safe loading tests in CI

optimum/habana/transformers/models/mistral/modeling_mistral.py
After this commit: https://github.com/huggingface/optimum-habana/pull/831
`allocate_kv_cache` has 1 less argument
This was fixed for llama but not for mistral: https://github.com/huggingface/optimum-habana/blob/main/optimum/habana/transformers/models/llama/modeling_llama.py#L823
=> sarkar/Fix mistral after syn1.15 update

optimum/habana/transformers/generation/utils.py, optimum/habana/transformers/models/llama/modeling_llama.py
Mark step helping in reducing workspace memory by approx twice of (BS,seq len, hidden dim).
Inplace add helping in reducing persistent tensors by approx twice of (BS, seq len, hidden dim).
Add lazy mode parameter.
---------
=> Add mark step and inplace residual add in llama model code

optimum/habana/transformers/generation/utils.py
Currently, bucket_size is only supported for a few models such as llama and falcon. This PR is to add bucket_size support for gpt_bigcode model , this can be useful if the dataset has varying prompt lengths.
=> Add --bucket_size support for gpt_bigcode #111

examples/text-generation/utils.py, optimum/habana/accelerate/utils/dataclasses.py, tests/test_fsdp_examples.py
The new backend has been introduced to pytorch-integraton - HPU_BACKEND . The deprecated backend ( AOT_HPU_TRAINING_BACKEND ) shall no longer be available in optimum habana as it's going to be removed from pytorch-integration.
=> Remove deprecated AOT_HPU_TRAINING_BACKEND (#138)

tests/baselines/clip_roberta.json
Enables data loading via mediapipe.
Updates Gaudi2 baseline numbers.
=> Enable clip mediapipe and update G2 baseline

examples/language-modeling/requirements.txt, examples/language-modeling/run_lora_clm.py, examples/text-generation/utils.py, optimum/habana/peft/__init__.py, optimum/habana/peft/layer.py, optimum/habana/transformers/trainer.py
=> add ia3 and adalora support

examples/summarization/ds_flan_t5_z3_config_bf16.json, tests/test_trainer.py
Upto 7% performance drop observed in flan-t5 8x summarization task with deepspeed-fork (synapse 1.16 version).
This PR fixes that.
=> fix perf drop in flan-t5 summarization

examples/text-generation/run_lm_eval.py
examples/text-generation/run_lm_eval.py didn't work with torch.compile mode. Adding nograd() to HabanaModelAdapter prevents backward backend.
=> Add nograd() to prevent backward backend

optimum/habana/transformers/modeling_utils.py, tests/transformers/tests/generation/test_utils.py
* Monkeypatches the `assisted_decoding` method of `transformers.generation.GenerationMixin`. The default transformers implementation of `assisted_decoding` is not compatible with `optimum-habana`. The patched version raises `NotImplementedError` which is more appropriate.
* Skips `test_assisted_decoding` tests, which would now fail with `NotImplementedError` instead of the previous: `E ValueError: `max_new_tokens` must be greater than 0, but is -1.`
=> Assisted decoding not implemented

tests/transformers/tests/models/wav2vec2/test_modeling_wav2vec2.py
Disable wav2vec2 symbolic tracing test
Disables testing of symbolic tracing for the Wav2Vec2 class of models. These tests are currently broken:
```
torch.fx.proxy.TraceError: symbolically traced variables cannot be used as inputs to control flow
```
Presumably this error is caused by the following line in the wav2vec2 implementation, which cannot be evaluated during symbolic tracing:
```
File "/usr/local/lib/python3.10/dist-packages/transformers/models/wav2vec2/modeling_wav2vec2.py", line 594, in forward
if attn_weights.size() != (bsz * self.num_heads, tgt_len, src_len):
```
The error can be reproduced with the following code snippet, which demonstrates that a similar issue is present in transformers without optimum-habana:
```python
from transformers import Wav2Vec2Model, Wav2Vec2Config …
```
=> Disable wav2vec2 symbolic tracing test

optimum/habana/transformers/generation/utils.py
REF: https://github.com/HabanaAI/optimum-habana-fork/pull/84
Extend function #24 to sample mode.
The command to reproduce performance is as follows:
`python ../gaudi_spawn.py --use_deepspeed --world_size 4 run_generation.py --model_name_or_path meta-llama/Llama-2-70b-hf --use_hpu_graphs --use_kv_cache --max_input_tokens 128 --max_new_tokens 2048 --batch_size 240 --attn_softmax_bf16  --trim_logits --bf16 --reuse_cache --warmup 1 --n_iterations 1 --limit_hpu_graphs --do_sample --bucket_size 256 --bucket_internal`
=> extend bucket_internal to SAMPLE generation mode

tests/transformers/tests/models/wav2vec2/test_modeling_wav2vec2.py
resolve runtime error for PYTEST- wav2vec test_model_for_pretraining
=> Fix AttributeError for wav2vec test

optimum/habana/transformers/trainer.py
Fixes https://github.com/huggingface/optimum-habana/issues/933
=> Grad norm tensor fix

README.md
cc @mfuntowicz after discussing this during the bi-weekly, not sure if this should be added to `optimum-intel` instead (not sure that make sense as resulting models won't be compatible with the leaderboard but we could mention `optimum-habana` and add the link for example https://github.com/huggingface/optimum-intel/pull/699)
Feel free to close @regisss
=> Add leaderboard link

examples/language-modeling/run_lora_clm.py
This PR fixes an issue when running `--help` on the `run_lora_clm.py` example file to see the args. It was giving the following error:
```
File "/tmp/dmsuehir/optimum-habana/examples/language-modeling/run_lora_clm.py", line 759, in <module>
main()
File "/tmp/dmsuehir/optimum-habana/examples/language-modeling/run_lora_clm.py", line 346, in main
) = parser.parse_args_into_dataclasses()
File "/usr/local/lib/python3.10/dist-packages/transformers/hf_argparser.py", line 331, in parse_args_into_dataclasses
namespace, remaining_args = self.parse_known_args(args=args)
File "/usr/lib/python3.10/argparse.py", line 1878, in parse_known_args
namespace, args = self._parse_known_args(args, namespace)
File "/usr/lib/python3.10/argparse.py", line 2091, in …
```
=> Fix formatting of arg parse help strings in the PEFT example

tests/utils.py
update llama and falcon CI tests to use new Habana gaudi configs rather than gpt2 config
=> use new Habana llama and falcon model configs

tests/transformers/tests/generation/test_configuration_utils.py
Update tests that used to throw warnings and now are `ValueError`
Tests were out-of-date. Check transformers tests [here](https://github.com/huggingface/transformers/blob/91d155ea92da372b319a79dd4eef69533ee15170/tests/generation/test_configuration_utils.py#L183)
=> Update test generation config to raise `ValueError`

examples/text-generation/run_generation.py, examples/text-generation/utils.py
Add `--trust_remote_code` argument for text generation examples to allow the custom models defined on the Hub in their own modeling files.
=> add `--trust_remote_code` for text generation examples

tests/clip_coco_utils.py, tests/test_diffusers.py
Replaces existing inconsistent method of Stable Diffusion Model's output images verification by a more consistent quantitative CLIP score. 
Refer here for more details on implementation:
https://huggingface.co/docs/diffusers/conceptual/evaluation#text-guided-image-generation
=> Upgrade SD output image verification with CLIP score

optimum/habana/transformers/models/mixtral/modeling_mixtral.py
When enabling finetune for Mixtral-7x8b, the train_loss is totally wrong when running with deepspeed on 8 cards. We found these all_gather code were hard coded in the model code, it lead to training totally wrong.
=> fix wrongly all_gather for mixtral finetune

optimum/habana/transformers/trainer.py
We have a condition check if the grad_norm tensor is a single element or not. If it's not we convert grad_norm as list.
(https://github.com/huggingface/optimum-habana/pull/938)
But for logging, we don't use grad_norm if it's a list so there's no point to get grad_norm list.
I changed condition to check if grad_norm is a list just assign None.
We see that this list conversion causes a perf issue.
=> Assign grad_norm for logging only if it's a single element tensor

examples/trl/requirements.txt
Upgrading the TRL version to the latest fixes the import issue seen when running TRL related CI tests on new transformer.
=> Fix for ImportError: cannot import name 'top_k_top_p_filtering'

examples/audio-classification/README.md, examples/contrastive-image-text/README.md, examples/image-classification/README.md, examples/language-modeling/README.md, examples/protein-folding/README.md, examples/question-answering/README.md, examples/speech-recognition/README.md, examples/summarization/README.md, examples/text-classification/README.md, examples/text-to-speech/README.md, examples/translation/README.md, examples/trl/README.md
=> fea(examples): Updated the READMEs with requirements.txt installation

optimum/habana/transformers/models/mixtral/modeling_mixtral.py
Fixed  'MixtralConfig' object has no attribute 'rope_scaling' while mistralai/Mixtral-8x7B-v0.1 training with examples/language-modeling/run_clm.py.
optimum-habana will crash with "AttributeError: 'MixtralConfig' object has no attribute 'rope_scaling'"
Below is the command line:
```
DEEPSPEED_HPU_ZERO3_SYNC_MARK_STEP_REQUIRED=1 python ../gaudi_spawn.py --world_size 8 --use_deepspeed \
run_clm.py --model_name_or_path mistralai/Mixtral-8x7B-v0.1 \
--dataset_name wikitext --dataset_config_name wikitext-2-raw-v1 \
--per_device_train_batch_size 1 --per_device_eval_batch_size 1 --do_train --do_eval \
--learning_rate 4e-4 --output_dir ./test-clm_streaming --gaudi_config_name Habana/gpt2 \
--use_habana --use_lazy_mode --use_cache False --throughput_warmup_steps 3 --max_steps 2 \ …
```
=> Fixed  'MixtralConfig' object has no attribute 'rope_scaling'

tests/transformers/tests/models/wav2vec2/test_modeling_wav2vec2.py
It fixes the ```test_modeling_wav2vec2.py::test_load_attn_adapter``` bypassing a problem of how we save the `adapter_weights` and load them in the test.
When we try to do `model.load_adapter` in the following code
```python
import os
import tempfile
import torch
from transformers import Wav2Vec2ForCTC
from transformers.models.wav2vec2.modeling_wav2vec2 import WAV2VEC2_ADAPTER_PT_FILE
model = Wav2Vec2ForCTC.from_pretrained("hf-internal-testing/tiny-random-wav2vec2", adapter_attn_dim=16)
with tempfile.TemporaryDirectory() as tempdir:
model.save_pretrained(tempdir)
model = Wav2Vec2ForCTC.from_pretrained(tempdir)
adapter_weights = model._get_adapters()
pt_filepath = os.path.join(tempdir, WAV2VEC2_ADAPTER_PT_FILE.format("eng"))
torch.save(adapter_weights, pt_filepath) …
```
=> Fix wav2vec test load adapter

examples/text-generation/README.md, examples/text-generation/utils.py, tests/test_text_generation_example.py
* Mark only scales as const
* remove --fp8 flag usage from llama
* removed usage of ENABLE_CONST_MARKING
Change-Id: I6dba8691d842fc62d09da5202ea1e61a111f5f18
---------
=> Mark scale as const and remove --fp8 flag usage 

optimum/habana/transformers/generation/stopping_criteria.py, tests/transformers/tests/generation/test_stopping_criteria.py
Update tests for Transformers v4.40.
- New test function: `test_eos_token_criteria`
Fixes `generation/stopping_criteria.py`:
- `needs_tensor_output` wasn't returning `False` in the `else`.
- Remove the need of `out_type_tensor` in the `gaudi_StoppingCriteriaList_call`. The output of each stopping criteria and the final output needs to be consistent.
=> Update test stopping criteria 4.40

tests/transformers/tests/generation/test_logits_process.py
- Updates `LogitsProcessorTest` to match tests from `transformer == 4.40.0`
- Adds a test to check if the expected output device is HPU 
Aside from new tests, the only issue was related to using different `torch_device`s. The solution here was to import the `torch_device` from `test_modeling_common` which uses the HPU.
=> Update test logins processor to transformers 4.40

tests/transformers/tests/models/falcon/test_modeling_falcon.py, tests/transformers/tests/models/gpt2/test_modeling_gpt2.py, tests/transformers/tests/models/gpt_neox/test_modeling_gpt_neox.py
https://github.com/huggingface/optimum-habana/blob/transformers_4.40/optimum/habana/transformers/generation/utils.py#L420
this line was added:
```
if not ignore_eos and generation_config.eos_token_id is not None:
criteria.append(EosTokenCriteria(eos_token_id=generation_config.eos_token_id))
```
in some tests `model.generate()` is called without ignore_eos set
`ignore_eos` is None i think, which means this `not ignore_eos` becomes true, which means `EosTokenCriteria` stopping criteria is added, causing tests to fail.
=> sasarkar/Add ignore_eos=True for some tests

optimum/habana/transformers/generation/utils.py
#1019 added the import `import habana_frameworks.torch.hpu as torch_hpu` at the top of `optimum/habana/transformers/generation/utils.py`. This makes the text-generation example use DeepSpeed even for 1x commands, for instance:
```
python run_generation.py --model_name_or_path mistralai/Mistral-7B-v0.3 --use_hpu_graphs --use_kv_cache --limit_hpu_graphs --bucket_size 128 --max_new_tokens 128 --batch_size 1 --bf16
```
Also, env variables like `PT_HPU_ENABLE_LAZY_COLLECTIVES` seem to be set before they are set in the example, leading to an error. For example with OPT:
```
GAUDI2_CI=1 pytest tests/test_text_generation_example.py -k "opt"
```
leading to
```
RuntimeError: collective nonSFG is not supported during hpu graph capturing
```
The `__init__.py` of `habana_frameworks.torch` imports …
=> Fix text-generation example

tests/transformers/tests/generation/test_beam_search.py
- Adapt tests to HPU and 
- It makes sure that both tensors in the following operation
```
input_ids[:, :fulfill_len] = fulfilling_sequence
```
are in the same device, otherwise we have an unexpected behavior.
=> updates test_beam_search to transformers_4.40

examples/text-generation/run_lm_eval.py
Fix a minor issue caused by initialize_model in utils.py 
In https://github.com/huggingface/optimum-habana/blob/306981885de235a5be0c52ac07682d22f0c17bd7/examples/text-generation/run_lm_eval.py#L152 three values are expected, but the function after PR https://github.com/huggingface/optimum-habana/pull/973 returns four values of `model, assistant_model, tokenizer, generation_config` 
Fixes a `ValueError` issue
=> Fix a return value issue casued by PR 973

examples/language-modeling/README.md, tests/test_fsdp_examples.py
Updating Readme to  indicate flash attention support for LLama2 70b with FSDP. This improves performance as well as memory footprint
=> Readme Update for FSDP

examples/text-generation/run_generation.py, examples/text-generation/text-generation-pipeline/pipeline.py, optimum/habana/transformers/generation/utils.py, optimum/habana/transformers/training_args.py, optimum/habana/utils.py
1. Add option profiling_record_shapes in run_generation (default False) - reducing profiling files size
2. Remove option with_stack in profiler - reducing profiling files size
=> No shapes in profilings by default (#233)

examples/question-answering/README.md
Update README with instructions for running Albert-xxlarge model in torch.compile mode.
=> Update README for Albert torch.compile mode

examples/text-generation/requirements_lm_eval.txt
* Fix lm_evaluation_harness to specific commit
* Different commit in requirements_lm_eval
Why this change?
1. We should have fixed reference instead of branch which could change in the future
2. By fixing to specific commit hash we make pip download requirements.txt a lot faster
=> Fix lm_evaluation_harness to specific commit (#240)

examples/stable-diffusion/training/README.md, examples/stable-diffusion/training/train_text_to_image_sdxl.py, tests/test_diffusers.py
Mirrors the changes here https://github.com/huggingface/diffusers/commit/8edaf3b79c564a56fbffb003ee74ac92e9162a73
@regisss  @dsocek  @libinta 
Hi team, 
Opening this PR to fix up some SDXL issues related to gated dataset. Tests are completed and provided in below. 
gated dataset for sdxl training 
```bash
------------------------------------------------------------------------------
{'attention_type', 'reverse_transformer_layers_per_block', 'dropout'} was not found in config. Values will be initialized to default values.
Repo card metadata block was not found. Setting CardData to empty.
06/04/2024 15:04:42 - WARNING - huggingface_hub.repocard - Repo card metadata block was not found. Setting CardData to empty.
Map: …
```
=> sdxl-trainig: fixed ci, changed gated dataset, fixes for non-square datasets

optimum/habana/transformers/generation/utils.py
Move the 1st token finish time to not include 2nd step kv pad time.
=> Fix 1st token latency time

optimum/habana/transformers/models/starcoder2/modeling_starcoder2.py
1. starcoder2 has accuracy issue when kv_cache is used and max_input_token is specified, such as with this command:
python run_generation.py --model_name_or_path bigcode/starcoder2-3b --batch_size 1 --use_hpu_graphs --use_kv_cache --max_new_tokens 100 --bf16 --prompt "def print_hello_world():" --max_input_tokens 1024
This PR is used to fix the accuracy issue.
2. Use fused RoPE to optimize the performance on Gaudi
=> Fix starcoder2 accuracy issue and optimize performance with fused rope

examples/language-modeling/README.md, tests/baselines/llama_7b.json, tests/test_examples.py
Adding example test case for the combination of Llama2-7B + MPI + LoRA + FP8 precision
=> Add a test for llama finetuning with FP8 precision

optimum/habana/transformers/models/llama/configuration_llama.py, optimum/habana/transformers/models/llama/modeling_llama.py
Support for fused_qkv in llama.
fused_qkv is single linear for all 3 q,k and v proj instead of separate linears.
Add "fused_qkv": true to config.json of model file to enable.
=> Adding fused qkv support along with config

examples/language-modeling/README.md, optimum/habana/accelerate/accelerator.py, optimum/habana/accelerate/utils/__init__.py, optimum/habana/accelerate/utils/dataclasses.py, optimum/habana/accelerate/utils/transformer_engine.py, optimum/habana/peft/layer.py, optimum/habana/transformers/trainer.py, optimum/habana/transformers/training_args.py
Refactoring `transformer_engine` FP8 support in optimum-habana. This removes model specific changes and makes the code more model agnostic.
=> TE FP8 integration

examples/text-generation/utils.py
torch.compile keep input mutation in graph this avoids unnecessary memcpy coming from inplace index_copy from kv cache
=> torch.compile keep input mutation in graph this avoids unnecessary memcpy

optimum/habana/transformers/generation/utils.py
**TL;DR**
Fix recompiles if limit_hpu_graph is False
**Details**
If `--limit_hpu_graphs` is set to False, there are multiple recompilations, causing low thruput.
The reason for recompilations is:
for 1st prefill, input = prompt of len “p” goes in, and kv cache of size “p” comes out, and that is padded by “m” to give size = p+m
for second prefill (during second warmup), inp = p goes in, but output is p+m (should have been just p).. which is padded by m again, and then becomes p+m+m etc
This is probably because this clearing code isnt invoked when limit_hpu_graph=False: [optimum-habana/optimum/habana/transformers/generation/utils.py at main · huggingface/optimum-habana](https://github.com/huggingface/optimum-habana/blob/main/optimum/habana/transformers/generation/utils.py#L1888)
A possible …
=> sasarkar/Fix recompiles if limit_hpu_graph is False

tests/baselines/llama_7b.json, tests/test_examples.py
The CausalLanguageModelingLORAExampleTester using "databricks/databricks-dolly-15k" only has a baseline defined for llama-7b with Gaudi2. The test was incorrectly trying to run in other use cases causing a key error:
1. The test was trying to run with falcon-40b and with llama-7b with Gaudi 1. 
```
RUN_SLOW=true python -m pytest tests/test_examples.py::CausalLanguageModelingLORAExampleTester::test_run_lora_clm_falcon-40b_single_card
...
FAILED tests/test_examples.py::CausalLanguageModelingLORAExampleTester::test_run_lora_clm_falcon-40b_single_card - KeyError: 'databricks/databricks-dolly-15k'
```
2. The test was trying to run with llama-7b with Gaudi 1
```
GAUDI2_CI=0 RUN_SLOW=true python -m pytest tests/test_examples.py::CausalLanguageModelingLORAExampleTester::test_run_lora_clm_llama-7b_ …
```
=> Fix test CausalLanguageModelingLORAExampleTester KeyError

Makefile, README.md, docs/source/index.mdx, examples/object-detection/README.md, examples/object-detection/run_example.py, optimum/habana/transformers/modeling_utils.py, optimum/habana/transformers/models/__init__.py, optimum/habana/transformers/models/detr/__init__.py, optimum/habana/transformers/models/detr/modeling_detr.py, setup.py, tests/test_object_detection.py
This PR contains the patch, example, and test codes for DETR models.
A100 CUDA BF16(Autocast) benchmarks:
n_iterations: 10
Total latency (ms): 241.29199981689453
Average latency (ms): 24.129199981689453
Gaudi2 BF16(Autocast and Graph mode) benchmarks: 
n_iterations: 10
Total latency (ms): 65.3073787689209
Average latency (ms): 6.53073787689209
- [N.A.] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [Yes] Did you make sure to update the documentation with your changes?
- [Yes] Did you write any new necessary tests?
=> Enabled DETR (Object Detection) model

optimum/habana/transformers/models/mpt/modeling_mpt.py
Adds support for `--bucket_internal` for MPT model.
Measurements:
| Param                                  | In/Out tokens | Bath size | Throughput t/s |  Memory allocated |
|-------------------------------|----------------|------------|----------------|-------------------|
| `--bucket_internal`               | 128/128         | 128           | 6019.4            | 37.04 GB           |
| **NO** `--bucket_internal`   | 128/128         | 128           | 2919.8           | 37.28 GB           |
| `--bucket_internal`               | 128/256         | 64             | 4268.5           | 31.28 GB           |
| **NO** `--bucket_internal`   | 128/256         | 64            | 3265.1           | 37.03 GB          |
| `--bucket_internal`               | 128/512         | 32             | 2529.7 …
=> Support `bucket_internal` for MPT

optimum/habana/transformers/models/gpt_bigcode/modeling_gpt_bigcode.py, tests/test_text_generation_example.py
Added support of following options to gpt_bigcode (starcoderbase) model use_flash_attention,
flash_attention_recompute,
flash_attention_fast_softmax,
flash_attention_causal_mask
=> gpt_bigcode: added FusedSDPA kernel

examples/text-generation/README.md, examples/text-generation/run_generation.py, examples/text-generation/utils.py, optimum/habana/distributed/__init__.py, optimum/habana/distributed/serialization.py, optimum/habana/distributed/strategy.py, optimum/habana/distributed/tensorparallel.py, optimum/habana/distributed/tp.py, optimum/habana/distributed/tp_wrapping.py, optimum/habana/transformers/models/llama/configuration_llama.py, optimum/habana/transformers/models/llama/modeling_llama.py, tests/test_text_generation_example.py
Tensor parallel by extending GaudiLlamaAttention -> TPGaudiLlamaAttention and GaudiLlamaMLP -> TPGaudiLlamaMLP
use parameter --distributed_strategy="tp" to invoke this code path
code design reference: https://github.com/foundation-model-stack/foundation-model-stack/tree/main
=> Tensor parallel distributed strategy without using deepspeed

optimum/habana/transformers/models/mpt/modeling_mpt.py
Modified the kv_cache initialization method and optimized performance.
Co-author:  @atakaha 
Test command:
```bash
python run_generation.py --model_name_or_path mosaicml/mpt-7b --use_hpu_graphs --use_kv_cache --limit_hpu_graph --batch_size 128  --max_input_tokens 128 --max_new_tokens 128 --trim_logits --attn_softmax_bf16 --warmup 3 --n_iterations 1 --bf16
```
Result:
|Version|batchsize|max input tokens|max new tokens|Throughput (including tokenization)(tokens/s)|Memory allocated(GB)|Max memory allocated(GB)|
|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
|before|128|128|128|2900|37.28|64.39|
|after|128|128|128|4803|29.28|48.39|
|before|16|128|1024|624|26.55|41.79|
|after|16|128|1024|1215|23.04|33.77|
|before|2|1024|1024|197|16.27|19.66|
|after|2|1024|1024|255|15.27|17.66| …
=> refine use cache for mpt model

examples/text-generation/run_lm_eval.py, optimum/habana/transformers/generation/utils.py, optimum/habana/transformers/modeling_utils.py, optimum/habana/transformers/models/__init__.py, optimum/habana/transformers/models/gptj/__init__.py, optimum/habana/transformers/models/gptj/modeling_gptj.py, tests/test_text_generation_example.py
=> GPT-J support reuse_cache

examples/stable-diffusion/README.md, optimum/habana/diffusers/pipelines/controlnet/pipeline_controlnet.py, optimum/habana/diffusers/pipelines/stable_video_diffusion/pipeline_stable_video_diffusion.py, setup.py, tests/test_diffusers.py
* Updated optimum-habana diffusers to 0.29.2 in `setup.py`
* Fixed SVD (GaudiStableVideoDiffusionPipeline) to handle updated API in 0.29.2 for `tensor2vid` and instead use `video_processor.postprocess_video`
* Fixed GaudiStableDiffusionControlNetPipeline to handle updated `check_inputs` API in 0.29.2
* Fixed `tests/test_diffusers.py` to use `to(dtype=...)` instead of `to(torch_dtype=...)` which is deprecated starting diffusers 0.27.0 (See [here](https://github.com/huggingface/diffusers/blob/v0.26.3/src/diffusers/pipelines/pipeline_utils.py#L781))
* Clean-up SVD to remove all inheritable functions
* Updated warmup logic in SVD
* Updated documentation example with command line for SVD that yields improved performance
Ran tests on G2:
```bash
export RUN_SLOW=true
export GAUDI2_CI=1
make …
```
=> Upgrade optimum-habana diffusers dependency from 0.26.3 to 0.29.2

optimum/habana/transformers/models/llama/modeling_llama.py
use fast softmax only on prefill
=> use fast softmax only on prefill

optimum/habana/transformers/models/llama/modeling_llama.py
max_position_embedding value was passed through as an argument on the 4.40.2, and initialized correctly but this is no longer happening since tf4.43 code is changed. We still use old architecture for this RotaryEmbedding, so the valuehas to be initialized before cos/sin cache updated. I am setting this up in RotaryEmbedding itself by reading it from config. 
https://github.com/huggingface/transformers/blob/v4.43.2/src/transformers/models/llama/modeling_llama.py#L306  vs 
https://github.com/huggingface/transformers/blob/v4.40.2/src/transformers/models/llama/modeling_llama.py#L295
Without above change, crash was seen on transformer 4.43 branch for llama when the max_new_token is bigger than 2048.
=> Fix max_position_embedding init for tf4.43 upgrade

tests/transformers/tests/models/llama/test_modeling_llama.py
To resolve "AttributeError: 'LlamaConfig' object has no attribute 'parallel_strategy'" from test "GAUDI2_CI=1 RUN_SLOW=1 python -m pytest tests/transformers/tests/models/llama/test_modeling_llama.py -v -s".
* changes from : https://github.com/HabanaAI/optimum-habana-fork/pull/272
=> Fix LlamaConfig attr errors during test

optimum/habana/transformers/models/llama/modeling_llama.py
This reverts commit 55f9b0ce39a4f01978077e601e031a6acc2d5609.
This commits fixes llama, but cause failure on Mixtral. 
New pull request(#1205) fix for both models.
=> Revert "Fix max_position_embedding init for tf4.43 upgrade (#1202)"

tests/transformers/tests/models/wav2vec2/test_modeling_wav2vec2.py
Part of the previous PR: https://github.com/huggingface/optimum-habana/pull/937/files 
```
GAUDI2_CI=1 RUN_SLOW=1 python -m pytest tests/transformers/tests/models/wav2vec2/test_modeling_wav2vec2.py -s -v -k test_load_attn_adapter
```
```
=========================================================================================== 1 passed, 156 deselected, 5 warnings in 16.37s ============================================================================================
```
=> fea(937): fixes related to OSError

examples/language-modeling/peft_poly_seq2seq_with_generate.py, examples/language-modeling/run_multitask_prompt_tuning.py
This PR addresses issues after upgrading the peft from `0.10.0` -> `0.12.0`
The second issue is resolved by yi.a.wang@intel.com
To test,
```sh
export RUN_SLOW=true
export GAUDI2_CI=1
python -m pytest tests/test_examples.py -v -s -k test_run_multitask_prompt_tuning_t5-small_multi_card
python -m pytest tests/test_examples.py -v -s -k test_peft_poly_seq2seq_with_generate_t5-small_multi_card
```
- In the recent version peft > 0.10.0, https://github.com/huggingface/peft/blob/e6cd24c907565040ee1766a5735afe3d13a71164/src/peft/mapping.py#L133, getting a Peft model object from a model and a config, cast adapter weights using float16 or bfloat16 to float32. This causes an issue. This PR is workaround for this issue.
- The second issue is copying the original model to avoid reusing …
=> T5 multi card

tests/baselines/flan_t5_xxl.json, tests/baselines/gpt2_xl.json, tests/baselines/gpt_neox_20b.json, tests/baselines/roberta_base.json, tests/baselines/roberta_large.json, tests/test_image_to_text_example.py
- Fixes the failed tests on flan-t5, img2txt, gpt and reberta. 
- For flan-t5, the increased steps adds about ~1min to total runtime. 
- All tests have succeeded locally (below)
`gpt-neox`
```
[2024-08-07 19:24:21,431] [INFO] [launch.py:348:main] Process 588 exits successfully.
[2024-08-07 19:24:23,434] [INFO] [launch.py:348:main] Process 587 exits successfully.
[2024-08-07 19:24:24,435] [INFO] [launch.py:348:main] Process 589 exits successfully.
[2024-08-07 19:24:24,436] [INFO] [launch.py:348:main] Process 585 exits successfully.
[2024-08-07 19:24:25,437] [INFO] [launch.py:348:main] Process 586 exits successfully.
[2024-08-07 19:24:25,437] [INFO] [launch.py:348:main] Process 584 exits successfully.
[2024-08-07 19:24:26,439] [INFO] [launch.py:348:main] Process 591 exits …
```
=> Ig/synapse 1.17 ci fixes

examples/text-generation/README.md, examples/text-generation/run_lm_eval.py
Remove the default env variable to trust remote code by default.
This is wrong to set the env variable by default in the code. 
```py
os.environ.setdefault("HF_DATASETS_TRUST_REMOTE_CODE", "true")
```
User should set this in their env if they trust remote dataset. User can do `export HF_DATASETS_TRUST_REMOTE_CODE=true` if they trust the remote dataset.
=> Remove the default env variable to trust remote code by default

examples/language-modeling/fsdp_config.json, examples/question-answering/fsdp_config.json, optimum/habana/accelerate/accelerator.py, optimum/habana/transformers/training_args.py
- Update CPU_RAM_EFFICIENT_LOADING to take it from config
- Disable FSDP flat_param upcast
With transformer 4.43 update(Accelerator 0.33.0), FSDP functionality is broken. 
- Flag was not set correctly due to the argument update. This cause FSDP not fully enabled causing Llama70b test fail with Host OOM. 
- Upcast logic(https://github.com/huggingface/accelerate/pull/2674) has been added on the update, but this is causing FSDP graph compiler failure.
=> Fix FSDP graph error due to Tranformer 4.43 update

examples/kubernetes/docker-compose.yaml
This is a small PR fixing the default PyTorch version to match the 1.17 image: 
```
docker pull vault.habana.ai/gaudi-docker/1.17.0/ubuntu22.04/habanalabs/pytorch-installer-2.3.1:latest
```
Without this fix, trying to build the container with the default build args will give the following error:
```
=> ERROR [optimum-habana-examples internal] load metadata for vault.habana.ai/gaudi-docker/1.17.0/ubuntu22.04/habanalabs/pytorch-installer-2.2.2:latest    
```
The documentation already has the correct `TORCH_VER`: https://github.com/huggingface/optimum-habana/blob/main/examples/kubernetes/README.md?plain=1#L48
=> Fix PyTorch version in the Kubernetes docker-compose to match image

optimum/habana/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py, optimum/habana/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py, optimum/habana/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_inpaint.py
This PR fixes overflow of steps in SDXL for default diffusers scheduler for all SDXL pipelines.
In SDXL scheduler tracks steps index of timesteps.  Issue happens when we have multiple batches.  Then default scheduler from diffusers would cause error.  This fix calls init function at beginning of each batch processing thus fixing the issue.
=> Fix overflow of steps in SDXL for default diffusers scheduler

optimum/habana/transformers/models/mixtral/modeling_mixtral.py
Currently `inputs_embeds` variable is used even if its none in below condition
```
if cache_position is None:
past_seen_tokens = past_key_values.get_seq_length() if past_key_values is not None else 0
cache_position = torch.arange(
past_seen_tokens, past_seen_tokens + inputs_embeds.shape[1], device=inputs_embeds.device
)
```
This is leading to error as below in some cases.
```
File "/usr/local/lib/python3.10/dist-packages/optimum/habana/transformers/models/mixtral/modeling_mixtral.py", line 603, in forward
past_seen_tokens, past_seen_tokens + inputs_embeds.shape[1], device=inputs_embeds.device
AttributeError: 'NoneType' object has no attribute 'shape'
```
Moved code up that checks and sets for `inputs_embeds`.
=> Set input_embeds before it gets used

optimum/habana/transformers/models/mixtral/modeling_mixtral.py
Fix the crash 
```
File "/usr/local/lib/python3.10/dist-packages/optimum/habana/transformers/models/mixtral/modeling_mixtral.py", line 613, in forward
past_seen_tokens = past_key_values.get_seq_length() if past_key_values is not None else 0
AttributeError: 'list' object has no attribute 'get_seq_length'
```
=> Fix cache position issue in mixtral

examples/kubernetes/requirements.txt
huggingface_hub was being specified in the requirements.txt because optimum habana v1.12.0 was using huggingface_hub < 0.23.0, and the Kubernetes workflow required huggingface_hub 0.23.0+ in order to use `HF_TOKEN_PATH`, as explained [here](https://github.com/huggingface/optimum-habana/pull/1099#discussion_r1678440748). Since 1.13.0 is using huggingface_hub >= 0.23.2, we can remove huggingface_hub from the requirements.txt.
I tested this change by rebuilding the container, and running the kubernetes example using a gated model to verify that the `HF_TOKEN_PATH` is working.
=> Remove huggingface_hub install that is no longer needed in the kubernetes example

optimum/habana/accelerate/utils/__init__.py, optimum/habana/accelerate/utils/other.py, optimum/habana/transformers/modeling_utils.py
This PR fixes a bug where the FSDP wrapper of the model is lost at some point in Accelerate:
- Distributed wrappers (i.e. DDP, FSDP, DeepSpeed) are removed [here](https://github.com/huggingface/accelerate/blob/v0.33.0/src/accelerate/utils/other.py#L90),
- At some point after that operation is performed, the FSDP wrapper is lost, which makes the BERT FSDP test fail.
This PR fixes that issue by keeping a buffer variable to not lose track of the distributed model and making sure that it is set it back at the end.
=> Fix BERT FSDP test

examples/image-to-text/README.md, examples/image-to-text/run_pipeline.py, optimum/habana/transformers/models/clip/modeling_clip.py, optimum/habana/transformers/models/llava/modeling_llava.py, optimum/habana/transformers/models/llava_next/modeling_llava_next.py
Added '--flash_attention_recompute' for llava and llava-next models to provide an option to enable disable recompute
=> Llava: Added flash_attention_recompute arg to provide an option to enable/disable recompute

.github/workflows/check_code_quality.yml, .github/workflows/failed_code_quality_check_comment.yml
The workflow used for posting a comment when the code quality check failed is currently a `workflow_call`, which doesn't have more permissions than the caller workflow (i.e. `pull_request`) and thus cannot post a comment in a PR from a fork.
This PR updates this workflow switching to `workflow_run` to fix that.
=> Switch failed code quality check comment to `workflow_run`

optimum/habana/transformers/models/llama/modeling_llama.py
While using Flash Attention with Llama2 7B it was found that graph break is happening which causes poor perf.
The graph break happens due to 1) isinstance() and 2) applying a boolean condition with the class instance.
isinstance() is fixed by PR: #330.
This PR fixes applying the boolean condition.
Complete details can be found here: SW-192950
=> [SW-198030]: Prevent Graph break in Llama when using flash attention

optimum/habana/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py, optimum/habana/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py, optimum/habana/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_inpaint.py
In current code, we are not setting the starting timestep for Euler type schedulers (e.g. `EulerDiscreteScheduler`, `GaudiEulerDiscreteScheduler`, etc).  Consequently, this value is `None` which causes slower timesteps reset process (e.g. in multiple batches scenarios for Euler schedulers).  When initial value is set to `0` then reset is performed as simple index switch (faster). (For example, this can be seen [here](https://github.com/huggingface/diffusers/blob/v0.30.0/src/diffusers/schedulers/scheduling_euler_discrete.py#L486-L491))
This PR fixes the aforementioned issue.  This gives notable speed boost in SDXL pipeline for both `default` and `euler_discrete` scheduler selections when processing multiple batches.
Ran the following command before and after the fix:
```bash
python …
```
=> Boost SDXL speed with initialized schedule step reset

optimum/habana/transformers/models/llama/modeling_llama.py
Transformer 4.43 has moved to use new Cache mechanism(https://github.com/huggingface/transformers/pull/31898) , and removed _reorder_cache from llama code while HPU is still using the previous mechanism.  Adding back _reorder_cache to the HPU llama code. 
Without this PR, below test case is failing. 
RUN_SLOW=true  GAUDI2_CI=1 python -m pytest tests/transformers/tests/models/llama/test_modeling_llama.py -v -s -k test_beam_search_generate
=> Add _reorder_cache back to Llama for HPU

examples/language-modeling/run_lora_clm.py
Fixes the failing test : 
**tests.test_examples.MultiCardCausalLanguageModelingLORAExampleTester2 | test_run_lora_clm_falcon-40b_multi_card**
[rank0]: Traceback (most recent call last):
[rank0]:   File "/root/optimum-habana/examples/language-modeling/run_lora_clm.py", line 930, in <module>
[rank0]:     main()
[rank0]:   File "/root/optimum-habana/examples/language-modeling/run_lora_clm.py", line 756, in main
[rank0]:     tokenized_datasets = raw_datasets.map(
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/datasets/dataset_dict.py", line 866, in map
[rank0]:     {
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/datasets/dataset_dict.py", line 867, in <dictcomp>
[rank0]:     k: dataset.map(
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/datasets/arrow_dataset.py" …
=> Fixes the no attribute error with the falcon multicard test

optimum/habana/transformers/generation/utils.py, optimum/habana/transformers/models/blip/modeling_blip_text.py, optimum/habana/transformers/models/bloom/modeling_bloom.py, optimum/habana/transformers/models/codegen/modeling_codegen.py, optimum/habana/transformers/models/decilm/modeling_decilm.py, optimum/habana/transformers/models/falcon/modeling_falcon.py, optimum/habana/transformers/models/gemma/modeling_gemma.py, optimum/habana/transformers/models/gpt2/modeling_gpt2.py, optimum/habana/transformers/models/gpt_bigcode/modeling_gpt_bigcode.py, optimum/habana/transformers/models/gpt_neox/modeling_gpt_neox.py, optimum/habana/transformers/models/gptj/modeling_gptj.py, optimum/habana/transformers/models/llama/modeling_llama.py, optimum/habana/transformers/models/mamba/modeling_mamba.py, optimum/habana/transformers/models/mistral/modeling_mistral.py, optimum/habana/transformers/models/mixtral/modeling_mixtral.py, optimum/habana/transformers/models/mpt/modeling_mpt.py, optimum/habana/transformers/models/opt/modeling_opt.py, optimum/habana/transformers/models/persimmon/modeling_persimmon.py, optimum/habana/transformers/models/phi/modeling_phi.py, optimum/habana/transformers/models/qwen2/modeling_qwen2.py, optimum/habana/transformers/models/stablelm/modeling_stablelm.py, optimum/habana/transformers/models/starcoder2/modeling_starcoder2.py, optimum/habana/transformers/models/t5/modeling_t5.py, tests/transformers/tests/generation/test_utils.py
Fixes issues with decoder-only generation. Multiple issues were found and corrected.
```
root@idc705326-7:/optimum-habana# GAUDI2_CI=1  RUN_SLOW=1 python -m pytest tests/transformers/tests/models/ -k test_generate_from_inputs_embeds_decoder_only
============================================================================================================== test session starts ==============================================================================================================
platform linux -- Python 3.10.12, pytest-7.4.4, pluggy-1.4.0
rootdir: /optimum-habana
configfile: setup.cfg
collected 1218 items / 1210 deselected / 8 selected
tests/transformers/tests/models/bert/test_modeling_bert.py . …
```
=> Fix decoder only generation

examples/text-generation/run_generation.py, examples/text-generation/utils.py
After PR https://github.com/huggingface/optimum-habana/pull/1231 merge graph recompilation statistics reporting is broken. Added cmd option to turn this statistics back on (off by default)
=> run_generation example: fixed graph compilation statistics reporting

examples/text-generation/run_generation.py, optimum/habana/transformers/generation/utils.py
Some multimodal generation model needs user specified embedded tokens input, for example [NExT-GPT](https://next-gpt.github.io/), this commit enable user-provided input embeddings for model generation.
1. Input Embeddings Support:
Modified transformers/generation/utils.py to include logic that supports user-provided input embeddings. This allows for more flexibility in how input data can be fed into the models.
Added the --input_embeds option in example/text-generation/run_generation.py to facilitate testing with different models using embedded tokens.
2. Testing and Performance Evaluation:
Conducted tests using the modified script on the Mistral 7B model with a batch size of 6. The tests included various input scenarios to assess the robustness and performance of the new features. …
=> Transformer models generation supports user-provided input embeddings

tests/test_diffusers.py
Opened this PR post #1284  since the `test_stable_diffusion_xl_img2img_euler` keeps crashing: https://github.com/huggingface/optimum-habana/actions/runs/10820064759/job/30019296923
> Note: the upstream code has a different expected values: https://github.com/huggingface/diffusers/blob/8336405e50e204fad3601e8350e04e6daa838eb4/tests/pipelines/stable_diffusion_xl/test_stable_diffusion_xl_img2img.py#L219
=> fix(pr1284-ci): fixed the expected values after for img2img slice

examples/language-modeling/README.md
modifications to gpt-neox-20b documentation recommendation to use jemalloc instead of temalloc for this model execution
=> recommend jemalloc for  gpt-neox-20b 8x

optimum/habana/transformers/modeling_utils.py, optimum/habana/transformers/models/__init__.py, optimum/habana/transformers/models/gpt_bigcode/__init__.py, optimum/habana/transformers/models/gpt_bigcode/modeling_gpt_bigcode.py
- introduce GaudiGPTBigCodeAttention class
- wrapped FusedSDPA kernel to separate ModuleFusedSDPA class
=> gpt_big_code: make flash attention impl quantization friendly

optimum/habana/transformers/models/gptj/modeling_gptj.py
Transformer4.45 has the Dynamic cache updates(https://github.com/huggingface/transformers/pull/31421) removing
self.bias causing the failure. Until we investigate further  and update the code based on the new transformer, we are putting bias back to GaudiGPTJAttention.init()
`GAUDI2_CI=1  RUN_SLOW=1 python3.10 -m pytest tests/test_text_generation_example.py -k token0-EleutherAI/gpt-j-6b-1
`
```
File "/usr/local/lib/python3.10/dist-packages/optimum/habana/transformers/models/gptj/modeling_gptj.py", line 124, in _attn
causal_mask = self.bias[:, :, key_length - query_length : key_length, :key_length]
AttributeError: 'GaudiGPTJAttention' object has no attribute 'bias'
```
=> Add  bias to gptj 

optimum/habana/transformers/models/bloom/modeling_bloom.py
https://github.com/huggingface/transformers/blob/main/src/transformers/models/bloom/modeling_bloom.py#L262 _reshape() function covers OH transpose change. No need to transpose in OH.
The current code is failed at text-getneration CI.
CI run command: python3 /root/optimum-habana/examples/text-generation/run_generation.py --model_name_or_path bigscience/bloomz-7b1 --batch_size 1 --use_kv_cache --max_new_tokens 100 --use_hpu_graphs --bf16
Error message:
File "/usr/local/lib/python3.10/dist-packages/optimum/habana/transformers/models/bloom/modeling_bloom.py", line 142, in gaudi_bloom_attention_forward
query_layer = query_layer.transpose(1, 2).reshape(batch_size * self.num_heads, q_length, self.head_dim)
RuntimeError: shape '[32, 32, 128]' is invalid for input of size 438272
=> Update bloom attention forward reshape follwing the transformer change

optimum/habana/transformers/modeling_attn_mask_utils.py
when I running inference with command:
``` bash
INPUT=32768
OUTPUT=32768
BATCH_SIZE=12
python gaudi_spawn.py --use_deepspeed --world_size 8 run_generation.py \
--model_name_or_path Meta-Llama-3.1-70B-Instruct/ \
--max_input_tokens ${INPUT} \
--max_new_tokens ${OUTPUT} \
--bf16 \
--use_kv_cache \
--batch_size ${BATCH_SIZE} \
--attn_softmax_bf16 \
--limit_hpu_graphs \
--trim_logits \
--flash_attention_causal_mask \
--flash_attention_recompute \
--warmup 1 \
--n_iteration 1 \
--bucket_internal \
--bucket_size=512 \
--use_flash_attention
```
it will OOM, while not OOM if `BATCH_SIZE=11`
after I debugged by using memory analysis tool, I found that the first time of creating causal attention mask tensor need too much device memory, that lead to device memory exhaustion. …
=> fix OOM when inference with llama-3.1-70b

examples/image-to-text/run_pipeline.py
This PR fix a conditional issue.
Fixes a minor issue
```sh
>>> python3 run_pipeline.py     --model_name_or_path Salesforce/blip-image-captioning-large     --image_path "https://ankur3107.github.io/assets/images/image-captioning-example.png"     --use_hpu_graphs     --bf16 
File "/root/optimum-habana/examples/image-to-text/run_pipeline.py", line 178, in main    args.prompt = processor.apply_chat_template(conversation, add_generation_prompt=True)UnboundLocalError: local variable 'processor' referenced before assignment
```
with the fix
```sh
>>> python3 run_pipeline.py     --model_name_or_path Salesforce/blip-image-captioning-large     --image_path "https://ankur3107.github.io/assets/images/image-captioning-example.png"     --use_hpu_graphs     --bf16 
09/25/2024 22:26:04 - INFO - __main__ …
```
=> Fix the conditional

examples/stable-diffusion/README.md
Removes repetitive ```pip install -r requirements.txt``` command from the stable-diffusion examples directory and brings it to the top as a pre-requisite, just like how it is done in the examples' READMEs.
=> Remove repetitive pip install commands

optimum/habana/transformers/models/mamba/modeling_mamba.py
attention_mask not set to none in the default case ie use_cache and token_idx not none
Runtime error seen on Transformer 4.45 future branch. 
GAUDI2_CI=1  RUN_SLOW=1 python3.10 -m pytest tests/test_text_generation_example.py  -s -v -k "mamba"
6626 RuntimeError: Reshape doesnt support change in number of elements: [1536, 1536, 110] Size of output: [2359296]
=> Fix reshape error in mamba

optimum/habana/transformers/generation/utils.py
change back value to 0 when do the padding. Before the fix, when we run `python3 run_pipeline.py  --model_name_or_path llava-hf/llava-1.5-7b-hf --use_hpu_graphs  --bf16 --use_kv_cache`, it will return wrong output:
`result = [[{'generated_text': 'USER:  \nWhat is shown in this image? ASSISTANT: The\nЪ\nЪ\nЪ\nЪ\nЪ\nЪ\nЪ\nЪ\nЪ\nЪ\nЪ\nЪ\nЪ\nЪ\nЪ\nЪ\nЪ\nЪ\nЪ\nЪ\nЪ\nЪ\nЪ\nЪ\nЪ\nЪ\nЪ\nЪ\nЪ\nЪ\nЪ\nЪ\nЪ\nЪ\nЪ\nЪ\nЪ\nЪ\nЪ\nЪ\nЪ\nЪ\nЪ\nЪ\nЪ\nЪ\nЪ\nЪ\nЪ\n'}]
]`, this PR fix it.
=> fix bug when running image-to-text example

examples/image-to-text/run_pipeline.py, tests/test_image_to_text_example.py
In case of not using use_kv_cache, the False value causes performance issue
This PR addresses a performance issue caused by setting the `use_cache` argument to `False` by default for all model classes when not passing `--use_kv_cache`. 
The `use_cache` parameter should only be set to `True` when explicitly requested, as its default setting to `False` leads to performance degradation. This PR restores the original behavior, making PR #1343 unnecessary. 
Without the fix
```sh
>>> python3 run_pipeline.py  --model_name_or_path llava-hf/llava-1.5-7b-hf  --use_hpu_graphs --bf16
09/26/2024 20:56:05 - INFO - __main__ - time = 1933.194888199796ms, Throughput (including tokenization) = 20.691136855450857 tokens/second
```
With this fix
```sh
>>> python3 run_pipeline.py  --model_name_or_path …
```
=> Only pass the use_kv_cache True to generator

optimum/habana/transformers/models/llava/modeling_llava.py
PR fixes the following tests:
```
pytest -v -s tests/test_image_to_text_example.py -k llava-1.5
```
Failure:
```
UnboundLocalError: local variable 'image_features' referenced before assignment
```
Issue comes from transformers: https://github.com/huggingface/transformers/commit/9c4639b62236b503d881c225246ad8ee61ae6ed8#diff-2204a446d82a75771bf0df20c493c6b6cdfba7a87e51767ac63aa9cf8832100aR555
`image_features` is set inside an if statement  and the tests fails as they don't enter it.
1. llava-1.5-7b-hf, BF16
```
python3 /root/synopsis/transformers_future/examples/image-to-text/run_pipeline.py --model_name_or_path llava-hf/llava-1.5-7b-hf --batch_size 1 --max_new_tokens 20 --use_hpu_graphs --bf16
09/30/2024 20:11:57 - INFO - __main__ - result = [[{'generated_text': 'USER:  \nWhat is shown in …
```
=> Fix local variable 'image_features' referenced before assignment

examples/sentence-transformers-training/README.md
This PR will add one README.md for all sentence transformer HPU examples although they have each readme on how to run for each example. This README will give the whole pictures on all examples for sentence transformer with HPU device and their supported features/test configurations as below like :
=> add README.md for Sentence transformer examples with HPU device

optimum/habana/transformers/models/mixtral/modeling_mixtral.py
fix following error from CI run
tests.transformers.tests.models.mixtral.test_modeling_mixtral.MixtralModelTest
UnboundLocalError: local variable 'attn_weights' referenced before assignment
=> fix error caused by uninitialized attn_weights

Makefile, tests/test_diffusers.py
- Top level installation i.e examples/stable-diffusion/requirements.txt done for all diffuser tests from Makefile
- test_diffusers.py now only has specific sub level requirements.txt installation
```
export GAUDI2_CI=1
make fast_tests_diffusers
== 111 passed, 47 skipped, 367 warnings in 1433.14s (0:23:53) ==
```
Fixing CI so pre-requisites are installed 
| Test | Test name | Error |
|----|-----|----|
|tests.test_diffusers.GaudiStableDiffusionXLPipelineTester | test_stable_diffusion_xl_inference_script | 1977     from compel import Compel, ReturnedEmbeddingsType 1978 ModuleNotFoundError: No module named 'compel' |
=> CI fix - Install stable-diffusion reqs

optimum/habana/transformers/models/mixtral/modeling_mixtral.py
fix following error from CI run
tests.transformers.tests.models.mixtral.test_modeling_mixtral.MixtralModelTest
UnboundLocalError: local variable 'attn_weights' referenced before assignment
=> Fix error caused by uninitialized attn_weights (#1391)

optimum/habana/transformers/models/gpt_neo/modeling_gpt_neo.py
replace flash attention flag in gpt neo since variable no longer defined in the latest transformers. Fixes the following CI test
test_text_generation_bf16_1x[token0-EleutherAI/gpt-neo-2.7B-1-False-257.2476416844122]
=> replace flash attention flag

.github/workflows/slow_tests_gaudi2.yml, tests/baselines/CodeLlama_13b_Instruct_hf.json, tests/baselines/LlamaGuard_7b.json, tests/baselines/gpt_neox_20b.json, tests/ci/slow_tests_deepspeed.sh
DeepSpeed CI slow tests are currently broken on Gaudi2 because some models are gated and a HF token is required.
The current solution
```bash
docker run ... pip install huggingface_hub && huggingface-cli login --token ${{ secrets.TEXT_GENERATION_CI_HUB_TOKEN }} && /bin/bash tests/ci/slow_tests_deepspeed.sh
```
doesn't work as only `pip install huggingface_hub` is executed inside the Docker container and `huggingface-cli login --token ${{ secrets.TEXT_GENERATION_CI_HUB_TOKEN }} && /bin/bash tests/ci/slow_tests_deepspeed.sh` are executed outside of the container.
This PR fixes that by moving all this logic to `tests/ci/slow_tests_deepspeed.sh`.
=> Fix DeepSpeed CI on Gaudi2

examples/summarization/run_summarization.py, optimum/habana/accelerate/accelerator.py, optimum/habana/transformers/trainer.py, optimum/habana/transformers/training_args.py
Added an option to enable compiled autograd for summarization for future use.
Added an option to change the value of dynamic for torch.compile in accelerator.py for debugging purposes.
=> Add misc. training args

Makefile, examples/text-generation/README.md, examples/text-generation/run_generation.py, examples/text-generation/utils.py, tests/test_text_generation_example.py
Added load options for different GPTQ checkpoints.
Modified the load params accordingly
=> Load INC GPTQ checkpoint & rename params

examples/language-modeling/run_lora_clm.py, optimum/habana/accelerate/utils/transformer_engine.py, optimum/habana/transformers/models/llama/configuration_llama.py, optimum/habana/transformers/models/llama/modeling_llama.py
Enablement of FusedSDPA (FP8) for Llama finetuning
=> Enable FusedSDPA fp8 in Llama FT

tests/transformers/tests/models/falcon/test_modeling_falcon.py, tests/transformers/tests/models/gpt2/test_modeling_gpt2.py, tests/transformers/tests/models/llama/test_modeling_llama.py, tests/transformers/tests/models/vit/test_modeling_vit.py, tests/transformers/tests/models/wav2vec2/test_modeling_wav2vec2.py
Some of the changes introduced in #1387 and #1386 are leading to pytest failures. 
This PR reverts them back. 
Added failures:
```
FAILED tests/transformers/tests/models/llama/test_modeling_llama.py::LlamaModelTest::test_torch_fx - AssertionError: Couldn't trace module: Model GaudiLlamaModel is not support...
FAILED tests/transformers/tests/models/llama/test_modeling_llama.py::LlamaModelTest::test_torch_fx_output_loss - AssertionError: Couldn't trace module: Model GaudiLlamaModel is not support
FAILED tests/transformers/tests/models/llama/test_modeling_llama.py::LlamaModelTest::test_torch_fx - AssertionError: Couldn't trace module: Model GaudiLlamaModel is not support...
FAILED tests/transformers/tests/models/llama/test_modeling_llama.py::LlamaModelTest::test_torch_fx_output_loss - …
```
=> fix(pr-1387/1386): reverting some of transformer pytest funcs/values

Makefile
current order of execution of test_diffusers is running into a problem where 1x tests are done initially and doesnt seem to release the cards for subsequent 8x tests. hence changing the order
=> change the order for test_diffusers

optimum/habana/transformers/generation/utils.py
PR #1359 introduced error in some models text generation:
’meta-llama/Llama-2-7b-hf‘
‘mistralai/Mistral-7B-Instruct-v0.2'
’Qwen/Qwen2-7B‘
’bigcode/starcoder2-15b‘
Reproduce command:
`
python examples/text-generation/run_generation.py --use_hpu_graphs --model_name_or_path meta-llama/Llama-2-7b-hf
`
Input/outputs:
input 1: ('DeepSpeed is a machine learning framework',)
output 1: ('DeepSpeed is a machine learning frameworkЉЉЉЉЉЉЉЉЉЉЉЉЉЉЉ\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n.............................\n\n............\n......',)
Only use slicing operation on hidden_states for logits computing in case of kv_cache and reuse_cache is enabled.
=> fix llama model text generation error

examples/text-generation/requirements.txt, examples/text-generation/requirements_lm_eval.txt
downgrade datasets version to 2.21.0 for text-gen due to the following error
(/usr/local/lib/python3.10/dist-packages/datasets/__init__.py)
import lm_eval.tasks
File "/usr/local/lib/python3.10/dist-packages/lm_eval/tasks/__init__.py", line 65, in <module>
from . import scrolls
File "/usr/local/lib/python3.10/dist-packages/lm_eval/tasks/scrolls.py", line 33, in <module>
from datasets import load_metric
ImportError: cannot import name 'load_metric' from 'datasets' (/usr/local/lib/python3.10/dist-packages/datasets/__init__.py)
=> datasets downgrade version to 2.21.0

tests/ci/sentence_transformers.sh
We suggest to modify the file tests/ci/sentence_transformers.sh to remove CI block issue -
1.  test_evaluator.py not existing in latest ST repo and no need to add here
2.  remove the testcases of file “ test_train_stsb.py test_trainer.py test_pretrained_stsb.py “ because all ST with hpu related training cases already put into tests/sentence_transformers. There are three training ST test cases there.
3.  So the final test cases just need to cover ST inference like - " test_cmnrl.py test_multi_process.py test_compute_embeddings.py test_model_card_data.py test_util.py " to be included in tests/ci/sentence_transformers.sh
The above suggestion can remove CI block issue due to the original ST training part not enabled with hpu device from ST repo.
=> Update ci sentence_transformer.sh

examples/language-modeling/README.md, examples/text-generation/README.md
add --trust_remote_code for google/flan-t5-xl as per runtime error comment
ValueError: Loading super_glue requires you to execute the dataset script in that repo on your local machine. Make sure you have read the code there to avoid malicious use, then set the option `trust_remote_code=True` to remove this error.
=> Update language-modeling README.md, add trust_remote_code for flan-t5-xl

examples/text-generation/README.md
Currently, unify_measurements.py supports only PTQ output. (default)
It will support PCQ output from v1.19.
=> Update unify_measurements.py support info

examples/text-generation/README.md
=> add peft generation example

examples/text-generation/utils.py
Quick fix for this exception:
```bash
PT_HPU_LAZY_MODE=0 python run_generation.py --model_name_or_path gpt2 --batch_size 2 --max_new_tokens 100 --use_hpu_graphs --use_kv_cache --bf16 --bucket_size 50 --torch_compile
File "/root/optimum-habana/examples/text-generation/utils.py", line 187, in get_torch_compiled_model
model.model = torch.compile(model.model, backend="hpu_backend", options={"keep_input_mutations": True})
File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1732, in __getattr__
raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'GaudiGPT2LMHeadModel' object has no attribute 'model'
```
I'm also preparing better solution, but with more changes which can affect other models.
=> GPT2 torch.compile fix

examples/text-generation/README.md, examples/text-generation/run_generation.py, examples/text-to-speech/README.md
this PR address 3 issues
1. a merge error in run_generation
2. remove support for facebook/hf-seamless-m4t-medium from text-to-speech due to issues
3. reduce the batch size for text-generation command using Using Habana Flash Attention due to memory issues
=> fix merge error and update text-to-speech readme

optimum/habana/transformers/models/llama/modeling_llama.py
This was added for llama3 error, but it's breaking code llama long sequence run. 
We are adding check for the llama3 only. 
https://github.com/huggingface/optimum-habana/pull/1394
`python run_generation.py --model_name_or_path codellama/CodeLlama-13b-Instruct-hf --use_hpu_graphs --trim_logits --use_kv_cache --limit_hpu_graphs --bucket_size=128 --bucket_internal --max_new_tokens 1384 --max_input_tokens 15000 --bf16 --batch_size 4 --use_flash_attention --flash_attention_recompute  
`
Out of memory error, only able to run batch 1.
=> Fix OOM error for code llama

optimum/habana/transformers/models/modeling_all_models.py, optimum/habana/transformers/models/starcoder2/modeling_starcoder2.py
A bug in scoped linear all-reduce implementation for starcoder2 model caused incorrect output as shown below:
`python ../gaudi_spawn.py --use_deepspeed --world_size 2 run_generation.py --model_name_or_path bigcode/starcoder2-15b --use_hpu_graphs --trust_remote_code --attn_softmax_bf16 --trim_logits --use_kv_cache --use_flash_attention --flash_attention_recompute --max_new_tokens 128 --batch_size 1 --bf16 --prompt "def is_prime():"`
Output:
Input/outputs:
input 1: ('def is_prime():',)
output 1: ('def is_prime(): ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( (',)
Output after the fix: …
=> Fix scoped linear all-reduce for starcoder model

optimum/habana/sentence_transformers/st_gaudi_trainer.py
In SentenceTransformer, the loss object stores the base model. To ensure compatibility with updated models (e.g., distributed or compiled models), we override the original model in the loss object. However, in distributed mode using DeepSpeed with PeftModel, this process caused a recursion error. This commit addresses the issue by properly handling the model override to prevent recursion.
This PR addresses the root causes of the issue using PeftModel, which has been tried in https://github.com/huggingface/optimum-habana/pull/1400 and it does not affect other cases non PeftModel with or without DeepSpeed
```sh
>>> cd ~/optimum-habana/examples/sentence-transformers-training/sts
>>> python ../../gaudi_spawn.py --use_deepspeed --world_size 2 training_stsbenchmark.py --peft
{'train_runtime': …
```
=> Fixed recursion error in SentenceTransformer

examples/language-modeling/run_lora_clm.py, examples/text-generation/utils.py
In the text-generation example, the pad token id is set to 0 by default for Llama models. This was introduced by a bad config for Decapoda-research models. However, this is not compatible with Llama 3.1 and newer.
Since the model from Decapoda-research is quite old now, this PR removes this and changes the logic to set the pad token id.
Fixes #1378 #1170.
=> Fix Llama 3.1 generation

examples/image-to-text/README.md, examples/image-to-text/run_pipeline.py, optimum/habana/transformers/models/clip/modeling_clip.py
DeepSpeed init_distributed() and init_inference() were pulled from the text-generation example. 
Clip model change is required because DeepSpeed updates hidden_size
=> Enable DeepSpeed for image-to-text example

examples/language-modeling/README.md, examples/language-modeling/run_lora_clm.py
New error _'ValueError: Asking to pad but the tokenizer does not have a padding token. Please select a token to use as `pad_token` `(tokenizer.pad_token = tokenizer.eos_token e.g.)` or add a new pad token via `tokenizer.add_special_tokens({'pad_token': '[PAD]'})`'_ introduced by  #1444 for Llama3.1.
This patch fixes the above when running the run_lora_clm.py for **finetuning**  llama3.1 using command from **language-modeling** README:
```
PT_HPU_MAX_COMPOUND_OP_SIZE=10 \
python3 ../gaudi_spawn.py --use_deepspeed  --world_size 8  run_lora_clm.py \
--model_name_or_path meta-llama/Llama-3.1-70B-Instruct \
--deepspeed llama2_ds_zero3_config.json \
--dataset_name tatsu-lab/alpaca \
--bf16 True \
--output_dir ./lora_out \
--num_train_epochs 2 \
--max_seq_len 2048 \
--per_device_train_batch_size …
```
=> Fixes 'Tokenizer does not have padding token' introduced by  #1444 for Llama3.1

examples/text-generation/utils.py
```
SRAM_SLICER_SHARED_MME_INPUT_EXPANSION_ENABLED=false ENABLE_EXPERIMENTAL_FLAGS=1 \
python run_generation.py \
--model_name_or_path meta-llama/Llama-2-7b-hf \
--use_kv_cache \
--trim_logits \
--batch_size 1 \
--bf16 \
--attn_softmax_bf16 \
--quantized_inc_model_path <local_model_path_from_inc> 
```
upper command gets error due to dtype mismatch. It will be fixed in Synapse 1.19.0
```
File "/home/xinhe3/optimum-habana-fork/examples/text-generation/run_generation.py", line 656, in generate                                              
output_tokens = model.generate(                                                                                                                      
File "/home/xinhe3/qnpu/venv-118/lib/python3.10/site-packages/torch/utils/_contextlib.py" …
```
=> fix bug when loading 4bit checkpoint quantized in INC

optimum/habana/transformers/models/falcon/modeling_falcon.py, optimum/habana/transformers/models/gemma/modeling_gemma.py, optimum/habana/transformers/models/llama/modeling_llama.py, optimum/habana/transformers/models/modeling_all_models.py, optimum/habana/transformers/models/qwen2/modeling_qwen2.py, optimum/habana/transformers/models/qwen2_moe/modeling_qwen2_moe.py, optimum/habana/transformers/models/starcoder2/modeling_starcoder2.py
Fixes the bias update in `post_all_reduce` for scoped all reduce to remove assumption of in-place bias updates. This led to incorrect outputs with fp8 models like starcoder2 since the Intel Neural Compressor does not use in-place updates (see https://github.com/intel/neural-compressor/blob/27f3e2657b2667e8bca8fb9c02a50d55f404a7e6/neural_compressor/torch/algorithms/fp8_quant/_quant_common/helper_modules.py#L417)
This PR is a more general fix for the issue than https://github.com/huggingface/optimum-habana/pull/1432 which only fixed the issue for bf16 models.
`QUANT_CONFIG=./quantization_config/maxabs_measure.json python ../gaudi_spawn.py --use_deepspeed --world_size 2 \
run_generation.py --model_name_or_path bigcode/starcoder2-15b \
--use_hpu_graphs --trust_remote_code --attn_softmax_bf16 …
=> Fix bias update in scoped all reduce

tests/transformers/tests/models/mistral/test_modeling_mistral.py, tests/transformers/tests/models/mixtral/test_modeling_mixtral.py
This PR is to skip the unsuported pytests added for mistral/mixtral with PR #1387 
```
======================================================================================================= short test summary info =======================================================================================================
FAILED tests/transformers/tests/models/mistral/test_modeling_mistral.py::MistralModelTest::test_attention_outputs - AssertionError: Lists differ: [2, 7, 7] != [4, 7, 7]
FAILED tests/transformers/tests/models/mistral/test_modeling_mistral.py::MistralModelTest::test_beam_search_generate - NotImplementedError: Make sure that a `_reorder_cache` function is correctly implemented in optimum.habana.transformers.models.mistral.modeling_mistral to enable beam search for <class …
```
=> fea(pytests): Added skip for unsuported tests for mistral/mixtral

docs/source/package_reference/gaudi_config.mdx, examples/language-modeling/README.md, optimum/habana/transformers/gaudi_configuration.py, optimum/habana/transformers/trainer.py, tests/test_examples.py
Flags (LOWER_LIST, FP32_LIST) used to force user-defined OPs to bfloat16 or float32 when using autocast have been deprecated in SynapseAI release 1.18.0 and shall be removed in SynapseAI release 1.19.0.  Update readme files & code to use new flags replacing these (PT_HPU_AUTOCAST_LOWER_PRECISION_OPS, PT_HPU_AUTOCAST_FP32_OPS_LIST).
=> Remove deprecated Mixed precision flags

optimum/habana/transformers/models/gemma/modeling_gemma.py
Add missing flash attention flags to gemma
=> Enable flash attention for gemma

examples/language-modeling/requirements.txt
Hi
Specifying torch requirement causes some bug in our QA infra, can we just skip the obvious pytorch requirement? I am not sure this version is still supported.
=> Remove torch req from LM example

examples/text-generation/run_lm_eval.py
This fix is already included in latest lm_eval version but upgrade is still WIP. Until we migrate to latest lm_eval we need this fix if customer wants to use remote code.
=> Fix trust_remote_code

Makefile, examples/text-generation/run_generation.py, tests/test_functional_text_generation_example.py, tests/test_text_generation_example.py
- Fix to `run_generation.py` so `results.json` stores all outputs instead of just the last when batch_size > 1
- Functional verification of select text gen models to be run for every PR (fast tests)
- Duration of added fast tests on Gaudi2: ` 7 passed, 1 warning in 1991.08s (0:33:11)`
- Functional verification added to slow test `test_text_generation_example.py` for select BF16 1HPU cases
- Found issues in bigcode/starcoder output in fast(passes) vs slow(fails due to bucketing options), will file ticket to fix that.
=> Tests for text gen output text

optimum/habana/transformers/models/starcoder2/modeling_starcoder2.py
Summary- (you can reproduce it from here)
Issue is not seen on 1 HPU.
Issue is seen with OptimumHabana v1.13 + with 8 HPU
Issue not seen with OptimumHabana v1.12 with 8 HPU
Replicate:
Reserve Gaudi2 with driver 1.17-495
docker pull [vault.habana.ai/gaudi-docker/1.17.0/ubuntu22.04/habanalabs/pytorch-installer-2.3.1:1.17.0-495](http://vault.habana.ai/gaudi-docker/1.17.0/ubuntu22.04/habanalabs/pytorch-installer-2.3.1:1.17.0-495)
git clone [GitHub - huggingface/optimum-habana: Easy and lightning fast training of 🤗 Transformers on Habana Gaudi processor (HPU)](https://github.com/huggingface/optimum-habana.git)
git checkout v1.13.2
docker run -it --runtime=habana -e HABANA_VISIBLE_DEVICES=all -e OMPI_MCA_btl_vader_single_copy_mechanism=none --rm --cap-add=sys_nice --net=host --ipc=host -v …
=> Fix tuple object error

optimum/habana/transformers/trainer.py
We are adding log prints for compile time in our evaluation/prediction loop for all inference test cases. To get the compile time, use the --throughput_warmup_steps flag (same logic as in text_generation/run_generation.py). This will also increase the throughput numbers since it will remove the warmup time from the throughput calculation.
- examples/language-modeling/run_mlm.py  
```
***** eval metrics *****
..
eval_graph_compliation_duration =      0.949
..
```
- examples/summarization/run_summarization.py 
```
***** predict metrics *****
predict_gen_len                    =     5.4174
predict_graph_compliation_duration =     9.3589
...
```
=> Add warmup time and compile time log for the eval/prediction. 

examples/text-generation/quantization_config/maxabs_quant_gemma.json, optimum/habana/transformers/models/gemma/modeling_gemma.py
Fixed Gemma FP8 flash attention lower throughput issue due to FusedSDPA did not proper convert to fp8_quant.
Fixes # (https://habana.atlassian.net/browse/HS-3985)
=> Fixed Gemma FP8 flash_attention lower throughput issue

optimum/habana/transformers/trainer.py
Problem: TrainingArgs.use_lazy_mode is not used by GaudiLlamaModel
Cause: lazy_mode argument was not passed by GaudiTrainer
Solution: Added missing argument to inputs in
GaudiTrainer._inner_training_loop
=> pass "lazy_mode" arg to GaudiLlamaModel GaudiTrainer

optimum/habana/transformers/models/bert/modeling_bert.py
Problem: graph brake is introduced by get_autocast_hpu_dtype call
Solution: this line is no longer needed as autocast logic will be executed in GaudiTrainer, therefore can be removed without breaking anything.
=> Removed workaround for NaN bug causing graph break.

optimum/habana/transformers/modeling_utils.py, optimum/habana/transformers/models/__init__.py, optimum/habana/transformers/models/wav2vec2/__init__.py, optimum/habana/transformers/models/wav2vec2/modeling_wav2vec2.py
=> implement fused sdpa for wav2vec2 (#18)

optimum/habana/transformers/models/gpt_bigcode/modeling_gpt_bigcode.py
Use torch.matmul instead of torch.baddbmm in
GPTBigCodeAttention._attn for devices other than cpu. This allows for using significantly larger batch sizes in text generation with bigcode-related models.
=> Memory optimization for gpt_bitcode (#4)

optimum/habana/transformers/generation/utils.py
Improves error reporting for case when internal_bucketing requested without kv-cache enabled
For example command line (note the absence of ```--use_kv_cache``` parameter)
```
python3 run_generation.py --model_name_or_path bigcode/starcoder --batch_size 2 --max_new_tokens 100 --bucket_size 128 --bucket_internal --use_hpu_graphs --bf16  --prompt 'def print_hello_world():'
```
Before fix:
```
File "/var/work/optimum-habana/examples/text-generation/run_generation.py", line 758, in <module>
main()
File "/var/work/optimum-habana/examples/text-generation/run_generation.py", line 523, in main
generate(None, args.reduce_recompile)
File "/var/work/optimum-habana/examples/text-generation/run_generation.py", line 494, in generate
outputs = model.generate(
File …
```
=> text_generation: improve parameters check

optimum/habana/transformers/trainer.py, optimum/habana/transformers/training_args.py, optimum/habana/utils.py
The default argument of profiler `with_stack ` is `False`. Enabling this can help performance analysis align with model function，through it need more memory usage, we still need it to locate problem code. 
This pr makes the `with_stack` changeable (for customer demands).
=> Makes the with_stack of the profiler changeable

examples/text-generation/run_generation.py
Change dtype of valid sequence length tensor to explicit torch.int32.
Previously this caused issue on bs=1 configs with torch.compile.
affected command:
PT_HPU_LAZY_MODE=0  python /root/optimum-habana-fork/examples/text-generation/run_generation.py --attn_softmax_bf16 --use_hpu_graphs --use_kv_cache --bf16 --model_name_or_path /qa/inference/helper_files/granite/granite-8b --batch_size 1 --bucket_size 128 --bucket_internal --n_iterations 1 --warmup 1 --max_input_tokens 2048 --max_new_tokens 1 --use_flash_attention --flash_attention_recompute --flash_attention_causal_mask --book_source --torch_compile
=> Fix dtype issue with valid sequence length in torch.compile bs=1

tests/baselines/Llama_3_1_8B.json, tests/baselines/Meta_Llama_3_1_8B.json, tests/test_examples.py, tests/utils.py
Recently, There was a fix in PR#1457 for a bug in the fine-tuning of the Llama 3.1 family models.
This PR ensures that this model family does not escape testing.
=> Add Llama 3.1 ft to CI

examples/text-generation/utils.py
It changes `get_torch_compiled_model(model)` function:
```python
def get_torch_compiled_model(model, logger):
if hasattr(model, 'transformer'):
model.transformer = torch.compile(
model.transformer, backend="hpu_backend", options={"keep_input_mutations": True}
)
...
...
```
It’s hard-coded now by models' types, but we can hard-code it from attributes' point of view. I think this way can cover more models already supported for each attribute.
Please advise, if you know better way to remove hard-codes.
I did some manual testing for models with types the function covers.
**Please, advise tests I need to run or a models list validated with `--torch_compile` option.**
=> Text-generation, model set-up: torch.compile for attributes instead of models' types

optimum/habana/transformers/modeling_utils.py, optimum/habana/transformers/models/__init__.py, optimum/habana/transformers/models/mllama/__init__.py, optimum/habana/transformers/models/mllama/modeling_mllama.py
=> enable fusedsdpa kernel for vision part of mllama

examples/contrastive-image-text/run_bridgetower.py, optimum/habana/transformers/gradient_checkpointing.py, optimum/habana/transformers/models/falcon/modeling_falcon.py, optimum/habana/transformers/models/mixtral/modeling_mixtral.py, tests/test_pipeline.py, tests/transformers/tests/models/wav2vec2/test_modeling_wav2vec2.py
Description: Adding support for loading images stored directly in a JSON file (encoded using ISO-8859-1) into an image object.
It resolves an error: TypeError Unexpected type <class 'NoneType'> in BridgeTower model.
Command:
WANDB_DISABLED=true PT_HPU_MAX_COMPOUND_OP_SIZE=512 python3 run_bridgetower.py --model_name_or_path 'BridgeTower/bridgetower-large-itm-mlm-itc' --do_train --dataset_name 'jmhessel/newyorker_caption_contest' --dataset_config matching --image_column image --caption_column image_description --remove_unused_columns False --mediapipe_dataloader --output_dir /tmp/bridgetower-test --per_device_train_batch_size 40 --per_device_eval_batch_size 16 --learning_rate 1e-05 --overwrite_output_dir --use_habana --use_lazy_mode --use_hpu_graphs_for_inference --gaudi_config_name …
=> Fix bridgetower example (#312)

examples/summarization/README.md
Add an example on 8 HPUs on Gaudi2 with DeepSpeed-ZeRO2 to fine-tune t5-large
=> Migrate OH T5-large training to torch.compile

optimum/habana/transformers/trainer.py
=> trainer: fixed spelling

optimum/habana/transformers/models/qwen2/modeling_qwen2.py, optimum/habana/transformers/models/qwen2_moe/modeling_qwen2_moe.py
=> Refactor Qwen2 Family

examples/stable-diffusion/text_to_image_generation.py, optimum/habana/diffusers/pipelines/pipeline_utils.py, optimum/habana/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py, optimum/habana/transformers/training_args.py
The new option --sdp_on_bf16 allows pyTorch to use reduced precision in sdp in the math backend.
The change affects the following examples:
* contrastive-image-text/run_bridgetower.py
* question-answering/run_qa.py
* speech-recognition/run_speech_recognition_ctc.py
* stable-diffusion//text_to_image_generation.py
* text-classification/run_glue.py
=> Add option to use bf16 in PT sdp (#5)

optimum/habana/transformers/models/wav2vec2/modeling_wav2vec2.py
Remove tensor.item and dynamic slicing operations in the loop that cause graph break
=> [wav2vec2] Remove tensor.item and dynamic slicing operations in the loop that cause graph break

optimum/habana/transformers/generation/utils.py
PR #1358 introduced a nested for loop which caused performance drop observed e.g. in T5 summarization. This change  translates the loop into tensor operations and restores performance.
=> Restore performance in generate

tests/test_text_generation_example.py
Since the accuracy patch for Qwen2 family [(PR Link)](https://github.com/huggingface/optimum-habana/pull/1541) was merged, the test case should be also adjusted for the batch size and output.
```
GAUDI2_CI=1  RUN_SLOW=1 python3.10 -m pytest tests/test_text_generation_example.py -s -v -k generation_bf16_1x[token0-Qwen/Qwen2-7B-256
```
Result:
```
Stats:
----------------------------------------------------------------------------------
Input tokens
Throughput (including tokenization) = 8871.747465242199 tokens/second
Memory allocated                    = 62.52 GB
Max memory allocated                = 65.15 GB
Total memory available              = 94.62 GB
Graph compilation duration          = 10.456412034000095 seconds
------------------------------------------------------------------------- …
```
=> Adjust Qwen2-7B test case

examples/text-generation/run_lm_eval.py
the output json file in examples/text-generation/run_lm_eval.py has several hundreds MB size,
the print(json.dumps(results, indent=2)) will print the several hundreds MB json file content to terminal each time it cost huge resource and not friendly using
so remove it
https://github.com/huggingface/optimum-habana/issues/1552
=> [run_lm_eval.py] Fixed too many print dump json info

examples/image-to-text/README.md, examples/image-to-text/run_pipeline.py, tests/test_image_to_text_example.py
This is an extension of PR#1514 by applying --sdp_on_bf16 to image-to-text examples and its tests
=> Apply --sdp_on_bf16 to image-to-text examples

tests/test_examples.py
Fixed issue with adalora example tester.  Fix regarded "Dataset_name" under "class MultiCardCausalLanguageModelingAdaloraExampleTester".
=> Fixed Adalora Test for OH 1.15

tests/baselines/llama_7b.json
Fixed issue relating to LORACP Test.  An error was observed as follows with default version of test:
22834 [2024-12-04T15:07:53.728Z] [rank0]:   File "/root/optimum-habana/examples/language-modeling/run_lora_clm.py", line 563, in main
22835 [2024-12-04T15:07:53.728Z] [rank0]:     raise ValueError(
22836 [2024-12-04T15:07:53.728Z] [rank0]: ValueError: Please set --validation_split_percentage as dataset does not contain `validation` key
22837 [2024-12-04T15:07:53.728Z] [rank6]: Traceback (most recent call last):
This issue is corrected by adding "--validation_split_percentage" to the "tatsu-lab/alpaca_cp" task name in "tests/baseline/llama_7b.json".
In addition, perplexity has to be adjusted in order to ensure that it passes the test.  Default value results in a FAILED test. @bhargaveede , …
=> Fixed LORACP Test for OH 1.15

optimum/habana/transformers/models/modeling_all_models.py
FAILED tests/test_examples.py::MultiCardCausalLanguageModelingPrefixTuningExampleTester::test_run_prompt_tuning_clm_llama-7b_multi_card - AssertionError:
1 != 0
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1565, in _call_impl
[rank2]:     return forward_call(*args, **kwargs)
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/peft/peft_model.py", line 1612, in forward
[rank2]:     return self.base_model(
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1556, in _wrapped_call_impl
[rank2]:     return self._call_impl(*args, **kwargs)
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1606, in _call_impl
[rank2]:     result = forward_call(*args, **kwargs) …
=> fix prefix llama ci failure

examples/image-to-text/run_pipeline.py, examples/text-generation/run_generation.py, tests/test_encoder_decoder.py, tests/test_examples.py, tests/test_fsdp_examples.py, tests/test_image_to_text_example.py, tests/test_text_generation_example.py
=> add sdp_on_bf16 to tests,text-gen

optimum/habana/transformers/generation/utils.py
pytest tests/test_examples.py::MultiCardImageToTextModelingLoRAExampleTester::test_run_image2text_lora_finetune_Llama-3.2-11B-Vision-Instruct_multi_card -v -s
File "/workspace/wangyi/optimum-habana/examples/image-to-text/run_image2text_lora_finetune.py", line 553, in
main()
File "/workspace/wangyi/optimum-habana/examples/image-to-text/run_image2text_lora_finetune.py", line 538, in main
anls = eval(
File "/workspace/wangyi/optimum-habana/examples/image-to-text/run_image2text_lora_finetune.py", line 334, in eval
generated_ids = model.generate(
File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
return func(*args, **kwargs)
File "/workspace/wangyi/optimum-habana/optimum/habana/transformers/generation/utils …
=> fix mllama test

optimum/habana/transformers/trainer.py
credit: @yafshar for fix
Fix for failing test:
```
GAUDI2_CI=1  RUN_SLOW=1 python3.10 -m pytest tests/test_examples.py -s -v -k test_run_glue_LlamaGuard-7b_deepspeed
```
```
[rank2]:     return forward_call(*args, **kwargs)
[rank2]:   File "/root/tf/deepspeed-fork/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
[rank2]:     ret_val = func(*args, **kwargs)
[rank2]:   File "/root/tf/deepspeed-fork/deepspeed/runtime/engine.py", line 1907, in forward
[rank2]:     loss = self.module(*inputs, **kwargs)
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
[rank2]:     return self._call_impl(*args, **kwargs)
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1750, in _call_impl
[rank2]: …
```
=> fix lazy_mode assignment

README.md, docs/source/index.mdx, examples/language-modeling/README.md, examples/language-modeling/run_clm.py, optimum/habana/transformers/generation/utils.py, optimum/habana/transformers/modeling_utils.py, optimum/habana/transformers/models/__init__.py, optimum/habana/transformers/models/chatglm/__init__.py, optimum/habana/transformers/models/chatglm/configuration_chatglm.py, optimum/habana/transformers/models/chatglm/modeling_chatglm.py, optimum/habana/transformers/models/chatglm/tokenization_chatglm.py, optimum/habana/transformers/trainer.py, tests/baselines/chatglm3_6b.json, tests/test_examples.py, tests/test_text_generation_example.py, tests/utils.py
This PR adds the chatglm model  (a custom model), including chatglm2-6b, chatglm3-6b.
The inference test and pretrain example/test are also available.
=> Add chatglm

optimum/habana/transformers/models/gpt_bigcode/modeling_gpt_bigcode.py, tests/test_text_generation_example.py
- update kv-cache state inplace at decode phase
- slice tensors with cache_idx to reduce excessive compute
This PR fixes lost context issue for gpt_bigcode class of models (starcoderbase/starcoder) when bucket_internal feature is used
It allows to unblock generation quality tests in https://github.com/huggingface/optimum-habana/blob/main/tests/test_text_generation_example.py#L36
For example, with command line
```
python3 examples/text-generation/run_generation.py --model_name_or_path bigcode/starcoder --batch_size 2 --use_kv_cache --max_new_tokens 100 --bucket_size 128 --bucket_internal --use_hpu_graphs --bf16  --prompt 'def print_hello_world():'
```
without this fix:
```
Input/outputs:
input 1: ('def print_hello_world():',)
output 1: ('def print_hello_world():\n    print("Hello …
```
=> gpt_bigcode: added internal bucketing fix

examples/text-generation/utils.py, optimum/habana/utils.py
Reverts huggingface/optimum-habana#1500
Currently, `neural_compressor_pt` package misses packing the version info. So we need to revert it.
`
AttributeError: module 'neural_compressor' has no attribute '__version__'
`
=> Revert "add check_neural_compressor_min_version for 4 bit behavior"

examples/text-generation/utils.py
Remove temporary fixes on neural compressor logic that we added to support Synapse 1.18
This code no longer needed for Synapse1.19
=> Remove unnecessary neural compressor fix for 1.19 release

optimum/habana/transformers/models/detr/modeling_detr.py, optimum/habana/transformers/trainer.py, optimum/habana/transformers/training_args.py
=> Fixed spelling

examples/text-generation/utils.py, optimum/habana/transformers/models/llama/modeling_llama.py
Moving the max_position_embeddings truncation from model code as it hampers with training.
Moved it to text-generation/utils.py as that's better place
=> Limit position embeddings in inference

examples/text-generation/README.md, optimum/habana/transformers/models/llama/modeling_llama.py, optimum/habana/transformers/models/modeling_all_models.py
Fixed common KVCache code NOT to have token_idx check to fix lm_eval with reuse_cache. (Readme validation). 
Added LlamaKVCache to have token_idx check handle llama prompt finetuning. 
Command for Falcon180b, Phi lm_Eval from Readme(https://github.com/huggingface/optimum-habana/blob/main/examples/text-generation/README.md#running-with-fp8) is failing
Command:
```
python run_lm_eval.py -o falcon.eval --model_name_or_path tiiuae/falcon-7B --use_hpu_graphs --use_kv_cache --trim_logits --batch_size 1 --bf16 --reuse_cache --use_flash_attention --flash_attention_recompute --flash_attention_causal_mask
```
Error 
```
2024-12-12 17:55:48.844] [COMPLEXGUID_LIB] [error] 'tpckernel.sdpa_recomp_core_fwd' op Broadcast of shape [1, 1, 384, 384] not possible at index 3. Dimension 384 …
```
=> Revert common KVCache not to check token_idx

optimum/habana/transformers/models/llama/modeling_llama.py
Inherit KVCache to specific model(LlamaKVCache) cause memory increase and failing the max-batch run on llama model, get OOM on below command. Keep the KVCache it's own to llama model. 
QUANT_CONFIG=./quantization_config/maxabs_quant.json python ../gaudi_spawn.py \
--use_deepspeed --world_size 8 run_generation.py \
--model_name_or_path meta-llama/Llama-2-70b-hf \
--attn_softmax_bf16 \
--trim_logits \
--use_kv_cache \
--reuse_cache \
--use_flash_attention \
--flash_attention_recompute \
--bf16 \
--batch_size 350 \
--max_new_tokens 2048 \
--max_input_tokens 2048 \
--limit_hpu_graphs
For batch 300, this is the result I got. 
```
With LlamaKVCache:
----------------------------------------------------------------------------------
Input tokens
Throughput (including …
```
=> Revert LlamaKVCache due to memory increase

tests/test_diffusers.py
- Replace the the UNET custom attention processors with the default implementation on HPU.
Fixes # (issue) on G3
```sh
>>> python -m pytest tests/test_diffusers.py -v -s -k test_deterministic_image_generation --junitxml=report4.xml
tests/test_diffusers.py:3752:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py:116: in decorate_context
return func(*args, **kwargs)
optimum/habana/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py:594: in __call__
noise_pred = self.unet_hpu(
/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py:116: in decorate_context
return func(*args, **kwargs) …
```
=> Replace the UNET custom attention processors

examples/text-generation/utils.py
Some of old models doesn't have this rope_scaling  attribute and failing to run.  
Adding attribute check. 
Command to test: 
`python3 /root/optimum-habana/examples/gaudi_spawn.py --use_deepspeed --world_size 8 /root/optimum-habana/examples/text-generation/run_generation.py --model_name_or_path bigscience/bloomz --batch_size 1 --use_kv_cache --max_new_tokens 100 --use_hpu_graphs --output_dir /tmp/tmp20f06_pq
`
49874 [rank1]:   File "/usr/local/lib/python3.10/dist-packages/transformers/configuration_utils.py", line 202, in __getattribute__
49875 [rank1]:     return super().__getattribute__(key)
49876 [rank1]: AttributeError: 'BloomConfig' object has no attribute 'rope_scaling'
```
=> Check rope_scaling attr

conftest.py, optimum/habana/transformers/generation/utils.py, optimum/habana/transformers/models/bart/modeling_bart.py, pyproject.toml, tests/transformers/tests/generation/test_framework_agnostic.py, tests/transformers/tests/generation/test_utils.py
This reverts commit 2ba520a9f12467bfeb25a8fde4dee7caf27c0067.
This change caused so many new pytest failures. May need further change in transformer test side to have this change back.
=> Revert "Update transformers tests generation util v4.45.2 (#1441)"

examples/contrastive-image-text/README.md
=> fix readme cmds for clip-roberta

examples/trl/README.md
In DPO pipeline section, it shows run_generation.py command which it runs with DPO output.
The DPO output (./dpo) is generated from llama2-70b-hf, but the examples (merging/run_generation) are basing llama2-7b-hf.
It fails with wrong dimension during merging and OOM when it runs run_generation test.
=> Fix run_generation test commands for TRL out usage example

examples/text-generation/run_generation.py
Check if the model requires `token_type_ids` based on its configuration. The `type_vocab_size` attribute indicates the number of token types the model supports. If `type_vocab_size` > 0, `token_type_ids` are expected (e.g., for BERT and similar models).
If `type_vocab_size` is 0 or absent, `token_type_ids` are not needed
=> Falcon Model Support

examples/sentence-transformers-training/nli/training_nli.py, examples/sentence-transformers-training/nli/training_nli_v2.py, examples/sentence-transformers-training/nli/training_nli_v3.py, examples/sentence-transformers-training/paraphrases/training_paraphrases.py, examples/sentence-transformers-training/sts/training_stsbenchmark.py, examples/sentence-transformers-training/sts/training_stsbenchmark_continue_training.py
Update the argument options for sentence transformer examples with sdp_on_bf16 to solve the issue from 
https://github.com/huggingface/optimum-habana/pull/1555/files
and tested/verified with results. Thanks. 
=> Update sdp_on_bf16 option for ST example

optimum/habana/diffusers/pipelines/pipeline_utils.py
https://github.com/huggingface/optimum-habana/pull/1626 introduced a condition check on whether `text_encoder_2_lora_layers` is None or not and then call `save_lora_weights` in different ways: https://github.com/huggingface/optimum-habana/pull/1626/files#diff-bfc760c4e8acf1425990d609ecd6f1cadb2e027a0d20f027f652375f012e484dR399
However, `text_encoder_2_lora_layers` can be None and still be passed as an argument to `save_lora_weights`, as shown with SDXL in https://github.com/huggingface/optimum-habana/pull/1633#issuecomment-2553393043.
This PR changes the check so that `text_encoder_2_lora_layers` is passed if and only if it is part of the signature of `save_lora_weights`.
=> Fix `save_lora_weights` in `pipeline_utils.py`

examples/trl/README.md, optimum/habana/transformers/modeling_utils.py, optimum/habana/transformers/models/__init__.py, optimum/habana/transformers/models/mixtral/__init__.py, optimum/habana/transformers/models/mixtral/modeling_mixtral.py
moe block forward regresion brought by https://github.com/huggingface/optimum-habana/pull/1511 for training
=> refactor mixtral moe block.

examples/speech-recognition/requirements.txt
We saw B17fsspec.exceptions.FSTimeoutError with dataset 3.2.0 when running wav2vec test, downgrade to 2.19.2 solves the issue.
=> speech-recognition: downgrade datasets version

examples/stable-diffusion/text_to_image_generation.py, examples/stable-diffusion/training/train_controlnet.py, optimum/habana/diffusers/pipelines/controlnet/pipeline_controlnet.py
add sdp_on_bf16 in train_controlnet script. allows corresponding diffusers CI test to pass.
=> add sdp_on_bf16 to controlnet

examples/pytorch-image-models/train_hpu_graph.py, examples/pytorch-image-models/train_hpu_lazy.py
This PR will solve the distributed issue after OH upgrading to pytorch2.5 from the command example in TIMM model readme as https://github.com/huggingface/optimum-habana/tree/main/examples/pytorch-image-models
to solve the error as below. 
Now it is solved and results verified as below. 
Welcome for any comments. Thanks
=> Fix distributed issue for timm

examples/pytorch-image-models/README.md, examples/trl/README.md, optimum/habana/transformers/models/llama/modeling_llama.py
From PR https://github.com/huggingface/optimum-habana/pull/1148, we need 'training' parameter set for apply_customized_rope(). Otherwise it's True by default.
But when apply_customized_rope() is called in modling_llama, we don't set it.
I think it's missed by mistake. Other model files are updated properly.
=> Added missing parameter for llama function call

examples/multi-node-training/GaudiNIC/Dockerfile, examples/text-generation/README.md
Add missing option (--reuse_cache) for Llama3-405B fp8 measurement from https://github.com/huggingface/optimum-habana/pull/1637,
and fix model to match naming style,
and add missing command in multi-node-training Dockerfile, from https://docs.habana.ai/en/latest/Quick_Start_Guides/Intel_DevCloud_Quick_Start.html#start-the-intel-gaudi-docker-and-share-ssh-keys
=> Add reuse_cache for llama3-405b measurement

optimum/habana/transformers/models/mixtral/modeling_mixtral.py
In PT2.5, using `row_o.fill_` will throw error 'RuntimeError: fill_ only supports 0-dimension value tensor but got tensor with 4 dimensions.'
=> fix bug for GaudiMixtralAttentionLongSequence forward

examples/text-generation/run_generation.py
The prompt_length condition check for warm up is a legacy code for some previous demonstration.
We tried to show that even we do not warmup with exact (dynamic) length we still can get some performance.
But this demo case is no longer needed and all this kind of things are handled in vllm now.
This is a fix for performance degradation of dynamic shape run when datasets given.
For example, 
PT_HPU_LAZY_MODE=0  python3  run_generation.py  --num_beams 1 --model_name_or_path meta-llama/Llama-2-7b-chat-hf  --attn_softmax_bf16  --use_kv_cache --max_new_tokens 128 --bf16 --batch_size 8     --trim_logits --max_input_tokens -1 --n_iterations 500 --warmup 1 --dataset_name tatsu-lab/alpaca   --run_partial_dataset   --torch_compile
=> Enable warmup also for full prompt length case in text generation

examples/image-to-text/run_pipeline.py
Fixes # ([1699](https://github.com/huggingface/optimum-habana/issues/1669))
=> add padding to input for mllama/paligemma/idefices2

examples/audio-classification/run_audio_classification.py, optimum/habana/transformers/models/wav2vec2/modeling_wav2vec2.py
It was impossible for the user to select eager attention in wav2vec2 audio classification. It always defaulted to sdpa. Now default is eager and fused sdpa is selected with --use_flash_attention option.
=> [SW-214100] Enable attention selection in wav2vec-ac

examples/text-generation/run_lm_eval.py
When generate FP8 quant files for model `bigcode/starcoder`, even we add `--use_flash_attention` flag, it can not pass to modeling part. This PR fixes it.
=> fix bug when preparing quant files, starcoder model does not support

examples/pytorch-image-models/README.md, examples/pytorch-image-models/train_hpu_graph.py, examples/pytorch-image-models/train_hpu_lazy.py
In order to simplify the validation testing effort here one arg is added to choose whether save_checkpoint is executed or not to save the validation time. The command below in default is not saving checkpoint per epoch.
python train_hpu_graph.py \
--data-dir ./ \
--dataset hfds/johnowhitaker/imagenette2-320 \
--device 'hpu' \
--model resnet50.a1_in1k \
--train-split train \
--val-split train \
--dataset-download 
if you want to save checkpoint per epoch you need add one more argument " --save_checkpoint " in the command. 
In addition the README.md also is simplified for validation target.
=> Add save_checkpoint arg for TIMM training to simplify validation

optimum/habana/accelerate/accelerator.py, optimum/habana/transformers/trainer.py, optimum/habana/transformers/training_args.py
DeepSpeed's addition of forward and backward hooks to the model causes torch dynamo to fall back to eager mode during compilation for the backward pass (e.g., using CppTensorPreHookFunction), leading to a significant performance degradation.
By applying regional compilation to the model, we can effectively isolate DeepSpeed's hooks from the backward graph, allowing dynamo to successfully trace the backward pass of the model, thus improving performance.
More info about regional compilation:
https://pytorch.org/tutorials/recipes/regional_compilation.html
https://pytorch.org/blog/pytorch2-5/
=> Support regional compilation

optimum/habana/transformers/generation/utils.py
Improves the quality of the text generated by bf16 models when sampling. This change also affects multi-card inference using deepspeed in `run_generation.py` which uses bf16 by default.
For example:
`python run_generation.py --model_name_or_path gpt2 --use_kv_cache --max_new_tokens 100 --do_sample --prompt "Here is my prompt" --bf16`
Before fix: main  a51475f477715715f7debd064d
Here is my prompt for them to see this thread Quote courtesy of [set-up-example.com](http://set-up-example.com/) Waaah awaaaaah. Whoe wooooohhhhhhhhhhhhhhhh. What's that? Haskell version in printable format?\n\nsome@ehive.com\n\nMy HOST ROCKS FOR MY CORE:\n\nacmme29@design's [turntable.mac.ca:20187](http://turntable.mac.ca:20187/) Rational: why can't I mod ram?\n\n%~v1-pc
After fix:
Here is my prompt for your …
=> Fix text generation quality for bf16 models when sampling

examples/image-to-text/README.md, examples/text-classification/README.md, examples/text-feature-extraction/README.md
Simplify ReadMe for text-classification, text-feature-extraction, and image-to-text.
=> Readme modification

examples/text-generation/utils.py
python run_generation.py --model_name_or_path mosaicml/mpt-7b-chat --use_hpu_graphs --use_kv_cache --bf16 --batch_size=1
File "/optimum-habana/examples/text-generation/run_generation.py", line 773, in <module>
main()
File "/optimum-habana/examples/text-generation/run_generation.py", line 533, in main
generate(None, args.reduce_recompile)
File "/optimum-habana/examples/text-generation/run_generation.py", line 504, in generate
outputs = model.generate(
File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
return func(*args, **kwargs)
File "/usr/local/lib/python3.10/dist-packages/optimum/habana/transformers/generation/utils.py", line 997, in generate
generation_config, model_kwargs = …
=> Fix mpt model generation

tests/baselines/Llama_3_2_11B_Vision_Instruct.json
Following test `python -m pytest -s -v tests/test_examples.py -k test_run_image2text_lora_finetune_Llama-3.2-11B-Vision-Instruct_multi_card
` fails on transformers_future but passes on main:
```
tests/test_examples.py:758: in assert_no_regression
assert_function(
E   AssertionError: 18.229 not greater than or equal to 19.456 : for metric train_samples_per_second. 
E   ===== Assessed metrics (measured vs thresholded baseline) =====
E   eval_accuracy: 0.9252059885818973 vs 0.594
E   train_runtime: 396.1691 vs 493.5
E   train_samples_per_second: 18.229 vs 19.456
=========================== short test summary info ============================
FAILED tests/test_examples.py::MultiCardImageToTextModelingLoRAExampleTester::test_run_image2text_lora_finetune_Llama-3.2-11B-Vision-Inst …
```
=> Fix for image2text lora llama test

examples/kubernetes/Chart.yaml
This PR fixes the formatting of the `kubeVersion` in the Kubernetes example helm chart. Without this change, the helm chart fails to install when using Kubernetes v1.28:
```
Error: INSTALLATION FAILED: chart requires kubeVersion: 1.27-1.29 which is incompatible with Kubernetes v1.28.7
```
Formatting the range with spaces around the `-` has fixed the issue.
There are no automated tests for this, but I manually tested with Kubernetes v1.28.7 using the single card glue fine tuning example.
=> Fix formatting of the kubeVersion range in Kubernetes helm chart

examples/stable-diffusion/README.md, examples/stable-diffusion/quantization/stable-diffusion-3/measure_config.json, examples/stable-diffusion/quantization/stable-diffusion-3/quantize_config.json, examples/stable-diffusion/text_to_image_generation.py, optimum/habana/diffusers/pipelines/stable_diffusion_3/pipeline_stable_diffusion_3.py
* HPU graphs enabled
* Batching for inference enabled
* Fused SDPA integrated
* FP8 quantization enabled
* Updated run command in ReadMe and added documentation to run FP8
**Achieved ~4x throughput improvement with HPU Graph and Fused SDPA**
| **Batch Size** | **No of Images** | **Batches** | **Pre-Optimization Throughput (samples/sec)** | **Optimized Throughput (samples/sec)** |
|:--------------:|:----------------:|:-----------:|:--------------------------------------------:|:---------------------------------------:|
|       1        |        10        |      10     |                   0.047                      |                0.227                   |
|       2        |        20        |      10     |                   0.051                      |                0.228 …
=> Optimized SD3 pipeline

optimum/habana/utils.py, tests/test_diffusers.py
a Follow up on #1655, re-structured the check  of 8x-HPU avail on system without loading the `import habana_frameworks.torch.hpu as hthpu`
```
GAUDI2_CI=1 RUN_SLOW=true python -m pytest tests/test_diffusers.py -s -v -k textual_inversion
========================================================= test session starts =========================================================
platform linux -- Python 3.10.12, pytest-7.4.4, pluggy-1.5.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /devops/sgohari/tests/codes/ig/optimum-habana
configfile: setup.cfg
collected 165 items / 163 deselected / 2 selected
7.jpeg: 100%|███████████████████████████████████████████████████████████████████████████████████████| 160k/160k [00:00<00:00, 57.2MB/s]
4.jpeg: …
```
=> fea(): reworked the 8x hpu skipping strategy

examples/image-to-text/run_pipeline.py
Setting DEEPSPEED_USE_HABANA_FRAMEWORKS_DETERMINISTIC_API=1 solves the data loading issue.
=> Process getting killed while loading data for Llama3.2 90b, 8x

optimum/habana/transformers/models/mllama/modeling_mllama.py
The recipe's global HBM memory size (78,888,400) exceeds the QueueComputeScal HBM global memory size limit (67,108,864). Adjusted the recipe to ensure it fits within the required constraints.
command to reproduce the issue 
BS=16;TKI=1024;TKO=1024;python3 examples/image-to-text/run_pipeline.py --model_name_or_path /mnt/weka/data/pytorch/llama3.2/Meta-Llama-3.2-11B-Vision-Instruct/  --bf16 --use_hpu_graphs --use_flash_attention --flash_attention_recompute --batch_size=${BS} --max_input_tokens ${TKI} --max_new_tokens ${TKO} 
Error:
File "/software/users/kkumar/work/optimum-habana-fork/optimum/habana/transformers/generation/utils.py", line 1439, in generate
result = self._sample(
File "/software/users/kkumar/work/optimum-habana-fork/optimum/habana/transformers/generation/utils.py", line …
=> Fix: Adjust recipe to fit within QueueComputeScal HBM global memory size limit

README.md
in the Diffusers example, the ouputs= called "generator" function which is not defined in the example. Replacing with the "pipeline" object works
=> Update README.md - correction in diffusers example

examples/language-modeling/llama3_ds_zero1_config.json
Update Deepspeed-zero1 config to align with recommended settings (https://docs.habana.ai/en/latest/PyTorch/DeepSpeed/DeepSpeed_User_Guide/DeepSpeed_User_Guide.html#integrating-deepspeed-with-gaudi)
Configure the throughput timer to be unsynchronized
Configure contiguous_gradients=false
=> Update DS config to align with recommended settings

optimum/habana/transformers/training_args.py
The default value of option torch._dynamo.config.cache_size_limit is 8
This default value might be too small, often leading to out-of-memory (OOM) errors when dynamo compiles certain models. We need to an option in optimum-habana to increase this value to prevent OOM.
=> Add dynamo cache size limit option

optimum/habana/transformers/models/mixtral/modeling_mixtral.py
=> Fix graph breaks in Mixtral (#65)

optimum/habana/transformers/models/deepseek_v2/modeling_deepseek_v2.py
Resolve the error of no gate_proj attribute during the Expert Parallelism of DeepSeek-V2
Currently, EP doesn't work in the latest OH main. It fails with the following error
```
[rank3]:     self.experts[idx * self.expert_chunk + i].gate_proj.weight.squeeze() for i in experts_range
[rank3]: AttributeError: 'NoneType' object has no attribute 'gate_proj'
```
This PR will resolve the Error by skipping the NonType object
=> Resolve 'NoneType' object has no attribute 'gate_proj' err when applying EP in DeepSeek-V2

optimum/habana/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py, optimum/habana/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py, optimum/habana/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_inpaint.py, tests/test_diffusers.py
Fix the incorrect output of sdxl inpaint.
Command:
`python text_to_image_generation.py     --model_name_or_path  diffusers/stable-diffusion-xl-1.0-inpainting-0.1     --base_image https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/diffusers/inpaint.png     --mask_image https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/diffusers/inpaint_mask.png     --prompts "concept art digital painting of an elven castle, inspired by lord of the rings, highly detailed, 8k"     --seed 42     --scheduler euler_discrete     --num_images_per_prompt 12     --batch_size 4     --image_save_dir ./xl2     --use_habana     --use_hpu_graphs     --gaudi_config Habana/stable-diffusion     --sdp_on_bf16     --bf16`
**Before:**
Images(only attach first four images …
=> Fix the incorrect output of sdxl inpaint

optimum/habana/accelerate/utils/modeling.py, optimum/habana/quantizers/bitsandbytes.py, optimum/habana/transformers/modeling_utils.py, optimum/habana/transformers/models/llama/modeling_llama.py, tests/test_bnb_inference.py, tests/test_bnb_qlora.py
This PR adds changes required to support usage of Bitsandbytes on Gaudi2/3. Note that feature is still experimental and Gaudi specific changes to Bitsandbytes repo have not been upstreamed yet, therefore unit-tests added will not work for now. We expect to get these working in near future.
=> Supports Bitsandbytes development on HPU (#117)

optimum/habana/transformers/models/llama/modeling_llama.py
https://github.com/microsoft/DeepSpeed/commits/master/deepspeed/sequence/layer.py
With latest changes in DistributedAttention, we need to add batch_dim_idx and rotary_pos_emb to Distributed Attention.
This change brings changes to add the batch_dim_idx in line with new changes.
https://github.com/microsoft/DeepSpeed/commit/ffe0af23575c4f03a07408eacfc50b1a58781429
=> Add batch dim idx to support latest deepspeed DistributedAttention 

optimum/habana/transformers/training_args.py
Disabling the inline_inbuilt_nn_modules switch will restore ALBERT-XXL's performance to PyTorch 2.4 levels
=> Add the inline_inbuilt_nn_modules option 

optimum/habana/transformers/models/llama/modeling_llama.py
**Issue**: Low accuracy in Llama3.1-70B with eager/torch.compile mode
(Following details extracted from https://github.com/huggingface/transformers/issues/28685)
Use a number of transformers models that utilize arange for integer enumerations in the calculation of position embeddings with DeepSpeed zero.Init() and a low precision dtype (float16, bfloat16), and the generated embeddings will differ significantly from intended.
1) Using Llama as an example
t = torch.arange(self.max_seq_len_cached, device=device, dtype=self.inv_freq.dtype)
The inv_freq.dtype == float32. Single precision float can cover the required integer range for the enumeration (I believe it's in the 2k-8k range for Llama?).
2) However, when DeepSpeed zero.Init is used the init function patching will override the float …
=> Accuracy fix for llama3.1-70B in eager/torch.compile mode

examples/contrastive-image-text/README.md, tests/baselines/bridgetower_large_itm_mlm_itc.json, tests/baselines/clip_roberta.json, tests/test_examples.py
Align the CI test script to follow our latest QA test scripts/Readme
Change clip-roberta to torch-compile
Change bridgetower not to use fast_ddp
=> Change clip-roberta/bridgetower not to use fast_ddp

examples/sentence-transformers-training/paraphrases/README.md, examples/sentence-transformers-training/paraphrases/requirements.txt
Previously if you were following the README, you would run into `ModuleNotFoundError: No module named 'datasets'`. This PR fixes that by adding a `requirements.txt` with `datasets` and instructions in the README.
=> Adds requirements.txt to sentence transformers training paraphrases

optimum/habana/transformers/generation/utils.py, optimum/habana/transformers/modeling_utils.py
This PR addresses an issue with upgrade to transformers 4.48.2
- Added _prepare_inputs_for_generation overwriting GenerationMixin.prepare_inputs_for_generation to remove unused keys
- Added custom logic to filter out keys not used in the forward method
```sh
>>> GAUDI2_CI=1 RUN_SLOW=true python -m pytest tests/transformers/tests/models/roberta/ -s -v -k test_greedy_generate_dict_outputs
FAILED tests/transformers/tests/models/roberta/test_modeling_roberta.py::RobertaModelTest::test_contrastive_generate_low_memory - TypeError: RobertaForCausalLM.forward() got an unexpected keyword argument 'bucket_size'
```
The issue arises from a recent upgrade in the Transformers library, which revises the GenerationMixin.prepare_inputs_for_generation method to better handle models. This update also …
=> Add _prepare_inputs_for_generation

conftest.py, tests/baselines/fixture/tests/test_encoder_decoder.json, tests/baselines/fixture/tests/test_fp8_examples.json, tests/baselines/fixture/tests/test_fsdp_examples.json, tests/baselines/fixture/tests/test_image_to_text_example.json, tests/baselines/fixture/tests/test_openclip_vqa.json, tests/baselines/fixture/tests/test_pipeline.json, tests/baselines/fixture/tests/test_sentence_transformers.json, tests/baselines/fixture/tests/test_text_generation_example.json, tests/test_encoder_decoder.py, tests/test_fp8_examples.py, tests/test_fsdp_examples.py, tests/test_image_to_text_example.py, tests/test_openclip_vqa.py, tests/test_pipeline.py, tests/test_sentence_transformers.py, tests/test_text_generation_example.py
Implement a Baseline fixture to manage test case baselines via reference files instead of directly in the test code.
This allows for easier reference rebasing by simply passing the custom pytest option "--rebase" on the command-line to update the reference with the current test result.
It will also enable us to remove "baseline" from the test case signatures/names so they don't generate new signatures every time the baseline is updated or due to floating point precision differences from run-to-run.
A static/fixed test case signature ensures we can track the historical results of the test case in various tools/CI.
---
This is the first pull-request of multiple series to refactor how baselines are managed.  This PR is meant to specifically address the test cases that used "baseline" in the …
=> Implement baselines as a fixture and with simple rebase support

optimum/habana/trl/trainer/dpo_trainer.py
=> fix dpo crash in transformers 4.48

examples/image-to-text/run_pipeline.py
```Traceback (most recent call last):
File "/root/optimum-habana/examples/image-to-text/run_pipeline.py", line 414, in <module>
main()
File "/root/optimum-habana/examples/image-to-text/run_pipeline
.py", line 375, in main
generator(images, prompt=args.prompt, batch_size=args.batch_size, generate_kwargs=generate_kwargs)
File "/usr/local/lib/python3.10/dist-packages/transformers/pipelines/image_to_text.py", line 137, in call
return super().call(inputs, **kwargs)
File "/usr/local/lib/python3.10/dist-packages/transformers/pipelines/base.py", line 1343, in call
outputs = list(final_iterator)
File "/usr/local/lib/python3.10/dist-packages/transformers/pipelines/pt_utils.py", line 124, in next
item = next(self.iterator)
File "/usr/local/lib/python3.10/dist-packages/transformers/pipelines/pt_utils. …
```
=> Fix for Falcon image-to-text crash

optimum/habana/transformers/models/mixtral/modeling_mixtral.py
**Fixes** # (issue)
Segfault on Mixtral transformer test due to out-of-bound reference of experts Index in MOE block
- The test fails with changes to Sparse MOE block from docker build 1.20.0-301 
In this particular failing test, the expert parameter values do not align with the number of weight tensors provided to the MOE. Specifically, the test inputs are as follows:
Expert_max = 7 , number of experts being used in this test is 2.
Hence segmentation fault occurs when it tries to access experts of index range [2-7] as only 2 experts are available.
Changes made in PR:
- Update expert max to ( number of experts - 1 ) , as this is inclusive index range starts from 0.
=> Fix Experts Indexing in MoE for Mixtral: Align experts_max with Number of Available Experts

examples/text-generation/README.md, examples/text-generation/quantization_config/maxabs_quant_const_scales.json, examples/text-generation/run_generation.py, examples/text-generation/run_lm_eval.py, examples/text-generation/utils.py
=> Enable saving and loading FP8 model

examples/stable-diffusion/training/requirements.txt
- Add a missing `datasets` to the requirements for Stable Diffusion training
=> Add datasets to the requirements for Stable Diffusion training

tests/utils.py
Re-enable wav2vec-large model for speech_recognition test.  This is the only model that's enabled for the speech_recognition. 
<Module test_examples.py>
<UnitTestCase MultiCardAudioClassificationExampleTester>
<TestCaseFunction test_run_audio_classification_wav2vec2-base_multi_card>
<UnitTestCase MultiCardSpeechRecognitionExampleTester>
<TestCaseFunction test_run_speech_recognition_ctc_wav2vec2-large-lv60_multi_card>
=> Enable wav2vec-large model for speech_recognition test

optimum/habana/transformers/models/gemma2/modeling_gemma2.py
Fixed Gemma2 model error when saving pretrain.
Due to model.config has non-serializable type.
=> Fixed Gemma2 error when saving pretrain

examples/text-generation/quantization_config/unit_scale_quant.json, examples/text-generation/utils.py
* add changes for fix
* add keep_moduleon_host, modify quant json
* remove buffer check
* add llama 405 checks
* remove hardcoded path, reuse module on host check
* fix: undefined variable
* remove unused import
---------
=> Enable Llama 3.1 405B in FP8 (#124)

examples/audio-classification/README.md, examples/audio-classification/run_audio_classification.py, examples/speech-recognition/README.md, examples/speech-recognition/run_speech_recognition_ctc.py, optimum/habana/transformers/models/wav2vec2/modeling_wav2vec2.py, optimum/habana/transformers/training_args.py
User can select among the three attention implementations (Gaudi-specific fused sdpa, "plain" sdpa, or eager), using script arguments.
In the audio-classification and speech-recognition examples:
* for eager, pass --attn_implementation eager
* for "plain" sdpa, pass --attn_implementation sdpa --sdp_on_bf16
* for fused sdpa, pass --attn_implementation sdpa --use_flash_attention
=> Enable attention selection for wav2vec2

conftest.py, tests/test_bnb_inference.py, tests/test_bnb_qlora.py, tests/test_custom_file_input.py, tests/test_diffusers.py, tests/test_encoder_decoder.py, tests/test_examples.py, tests/test_feature_extraction.py, tests/test_fp8_examples.py, tests/test_fsdp_examples.py, tests/test_functional_text_generation_example.py, tests/test_image_to_text_example.py, tests/test_object_detection.py, tests/test_openclip_vqa.py, tests/test_sentence_transformers.py, tests/test_table_transformer.py, tests/test_text_generation_example.py, tests/test_video_llava.py, tests/test_video_mae.py, tests/test_zero_shot_object_detection.py, tests/utils.py
Add `--device` cli option to specify which CI device is
being tested.  If the cli option is not specified, then
we fallback to the usual GAUDI2_CI environment variable.
Finally, if neither is specified, then try to get the
device name automatically from the habana frameworks
API.
This setting is to prepare for gaudi3 specific (and
future devices) test cases and baseline references.
Eventually, we can deprecate the GAUDI2_CI environment
variable once the rest of the test framework is
migrated to the new device declaration.
=> Add device auto-discovery and cli option

optimum/habana/transformers/models/mixtral/modeling_mixtral.py
This is a temporary workaround to avoid segmentation fault during SFT training
- Added call_sparse_moe_op for training
- Added conditional logic to use call_sparse_moe_op during training to prevent segmentation faults.
- TODO: This is a temporary solution. Remove this section after the issue is fixed.
The example from `examples/trl` with fewer steps here for faster reproduction.
main
```sh
>>> DEEPSPEED_HPU_ZERO3_SYNC_MARK_STEP_REQUIRED=1 PT_HPU_LAZY_MODE=1 python ../gaudi_spawn.py --world_size 4 --use_deepspeed sft.py   --model_name_or_path mistralai/Mixtral-8x7B-Instruct-v0.1     --dataset_name "philschmid/dolly-15k-oai-style"     --subset 'data/'  --streaming False     --deepspeed ../language-modeling/llama2_ds_zero3_config.json     --output_dir="./model_mixtral" …
```
=> [1.20.0] Temporary workaround to avoid segmentation fault

examples/sentence-transformers-training/nli/README.md, examples/sentence-transformers-training/nli/ds_config.json, examples/sentence-transformers-training/sts/README.md, examples/sentence-transformers-training/sts/ds_config.json
This PR will fix the restart issue in intel Gaudi3 system because of memory/bandwidth requirement. Here we will use the deepspeed Zero3 stage in ds_config.json file instead of stage2 for deepspeed to further relax the requirement which is verified without restart issue. 
Thanks.
=> Fix Sentence Transformer STS restart issue

optimum/habana/transformers/modeling_utils.py
Importing lm_eval stuffs will break the link between transformers.generation.GenerationConfig andtransformers.GenerationConfig.
You can reproduce it with code below.
```Python
from lm_eval import evaluator, utils
from optimum.habana.transformers.modeling_utils import adapt_transformers_to_gaudi
adapt_transformers_to_gaudi()
import transformers
print('=======', transformers.GenerationConfig)
print('=======', transformers.generation.GenerationConfig)
```
=> fix broken link for GenerationConfig

optimum/habana/diffusers/pipelines/pipeline_utils.py, optimum/habana/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_mlperf.py
Fixes issue with Transformers 4.49.0 not loading assigned `dtype` in some diffusers components
Transformers release 4.49.0 has an issue that it fails to properly load assigned component dtype for some components.
This bug was created here:
https://github.com/huggingface/transformers/blob/v4.49.0/src/transformers/modeling_utils.py#L1461
```python
torch_dtype = kwargs.pop("torch_dtype", config.torch_dtype)
```
Which changed from older transformers:
https://github.com/huggingface/transformers/blob/v4.46.3/src/transformers/modeling_utils.py#L1508
```python
torch_dtype = kwargs.pop("torch_dtype", torch.get_default_dtype())
```
This bug has been fixed since in 4.50.0dev here:
https://github.com/huggingface/transformers/pull/36335
@regisss If we will still update Optimum-Habana transformers to …
=> Workaround for Transformers 4.49.0 component loading dtype issue

optimum/habana/distributed/contextparallel.py, optimum/habana/transformers/models/llama/modeling_llama.py, optimum/habana/transformers/trainer.py
- Update the GaudiTrainer to better match with with Transformers 4.48.3 with minor enhancement from 4.49.0
- Remove the `get_batch_samples_transformers`
- Implemented `get_num_items_in_batches` to calculate the number of items in each batch for all epochs during training.
- Added `get_iterator_batch_samples` to retrieve batch samples from an iterator. 
- Moved the calculation of `num_items_in_batches` outside the training loop to recover performance lost. This feature should be up streamed to Transformers branch.
- Update llama model loss computation
- Simplified loss computation by using a configurable loss function.
- Replaced the inline loss computation logic with a call to self.loss_function.
- Introduced ForCausalLMContextParallelLoss for context parallel loss computation.
- Updated …
=> [Transformers future] Loss Computation for Compatibility with Transformers 4.48.3

optimum/habana/accelerate/accelerator.py
Seems to be a better approach due to known issue with moving view tensors to device within FSDP: https://github.com/pytorch/pytorch/issues/147321
Also PyTorch recommendation in FSDP tutorial does it like that:
https://pytorch.org/tutorials/intermediate/FSDP_tutorial.html
```
model = Net().to(rank)
model = FSDP(model)
```
=> Move model to device before wrapping with FSDP

conftest.py
Fix bug introduced by #1787 that causes the follow error when running `GAUDI2_CI=1 RUN_SLOW=true python -m pytest tests/transformers/tests/models/ -s -v`:
```
________________________________________________________________________________________________________________ ERROR collecting tests/transformers/tests/models/wav2vec2/test_modeling_wav2vec2.py _________________________________________________________________________________________________________________
ImportError while importing test module '/root/optimum-habana/tests/transformers/tests/models/wav2vec2/test_modeling_wav2vec2.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.10/importlib/__init__.py:126: in import_module
return _bootstrap._gcd_import(name[level:], package, …
```
=> WA: conftest do not overshadow tests/transformers/tests

conftest.py
This change fixes a problem with deepspeed test_examples.
`torch_hpu.get_device_name()` has been moved to a separate process, because it occupies a device and doesn't release it.
For tests what work in a separate process if there's a need for all devices not all of them will be available due the occupation from current pytest process.
=> Conftest: get_device_name() without device occupation

tests/test_trainer.py
PR created to discuss regression on test 
python -m pytest tests/test_trainer.py -v -s -k test_gradient_accumulation_loss_alignment_with_model_loss
**AssertionError: 1.2642000000000007 not greater than 1.5 : Difference 1.2642000000000007 is not greater than 1.5**
=> update target value

optimum/habana/transformers/models/qwen2_vl/modeling_qwen2_vl.py
In upstream, supporting static cache for this model is temporarily set to False (https://github.com/huggingface/transformers/blame/752ef3fd4e70869626ec70657a770a85c0ad9219/src/transformers/models/qwen2_vl/modeling_qwen2_vl.py#L941). We will set it to true here to allow the following test to run
`python3 /root/optimum-habana/examples/image-to-text/run_pipeline.py --model_name_or_path Qwen/Qwen2-VL-2B-Instruct --batch_size 1 --max_new_tokens 20 --ignore_eos --use_hpu_graphs --bf16 --sdp_on_bf16 --output_dir /tmp/tmp_26vvp09`
If not, we get the following value error
```   
File "/usr/local/lib/python3.10/dist-packages/optimum/habana/transformers/generation/utils.py", line 1033, in _prepare_cache_for_generation
raise ValueError(
ValueError: This model does not support …
```
=> set support static cache for qwen2

optimum/habana/transformers/models/gpt_neox/modeling_gpt_neox.py, tests/transformers/tests/models/gpt_neox/test_modeling_gpt_neox.py
This PR fixes the following pytest failures: 
- The `_reorder_cache` has been removed from gpt_neox in HF PR: https://github.com/huggingface/transformers/pull/35610 and causing the following `FAILED tests/transformers/tests/models/gpt_neox/test_modeling_gpt_neox.py::GPTNeoXModelTest::test_beam_search_generate_dict_outputs_use_cache - NotImplementedError: Make sure that a _reorder_cache function is correctly implemented in`
- ` tests/transformers/tests/models/gpt_neox/test_modeling_gpt_neox.py::GPTNeoXModelTest::test_cached_forward_with_and_without_attention_mask - AssertionError: This test assumes the model to have the SDPA implementation for its attention calculations.`
```bash  
GAUDI2_CI=1 RUN_SLOW=true python -m pytest tests/transformers/tests/models/gpt_neox/ -s -v -k …
```
=> fea(): pytest fixes for gpt_neox (v4.49)

tests/transformers/tests/test_modeling_common.py
Miroring the HF 4.49 changes [here ](https://github.com/huggingface/transformers/blob/v4.49-release/tests/test_modeling_common.py#L2326)for this test. 
```
GAUDI2_CI=1 RUN_SLOW=true python -m pytest tests/transformers/tests/models/ -s -v -k test_tied_weights_keys
```
```
=================================================================================================================================== 1 failed, 17 passed, 1417 deselected, 15 warnings in 2.06s ===================================================================================================================================
```
```
======================================================================================================================================== 18 passed, 1417 deselected, 15 warnings in 2.00s …
```
=> fea(): updated test_tied_weights_keys pytest for 4.49

tests/baselines/fixture/tests/test_encoder_decoder.json, tests/test_text_generation_example.py
In text generation slow tests:
* Updated reference accuracy for tests/test_encoder_decoder.py::TestEncoderDecoderModels::test_text_summarization_bf16[t5-3b-Habana/t5-2-1]
* Skipped 3 tests for deprecated models
=> Slow test updates

optimum/habana/transformers/models/mllama/modeling_mllama.py
Token idx is a tensor and when used within python slicing, it internally calls torch's .item() function. This is unnecessary and slows down the workload. So we replace it with token idx cpu which is already an integer and perfect for this.
=> Use token_idx_cpu int instead of token_idx tensor in slicing (#157)

examples/language-modeling/run_clm.py
Workaround for issue: https://github.com/huggingface/transformers/issues/36258
Reproducing with chatglm3 model:
`pytest tests/test_examples.py -v -s -k test_run_clm_chatglm3-6b_deepspeed`
If `torch_dtype is None`, then we check if this value can be loaded from a model's config. So it replicates behavior of `auto`.
Maybe it's better to modify the test itself to directly pass `torch_dtype=bfloat16` to the models' args.
=> [transformers_4_49] Fix for AutoModelForCausalLM.from_pretrained()

optimum/habana/transformers/models/deepseek_v3/modeling_deepseek_v3.py
Author:    Jay Gala <jaygala@habana.ai>
Logits are converted to float32. This increases memory requirements and is not required for models running bf16
=> Keep logits in bf16 (#182)

optimum/habana/transformers/models/gpt2/modeling_gpt2.py
This PR fixes pytest failure that causes runtime error - Incompatible input shapes, broadcast not possible in test_gpt2_reorder_and_upcast_attn
GAUDI2_CI=1 RUN_SLOW=true python -m pytest tests/transformers/tests/models/gpt2/ -s -v -k test_gpt2_reorder_and_upcast_attn
FAILED tests/transformers/tests/models/gpt2/test_modeling_gpt2.py::GPT2ModelTest::test_gpt2_reorder_and_upcast_attn - RuntimeError: Incompatible input shapes, broadcast not possible. Tensor1 Size: 32 4 14 Tensor2 Size: 32 7 14
=> Fixes pytest runtime error - Incompatible input shapes, broadcast not possible

optimum/habana/transformers/models/llama/modeling_llama.py
Provide a fix for the error:
`AttributeError: 'GaudiLlamaAttention' object has no attribute 'max_position_embeddings'`
When running:
```
python ../gaudi_spawn.py --use_deepspeed --world_size 8 run_generation.py --model_name_or_path meta-llama/Llama-2-70b-hf --use_hpu_graphs --limit_hpu_graphs --use_kv_cache --bf16 --trim_logits --attn_softmax_bf16 --bucket_size=128 --bucket_internal --batch_size 8 --max_input_tokens 40960 --max_new_tokens 5120 --use_flash_attention --flash_attention_recompute --flash_attention_causal_mask --book_source
```
Tested on G3
In `main` we get:
```
Stats:
-----------------------------------------------------------------------------------
Input tokens
Throughput (including tokenization) = 281.69667986175455 tokens/second
Memory allocated                    = 22.66 …
```
=> Fix for GaudiLlamaAttention' object has no attribute 'max_position_embeddings' 

examples/text-generation/run_generation.py, examples/text-generation/utils.py, optimum/habana/utils.py
- Updated logic to prevent implicit setting of flash_attention_fast_softmax
- Users can now explicitly set flash_attention_fast_softmax to False to prevent it from being automatically set to True when use_flash_attention is enabled.
- Added warning messages to inform users of implicit changes to argument values
=> Allow explicit control over flash_attention_fast_softmax setting

tests/baselines/fixture/tests/test_examples.json
We see random failure in pytest of test_run_image2text_lora_finetune_llava-1.5-7b-hf_multi_card due to minor difference in eval_accuracy value. Since currently the reference value is 0.2122, to avoid random failures, the new value is set to 0.21 .This resolves the issue. I have tested this few times and I did not see the issue.
Before:
eval_accuracy:actual = 0.20916600712249245
gaudi2.eval_accuracy:ref    = 0.2122
ERROR    root:test_examples.py:785 eval_accuracy: ge(0.20916600712249245, 0.99 * 0.2122)
After:
eval_accuracy:actual = 0.20938339842684026
gaudi2.eval_accuracy:ref    = 0.21
PASSED
This fixes the random failure in pytest.
=> Adjust precision of eval_accuracy to avoid random failure in pytest for lora finetune Llava image-to-text

optimum/habana/transformers/models/llama/modeling_llama.py
Fixes bug in Llama model when internal bucketing is enabled without reuse cache option. 
When these options are enabled in Lazy HPU graph mode, HPU graph logic will fail to capture changes in the input padding on the fly (e.g. by changing `max new tokens`) and will try to replay old graph (with old padding), causing error.
Here is an example which will reproduce the issue:
```python
#!/usr/bin/env python
import torch
import transformers
from optimum.habana.transformers.modeling_utils import adapt_transformers_to_gaudi
from habana_frameworks.torch.hpu import wrap_in_hpu_graph
adapt_transformers_to_gaudi()
model_id = "meta-llama/Llama-3.1-8B-Instruct"
model_kwargs = {
"torch_dtype": torch.bfloat16,
"use_cache": True,
}
generation_config = transformers.AutoConfig.from_pretrained(model_id, …
```
=> Fix llama internal bucketing issue

optimum/habana/accelerate/accelerator.py
This reverts commit 379524c1c77a66cdfbd0d68606aa8a5def15bda0.
Unfortunately, this commit is causing OOM issues when running:
```
PT_HPU_AUTOCAST_LOWER_PRECISION_OPS_LIST=ops_bf16.txt PT_HPU_LAZY_MODE=0 \
python3 ../gaudi_spawn.py --world_size 8 --use_mpi run_lora_clm.py \
--model_name_or_path meta-llama/Llama-2-70b-hf \
--dataset_name tatsu-lab/alpaca \
--bf16 True \
--output_dir ./lora_out \
--max_seq_len 2048 \
--gradient_checkpointing \
--per_device_train_batch_size 5 \
--save_strategy no \
--learning_rate 0.0004 \
--warmup_ratio 0.03 \
--lr_scheduler_type "constant" \
--logging_steps 1 \
--dataset_concatenation \
--do_train \
--use_habana \
--throughput_warmup_steps 3 \
--lora_rank 4 \
--lora_target_modules "q_proj" "v_proj" "k_proj" "o_proj" \
--attn_softmax_bf16 True \ …
```
=> Revert "Move model to device before wrapping with FSDP (#1801)"

optimum/habana/diffusers/pipelines/stable_diffusion_3/pipeline_stable_diffusion_3.py
SD3 pipeline was running softmax kernels with inconsistent tensor shapes leading to low utilization. Observed from the perf lib logs as shown below
`The Geometry of the input and the kernel geometry are inconsistent in softmax_hf8 on account of which the kernel utilization is less than 50 percent  and equals to 25.000000 percent`
This PR addresses the issue of low utilization by padding prompt embeddings to a shape compatible with softmax_hf8 kernels, leading to better utilization and faster execution of diffusion attention process. 
-  Padding prompt embeddings gave a performance increase of 21%
The below table shows the performance change from default execution which uses the regular prompt embedding shape of 333 vs the padded version using 384.
<html …
=> Optimize SD3 Pipeline : Padding prompt Embeddings for softmax_hf8 compatibility and Efficient Utilization

optimum/habana/transformers/models/llama/modeling_llama.py
Without this small fix, there is an OOM issue with multiple models.
To reproduce it:
```
cd optimum-habana &&
pip install -e . &&
cd optimum-habana/examples/text-generation &&
pip install -r requirements.txt && 
pip install -r requirements_lm_eval.txt &&
HF_DATASETS_TRUST_REMOTE_CODE=true QUANT_CONFIG=optimum-habana/examples/text-generation/quantization_config/maxabs_measure.json  TQDM_DISABLE=1 python3 ../gaudi_spawn.py --use_deepspeed --world_size 2 run_lm_eval.py --model_name_or_path meta-llama/Llama-2-70b-hf --warmup 0 --use_hpu_graphs -o test_results_measure.json --bf16 --batch_size 8 --use_kv_cache --trim_logits --attn_softmax_bf16 --bucket_size=128 --bucket_internal --trust_remote_code --tasks hellaswag lambada_openai piqa winogrande
```
Accuracy is the same
=> Llama2 70 b OOM fix

examples/stable-diffusion/training/README.md, examples/stable-diffusion/training/download_train_datasets.py
This PR improves download script for diffusers training samples.
If we already ran `./download_train_datasets.py` current script would raise error that destination patch already exists:
```bash
./download_train_datasets.py
Fetching 6 files: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:00<00:00, 39.09it/s]
Fetching 5 files: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 35.63it/s]
File "/root/optimum-habana_transformers_future/examples/stable-diffusion/training/./download_train_datasets.py", line 48, in …
```
=> Improve diffusers training download script

examples/stable-diffusion/README.md
Updates FP8 diffusers README. 
If SD3 or FLUX pipelines run as a service (e.g., via API), we need to avoid re-quantizing an already FP8-quantized pipeline in memory as this may cause errors. This PR adds clarifying notes to prevent misuse.
=> Update FP8 diffusers doc

examples/question-answering/run_qa.py
Reintroducing https://github.com/huggingface/optimum-habana/pull/1830/files from @skaulintel, as having a more generic fix is causing OOM in other scenarios, but totally removing it, it will cause 
`pytest tests/test_fsdp_examples.py::test_fsdp_bf16[bert-base-uncased-Habana/bert-base-uncased-question-answering-24-8-run_qa.py-full_shard]` to fail
=> Move model to device before wrapping with fsdp 

tests/baselines/fixture/tests/test_examples.json
With the new changes from [PR-1869](https://github.com/huggingface/optimum-habana/pull/1869) the pytest test_run_clm_gpt2-xl_deepspeed for clm gtp2_xl is failing due to train_runtime. 
`root:test_examples.py:785 train_runtime: le(236.54, 1.05 * 206.5775)`
Reference train_runtime = 216.90
The test should be updated with new reference train_runtime to avoid future failures. This is the new train_runtime results on G2 measured with PR-1869. Once PR-1869 is merged, this change should also be merged to avoid failures.
Command tested:
`RUN_SLOW=1 python -m pytest test_examples.py -v -s -k "test_run_clm_gpt2-xl_deepspeed"`
Results without PR-1869:
```
***** train metrics *****
epoch                       =        2.0
max_memory_allocated (GB)   =      34.83
memory_allocated (GB)       = …
```
=> Update train_runtime reference number for clm gpt2_xl to fix pytest failure

tests/baselines/fixture/tests/test_examples.json, tests/configs/examples/gemma_2b_it.json
The learning rate for gemma2b mpi and deepspeed should be replaced to be more consistent with one card version and have good perplexity.
8x G2: 
```
epoch                       =        2.0
max_memory_allocated (GB)   =      64.53
memory_allocated (GB)       =      22.22
total_flos                  = 54434080GF
total_memory_available (GB) =      94.62
train_loss                  =     5.0075
train_runtime               = 0:01:23.76
train_samples               =       2395
train_samples_per_second    =     76.627
train_steps_per_second      =        2.4
***** eval metrics *****
epoch                           =        2.0
eval_accuracy                   =      0.482
eval_graph_compliation_duration =      1.493
eval_loss                       =     2.5507
eval_runtime                    = …
```
=> Fix gemma2b-it perplexity

examples/image-to-text/run_pipeline.py, optimum/habana/transformers/generation/configuration_utils.py, optimum/habana/transformers/generation/utils.py, optimum/habana/transformers/models/mllama/modeling_mllama.py
Use the `--logits_bf16` parameter to keep logits in BF16; otherwise, fall back to the default path.
=> Optimize memory utilization by keeping logits in BF16.

optimum/habana/transformers/models/mllama/modeling_mllama.py
* [Llama-vision] Add support for Fused RMS Norm
* fix constructor
* add reference in forward
* fix formatting
* Update optimum/habana/transformers/models/mllama/modeling_mllama.py
* organize imports
---------
JH...!
=> [Llama-vision] Add support for Fused RMS Norm (#161)

tests/transformers/tests/models/falcon/test_modeling_falcon.py
Unskipping revealed that SW-209093 is still not fixed.
This PR skips a test that has no chance of passing (due to known and not fixed bug).
=> Skipping falcon rope scaling test (#221)

examples/text-generation/utils.py
This PR caps the max pos embeds limit to 8k for the llama family of models. Earlier this check was for just one llama 3 model with a specific config. Now it applies to all llama family models and can be extended to others in the future.
Capping the max pos embeds for models in which we dont support higher context len saves memory and prevents OOM in bigger models like llama 3.1 405B
=> Limit max pos embeds to 8k to prevent OOM (#227)

examples/image-to-text/run_image2text_lora_finetune.py, examples/language-modeling/run_clm.py, examples/language-modeling/run_lora_clm.py
Fixes #1930 
1. Fix `--save_last_ckpt` to work always even when --save_strategy "no".
2. Call trainer._save_checkpoint() for `run_image2text_lora_finetune.py` when `--save_last_ckpt` is set
```
python3 run_image2text_lora_finetune.py     --model_name_or_path meta-llama/Llama-3.2-11B-Vision-Instruct     \
--dataset_name nielsr/docvqa_1200_examples     \
--bf16 True     \
--output_dir ./model_lora_llama     \
--num_train_epochs 1     \
--per_device_train_batch_size 2     \
--per_device_eval_batch_size 2     \
--gradient_accumulation_steps 8     \
--weight_decay 0.01     \
--logging_steps 25     \
--eval_strategy "no"     \
--save_strategy "no"     \
--learning_rate 5e-5     \
--warmup_steps  50     \
--lr_scheduler_type "constant"     \
--input_column_names 'image' 'query'     \ …
```
=> Fix --save_last_ckpt if --save_strategy no is set

setup.py, tests/baselines/fixture/tests/test_bnb_inference.json, tests/baselines/fixture/tests/test_bnb_qlora.json, tests/test_bnb_inference.py, tests/test_bnb_qlora.py
1. Pad the examples up to max_seq_len of 1024
2. Increase the max_steps (from 5 to 50) and eval_steps (from 3 to 10). Set throughput-related arguments (adjust_throughput, throughput_warmup_steps)
4. Update the fine-tuning test name
5. Also, adjust the reference "eval loss" value for fine-tuning test and "output" for inference test.
Additional updates
6. Enable the eager mode for the test (disable the torch.compile mode for now).
7. Add new requirement for installing the bitsandbytes (from https://github.com/bitsandbytes-foundation/bitsandbytes/tree/multi-backend-refactor)
=> Pad the examples for QLoRa finetuning test

setup.py, tests/test_bnb_inference.py, tests/test_bnb_qlora.py
Instead of adding bitsandbytes (bnb) requirement to setup.py, move it to bnb test files (tests/test_bnb_qlora.py, tests/test_bnb_inference.py). 
Details:
1) Because for HPU, bitsandbytes loads the CPU binaries (https://github.com/bitsandbytes-foundation/bitsandbytes/blob/multi-backend-refactor/bitsandbytes/cextension.py#L73), which are not required. Failure to load these binaries throws OSError (OSError: /usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cpu.so: cannot open shared object file: No such file or directory) for other tests.
2) For now, we move the BNB installation to the above-specified tests. And **both of these tests passed**.
3) Later, we'll try to upstream the fix to the bitsandbytes repo.
=> Move bitsandbytes requirements from setup.py to bnb tests

optimum/habana/transformers/training_args.py
Change-Id: Id7a21c0c1e014e9dc8c503c645a252ad4da136fb
This is an option from https://github.com/pytorch/pytorch/pull/142829 to not specialize int from nn.Modules under torch.compile mode
=> Support allow_unspec_int_on_nn_module

examples/text-generation/run_generation.py
Issue:
For the Llama2 7B Dynamic mode, with padding="max_length", the tokenizer produces 'input_ids' without padding and having actual tokens only in the list. This is expected and works fine.
For the Llama3.1 8B Dynamic mode, with padding="max_length", the tokenizer produces 'input_ids' with padding and having 128K tokens (which is the max model input length. This is not expected.
Fix: The tokenizer configuration has been changed to address this issue.
=> Tokenizer config fix for dynamic mode (#144)

optimum/habana/transformers/trainer.py, optimum/habana/transformers/training_args.py
Change-Id: Ic15cd7d04b93a4674425f4752ef31eedb64afe87
We add an option to compile from the 2nd iteration. This can be helpful when the dynamic graph contains some opaque operators which cannot be inspect during the tracing.
=> Support compile from the 2nd iteration

examples/stable-diffusion/training/README.md, examples/text-generation/README.md
Updates documentation with few fixes:
1. Fixes incomplete paths to multi card spawn script in `examples/stable-diffusion/training/README.md`
2. Fixes example of using PEFT adapter with LLM (the current example does not illustrate the lora fine tuned functionality)
Regarding PEFT LLM example, we currently have:
```bash
python run_generation.py \
--model_name_or_path meta-llama/Llama-2-7b-hf \
--use_kv_cache \
--batch_size 1 \
--bf16 \
--max_new_tokens 100 \
--prompt "Here is my prompt" \
--peft_model yard1/llama-2-7b-sql-lora-test \
--sdp_on_bf16
```
This supposed to be showcasing SQL fine-tuned LoRA model to help generate correct SQL command given a specially formatted question.  The prompt  "Here is my prompt" does not showcase it.
We can instead adopt example from …
=> Fix READMEs - SD paths and LLM PEFT example

examples/text-generation/run_generation.py
for example/text-generation/run_generation.py:
Add TTFT/TPOT/E2E latency output for each generation, and average latency at the end of output and result.
Fixes # https://github.com/huggingface/optimum-habana/issues/1952 (issue)
=> add average latency metrics

conftest.py, tests/test_bnb_inference.py, tests/test_bnb_qlora.py
Move bitsandbytes installation (required for qlora tests: tests/test_bnb_qlora.py, tests/test_bnb_inference.py) to conftest.py
Details:
1) pytest runs the pytest_configure function before executing the test itself (https://github.com/huggingface/optimum-habana/blob/main/conftest.py#L118)
2) Now, this function imports optimum.habana, which imports transformers.utils, which checks whether specific packages (for example: torch, peft, bitsandbytes) are installed (and transformers saves this state). 
3) Bitsandbytes is installed later (during the test execution) because the transformer has not updated its state, and the QLORA tests fail for the above reason. 
4) This issue does not occur in internal (OH-fork) repo because of the absence of the pytest_configure function from conftest.py file
5) …
=> Bitsandbytes installation for qlora tests

Makefile, tests/test_examples.py
Allows for using cached datasets (http://images.cocodataset.org) in slow tests.
=> Use data cache in slow_tests_8x (#214)

examples/stable-diffusion/training/train_dreambooth_lora_flux.py, tests/test_diffusers.py
Fixes flux training script issue caused by updated accelerator #1876 
Error before fix:
```
File "/root/optimum-habana_main/examples/stable-diffusion/training/train_dreambooth_lora_flux.py", line 1142, in <module>
main(args)
File "/root/optimum-habana_main/examples/stable-diffusion/training/train_dreambooth_lora_flux.py", line 839, in main
train_dataset = DreamBoothDataset(
File "/root/optimum-habana_main/examples/stable-diffusion/training/train_dreambooth_lora_flux.py", line 480, in __init__
prompt_embeds, pooled_prompt_embeds, text_ids = self.convert_to_torch_tensor(
File "/root/optimum-habana_main/examples/stable-diffusion/training/train_dreambooth_lora_flux.py", line 538, in convert_to_torch_tensor
prompt_embeds = np.array(prompt_embeds).reshape(self.max_sequence_length, …
```
=> Fix FLUX fine-tuning script

tests/baselines/fixture/tests/test_encoder_decoder.json
Feel free to replicate the value on Gaudi3, running:
```
git clone -b v1.17.0 https://github.com/huggingface/optimum-habana.git
cd optimum-habana/
pip install -e .
python -m pip install .[tests]
pip install pytest
export RUN_SLOW=1
```
```
python -m pytest tests/test_encoder_decoder.py::TestEncoderDecoderModels::test_text_translation_bf16[t5-small-Habana/t5-2-1] --device gaudi3 --log-cli-level 20 -v -s
```
for tag **v1.17.0**
The previous reference number was never achieved on the previous release (v1.16.0), at least on the machines I run the test.
On **v1.16.0** the equivalent command is:
```
export GAUDI2_CI=1
python -m pytest tests/test_encoder_decoder.py::TestEncoderDecoderModels::test_text_translation_bf16[t5-small-Habana/t5-2-1] --log-cli-level 20 -v -s
```
Test is for Lazy only
=> Update t5-small samples_per_second value

optimum/habana/transformers/models/qwen2_vl/modeling_qwen2_vl.py
Fixes bug:
[rank1]:   File "/usr/local/lib/python3.10/dist-packages/optimum/habana/transformers/models/qwen2_vl/modeling_qwen2_vl.py", line 623, in forward
[rank1]:     inputs_embeds[image_mask] = image_embeds
[rank1]: RuntimeError: a view of a leaf Variable that requires grad is being used in an in-place operation.
New tests are not required.
This test still passes.
GAUDI2_CI=1 RUN_SLOW=1 python -m pytest tests/test_image_to_text_example.py -v -s -k Qwen2-VL
=> Fix issue with in-place operation with requires grad with modeling_qwen2_vl.py

Makefile
This PR is needed to enforece the lazy mode in diffuser starting on 1.21 release. 
It at least addresses the following failures on 1.21-5XX driver/container
```
RUN_SLOW=true python -m pytest --device gaudi2 -s -v tests/test_diffusers.py -k test_attention_slicing_forward_pass
```
```
FAILED tests/test_diffusers.py::StableDiffusionInpaintPipelineTests::test_attention_slicing_forward_pass - RuntimeError: HPUGraph class is available in lazy mode only.
FAILED tests/test_diffusers.py::StableDiffusionXLInpaintPipelineTests::test_attention_slicing_forward_pass - RuntimeError: HPUGraph class is available in lazy mode only.
```
with PR changes, the above-test pass. 
=> fea(): Added PT_HPU_LAZY_MODE=1 for diffuser tests

examples/stable-diffusion/training/README.md, examples/stable-diffusion/training/train_dreambooth_lora_flux.py, optimum/habana/diffusers/models/attention_processor.py, optimum/habana/diffusers/pipelines/flux/pipeline_flux.py, optimum/habana/diffusers/pipelines/flux/pipeline_flux_img2img.py
Speeds up FLUX training **more than 2x** by using **Gaudi optimized attention**.
FLUX train speed **before fix** (1xG2 w/ 1.20.0-543 release) = 5.19s/it
```bash
05/01/2025 17:29:03 - INFO - accelerate.checkpointing - Optimizer state saved in dog_lora_flux/checkpoint-500/optimizer.bin
05/01/2025 17:29:03 - INFO - accelerate.checkpointing - Scheduler state saved in dog_lora_flux/checkpoint-500/scheduler.bin
05/01/2025 17:29:03 - INFO - accelerate.checkpointing - Sampler state for dataloader 0 saved in dog_lora_flux/checkpoint-500/sampler.bin
05/01/2025 17:29:03 - INFO - accelerate.checkpointing - Random states saved in dog_lora_flux/checkpoint-500/random_states_0.pkl
05/01/2025 17:29:03 - INFO - main - Saved state to dog_lora_flux/checkpoint-500
Steps: …
```
=> Speed up FLUX training over 2x with Gaudi optimized attention

optimum/habana/accelerate/accelerator.py
In [SW-207456](https://jira.habana-labs.com/browse/SW-207456) , it is found the multi-node training would crash at the begining when `dataloader_num_workers` is set to larger than 0.
According to the [official habana document](https://docs.habana.ai/en/latest/PyTorch/Getting_Started_with_PyTorch_and_Gaudi/Getting_Started_with_PyTorch.html?highlight=spawn#torch-multiprocessing-for-dataloaders), it is required to change the start method to spawn or forkserver using the PyTorch API. Thus this PR updates the API for Accelerate Dataloader.
[SW-207456](https://jira.habana-labs.com/browse/SW-207456)
=> Switch to Spawn in PyTorch DataLoader when num_worker>0

requirements.txt
There are duplicate entries in requirements.txt left from the 1.16 merge.
=> Remove duplicates from requirements.txt

optimum/habana/accelerate/accelerator.py
=> Hot fix regional compilation

examples/text-generation/README.md, examples/text-generation/mbxp_evaluation/evaluation_setup/ubuntu.sh, examples/text-generation/mbxp_evaluation/setup.sh, examples/text-generation/run_generation.py
This commit implements accuracy.json generation. 
In order to generate inference responses for custom dataset simply run run_generation script with two parameters --dataset custom_dataset.pkl and --dataset_name custom.
Additionaly you can setup environment for mbxp dataset evaluation and evaluate responses by using mlcommon scripts.
Results from the evaluation of the mlcommon dataset, which is a combination of OpenOrca, GSM8K, and MBXP.
{
'rouge1': 45.4708,
'rouge2': 23.2887,
'rougeL': 30.3478,
'rougeLsum': 42.4501,
'gsm8k': 74.16,
'mbxp': 60.36,
'gen_len': 4243067,
'gen_num': 15000,
'gen_tok_len': 2808861,
'tokens_per_sample': 187.3
}
=> Enable mixtral 8x7b accuracy evaluation

optimum/habana/transformers/loss/__init__.py, optimum/habana/transformers/loss/loss_rt_detr.py, optimum/habana/transformers/modeling_utils.py
prevent cpu fallback in loss calculation
By default returned tensor is created on cpu. Moving to active device explicitly to avoid further fallbacks: these values then used to index hpu tensors, which causes cpu fallback for ```aten::index.Tensor_out```
=> rt-detr: optimize loss calculation

optimum/habana/accelerate/accelerator.py, optimum/habana/accelerate/utils/other.py
These are the same changes proposed in upstream accelerate in https://github.com/huggingface/accelerate/pull/3609.
Regional compilation was tested with accelerate's deepspeed testing suite: `RUN_SLOW=1 ACCELERATE_DYNAMO_BACKEND=inductor ACCELERATE_DYNAMO_USE_REGIONAL_COMPILATION=True pytest tests/deepspeed/test_deepspeed.py -s -vvvv`
=> Deepspeed regional compilation

optimum/habana/transformers/models/mixtral/modeling_mixtral.py
Logits only have to be converted to floats if we are computing the loss. This PR removes unnecessary conversion, resulting in some speed up.
**This PR should only be merged after upgrade to version 4.46.**
=> Don't upcast logits to float if not necessary

examples/text-generation/quantization_config/maxabs_quant_dynamic_quantization.json, examples/text-generation/quantization_config/maxabs_quant_dynamic_quantization_pts.json
This pull request adds two new configuration files for dynamic quantization in the `examples/text-generation/quantization_config` directory. These configurations specify different methods for scaling and quantizing model parameters.
**New dynamic quantization configurations:**
* [`examples/text-generation/quantization_config/maxabs_quant_dynamic_quantization.json`](diffhunk://#diff-18fb0c9fe1fdf297efb66b2574e8341e5eeed130caac00a211e401795789aab4R1-R13): Introduced a configuration file with the `ACT_MAXABS_PCS_POW2_WEIGHT_MAXABS_PTS_POW2_HW` scaling method, allowing dynamic quantization and specifying the `mlp` module in the allowlist.
* [`examples/text-generation/quantization_config/maxabs_quant_dynamic_quantization_pts.json`](diffhunk://#diff-289160e64f718dba101055a0bb1b0e345fe44d5f0a9f08 …
=> Bring back dynamic quantization files

examples/text-generation/run_generation.py
This pull request includes a small change to the `generate_dataset` function in `examples/text-generation/run_generation.py`. The change removes the call to `HabanaProfile.disable()` during the compilation stage, simplifying the function.
=> Remove unnecesary HabanaProfile.disable

examples/text-generation/requirements_lm_eval.txt, examples/text-generation/run_lm_eval.py
This pull request updates dependencies and refactors logging in the `examples/text-generation` module. The most important changes include upgrading the `lm-eval` library to its latest version and replacing the custom logger with Python's built-in logging module.
Dependency updates:
* [`examples/text-generation/requirements_lm_eval.txt`](diffhunk://#diff-31a8b5ee72c51acd69df94416def6e14afd17ee766ebee41ba3b1ac66bf4398aL1-R1): Upgraded `lm-eval` from version `0.4.7` to `0.4.8`.
Logging refactor:
* [`examples/text-generation/run_lm_eval.py`](diffhunk://#diff-f1cc242d23dabd24c924359e72d7eba31a9edc5c6a589ca3ab8438d7fad8589bR22): Added the `logging` module import to replace the custom logger.
* [`examples/text-generation/run_lm_eval.py`](diffhunk://#diff-f1cc242d23dabd24c924359e72d7eba31a9edc5c6a …
=> Upgrade to lm_eval==4.8.0

optimum/habana/transformers/generation/utils.py
This pull request includes a minor update to the `_sample` method in the `optimum/habana/transformers/generation/utils.py` file. The change ensures that the `torch.arange` function specifies the `device` as `"hpu"` for compatibility with Habana hardware.
* [`optimum/habana/transformers/generation/utils.py`](diffhunk://#diff-284d6c109e6788a4405e302113203f6b7e98be68afc7dd3d85b89c6329b9275eL2858-R2858): Updated the `mask` creation line in `_sample` method to use `torch.arange` with the `device="hpu"` argument for improved compatibility with Habana hardware.
=> Extra Content: enable accuracy benchmark using torch compile

setup.py, tests/test_image_to_text_example.py
The `THUDM/glm-4v-9b` model requires the `tiktoken` and `blobfile` packages. Currently, the test failed with:
```
File "/root/optimum-habana-fork/examples/image-to-text/run_pipeline.py", line 527, in <module>
main()
File "/root/optimum-habana-fork/examples/image-to-text/run_pipeline.py", line 286, in main
processor = AutoProcessor.from_pretrained(args.model_name_or_path, padding_side="left")
File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/processing_auto.py", line 362, in from_pretrained
raise ValueError(
ValueError: Unrecognized processing class in THUDM/glm-4v-9b. Can't instantiate a processor, a tokenizer, an image processor or a feature extractor for this model. Make sure the repository contains the files of at least one of …
```
=> Add missing test dependencies for image-to-text

examples/text-generation/requirements_awq.txt
This PR updates the transformers version constraint in text-generation/requirements.txt:
This change is required to align with updates introduced in [#2063](https://github.com/huggingface/optimum-habana/pull/2063), which upgraded the minimum supported transformers version to 4.51. Without this fix, certain classes such as AssistantVocabTranslatorCache used in text generation are not available, leading to import errors.
=> text-generation requirements fix for transformers upgrade 4.51

examples/text-generation/quantization_config/maxabs_quant_dynamic_quantization.json, optimum/habana/transformers/models/llama/modeling_llama.py
This pull request introduces changes to support dynamic quantization and improve dtype handling in specific tensor operations. The updates include the addition of a new quantization configuration file and modifications to the `get_k_proj_weight_dtype` method to handle specific dtype scenarios.
* Added a new configuration file, `maxabs_quant_dynamic_quantization.json`, to enable dynamic quantization using the `MAXABS_POW2_DYNAMIC` scale method. The file specifies quantization mode, scale format, and an allowlist for quantization targets (`mlp`). It also includes a path for dumping statistics.
* Updated the `get_k_proj_weight_dtype` method in `optimum/habana/transformers/models/llama/modeling_llama.py` to handle cases where `k_proj.weight.dtype` includes "float8" and `k_cache` is an …
=> Enable dynamic quantization

examples/trl/README.md
Currently, the trl example commands fail with the following error: `RuntimeError: Error when trying to cast Long to Int, Input values range [9223372036854775807, 9223372036854775807] exceeds Int range [-2147483648, 2147483647]` which is caused by lack of default support for Long in lazy mode. The `PT_ENABLE_INT64_SUPPORT` flag enables the Long support.
=> Use `PT_ENABLE_INT64_SUPPORT=1` for trl examples

Makefile, tests/test_image_to_text_example.py
Add slow_tests_image_to_text_example_2x group to align tests with correct platform configuration
=> Add groups to slow_tests_image_to_text_example v1.18

setup.py
This PR adds the bitsandbytes library to the test dependencies for text generation.
Starting from Transformers 4.51, loading some quantized models (especially with AutoModelForCausalLM.from_pretrained) may trigger runtime error
The issue can be reproduced in the slow test:
tests/test_text_generation_example.py::test_text_generation_bnb[unsloth/Meta-Llama-3.1-70B-bnb-4bit-1-20-False-True]
=> Add missing test dependency (bitsandbytes)

examples/audio-classification/requirements.txt, examples/text-generation/requirements.txt, examples/text-generation/requirements_lm_eval.txt
This pull request updates the `datasets` library version in multiple requirement files across the project to ensure compatibility with version `>= 3.0.2`. The changes standardize the version used across different examples and remove upper version constraints where applicable.
Library version updates:
* [`examples/audio-classification/requirements.txt`](diffhunk://#diff-46d365f6fa6b793318393522a7406ef27f034f9bb1a04ac3516a0a2849d6598fL1-R1): Updated `datasets` version from `>= 1.14.0, <= 2.19.2` to `>= 3.0.2`.
* [`examples/text-generation/requirements.txt`](diffhunk://#diff-6f40227d268fdd6ec065cd354c71cf9b11c762b375e4ade0e5146b37a9cdb5e1L1-R1): Updated `datasets` version from `== 2.19.2` to `>= 3.0.2`.
* [`examples/text-generation/requirements_lm_eval.txt`](diffhunk://#diff-31a8b5ee72c51acd6 …
=> Upgrade datasets to fix utf-8 encoding problem

examples/text-generation/run_generation.py
TF==4.51 introduced a bug:
https://github.com/huggingface/transformers/pull/37281
deepspeed is imported too early - this causes accelerator libraries (hpu/nvidia) load too early and that blocks our environment variables to be effective (they must be set before loading habanalabs). 
it was later fixed with TF==4.52:
https://github.com/huggingface/transformers/pull/37755
so next release will not be affected. Meanwhile we must move-away all libs loading transformers.trainer from global scope.
=> This PR fixes too early deepspeed initialization

optimum/habana/accelerate/accelerator.py, optimum/habana/accelerate/utils/other.py
This pull request refactors and enhances the regional compilation functionality for Habana Gaudi accelerators. It introduces new utility functions for modular compilation, improves code organization, and updates the `GaudiAccelerator` class to use these utilities. The changes aim to optimize compilation workflows, particularly for large models and DeepSpeed integration.
* **Utility Functions for Compilation**: Added new functions in `optimum/habana/accelerate/utils/other.py` to support regional compilation, including `compile_regions`, `compile_regions_deepspeed`, `is_compiled_module`, `has_compiled_regions`, `is_repeated_blocks`, and `has_repeated_blocks`. These utilities streamline the compilation process and provide checks for repeated blocks and compiled regions.
* **Integration of …
=> Deepspeed regional compilation (#2021)

optimum/habana/transformers/trainer.py, optimum/habana/trl/trainer/dpo_trainer.py, optimum/habana/trl/trainer/sft_trainer.py
Recent versions of `transformers` deprecated the usage of `Trainer.tokenizer` in favor of `Trainer.processing_class`. However, the property method of the tokenizer attribute triggers a `logging.warning` each time the property is accessed. This causes the script output to be flooded with these tokenizer warnings. Until the next `transformers` upgrade, we want to silence these warnings.
=> Silence `Trainer.tokenizer` warnings

optimum/habana/transformers/models/mllama/modeling_mllama.py
https://github.com/habana-internal/optimum-habana-fork/pull/260
This PR fixes a `RuntimeError` encountered during generation 
```
RuntimeError: unsupported operation: some elements of the input tensor and the written-to tensor refer to a single memory location. Please clone() the tensor before performing the operation.
```
This error originates from the `_update_model_kwargs_for_generation` method in `modeling_mllama.py`, where the following in-place operation is performed:
```python
cross_attention_mask_prev.index_copy_(1, token_idx - 1, mask)
```
In certain scenarios, the `mask` tensor and `cross_attention_mask_prev` can share overlapping memory. Performing in-place writes under such conditions is not supported by PyTorch, as it can lead to undefined behavior or memory corruption.
--- …
=> Llama 3.2 - Fix the issue for eager mode (#260)

examples/stable-diffusion/README.md, examples/stable-diffusion/text_to_image_generation.py, optimum/habana/diffusers/models/attention_processor.py, optimum/habana/diffusers/pipelines/stable_diffusion_3/pipeline_stable_diffusion_3.py
🚀 Adds distributed CFG inference support for SD3 models and updates documentation
⚡ Replaces standard RMSNorm with Gaudi-optimized RMSNorm in SD3 attention, improving performance
🛠️ Fixes text-to-image sample script to correctly output generated images during multi-card inference
In Optimum-Habana Diffusers, multi-card inference currently spawns independent image generations on each worker, which does not improve performance per device. However, the SD3 pipeline architecture allows for a performance optimization: by leveraging classifier-free guidance (CFG) mode, we can parallelize the conditional and unconditional branches across two devices, yielding up to ~2× speedup per image. This approach is not yet supported in the main Hugging Face Diffusers library (for general GPU usage), making …
=> Enable distributed CFG for SD3 pipeline

examples/text-generation/run_lm_eval.py
This pull request introduces enhancements to the `examples/text-generation/run_lm_eval.py` script, focusing on expanding configuration options, improving generation logic, and optimizing backend behavior for specific model families. The most important changes include adding new parameters for truncation and maximum length, introducing a patched `_model_generate` method, and refining backend behavior for Gemma models.
* Added new optional parameters `truncation` and `max_length` to the `__init__` method to provide more control over text generation behavior. [[1]](diffhunk://#diff-f1cc242d23dabd24c924359e72d7eba31a9edc5c6a589ca3ab8438d7fad8589bR108-R110) [[2]](diffhunk://#diff-f1cc242d23dabd24c924359e72d7eba31a9edc5c6a589ca3ab8438d7fad8589bR131-R144)
* Expanded the default input length …
=> Extra Content: Ifeval and MMLU now better supported

examples/text-generation/run_generation.py
This pull request simplifies the argument parsing logic in `examples/text-generation/run_generation.py` by replacing the custom `StoreTrueFalseAction` class with a new `SetTrueOrFalseOrNone` action. This change reduces complexity and improves maintainability.
* Removed the `StoreTrueFalseAction` class, which handled boolean and optional values for command-line arguments.
* Replaced references to `StoreTrueFalseAction` with `SetTrueOrFalseOrNone` for several arguments (`--flash_attention`, `--flash_attention_recompute`, `--flash_attention_causal_mask`) to streamline the handling of boolean flags.
=> Unify SetTrueOrFalseOrNone and StoreTrueFalseAction

examples/text-generation/run_generation.py, optimum/habana/transformers/generation/utils.py
This pull request focuses on cleaning up redundant code and improving readability in the Habana-related text generation utilities and example scripts. The most important changes involve removing unused variables, redundant imports, and unnecessary debug prints.
* Removed redundant debug print statements in the `generate` function to simplify logging output. (`[[1]](diffhunk://#diff-540800c202278e07e1977ad2ad4b4c7a42e59baf002f99907b728abd99f9bf1fL582-R582)`, `[[2]](diffhunk://#diff-540800c202278e07e1977ad2ad4b4c7a42e59baf002f99907b728abd99f9bf1fL776)`)
* Removed the unused `time` import to clean up the file. (`[optimum/habana/transformers/generation/utils.pyL20](diffhunk://#diff-284d6c109e6788a4405e302113203f6b7e98be68afc7dd3d85b89c6329b9275eL20)`)
* Eliminated the `greedy_first` variable …
=> Remove old 1TL measuring

examples/text-generation/run_generation.py
This pull request updates the dataset handling logic in the `examples/text-generation/run_generation.py` script to include support for the "openorca" dataset alongside the existing "mlcommons" dataset.
Key change:
* Updated the conditional in the `main` function to allow the use of the "openorca" dataset by adding a check for `args.dataset_name == "openorca"`. This ensures that the benchmarking logic can now handle both "openorca" and "mlcommons" datasets.
=> Fix missing openorca dataset

optimum/habana/utils/__init__.py, optimum/habana/utils/misc.py
A previous PR [1] introduced a new package `optimum.habana.utils` which created a conflict with the `optimum/habana/utils.py` file. This commit adds the missing `utils/__init__.py` file and moves the `utils.py` file into the `utils/` module (renamed as `misc.py`).
[1] https://github.com/huggingface/optimum-habana/pull/1926
=> Fix utils package

optimum/habana/utils/__init__.py, optimum/habana/utils/misc.py
A previous PR [1] introduced a new package `optimum.habana.utils` which created a conflict with the `optimum/habana/utils.py` file. This commit adds the missing `utils/__init__.py` file and moves the `utils.py` file into the `utils/` module (renamed as `misc.py`).
[1] https://github.com/huggingface/optimum-habana/pull/1926
=> Fix utils package #2141

examples/image-to-text/run_pipeline.py
With Llama 4 support in Transformers 4.51, there was a change in the `Pipeline` class [1], which causes the pipeline device to be set to `self.model.device`. In the case of Mllama, DeepSpeed is used to create the `.language_model` on HPU, whereas the rest of the model stays on CPU [2]. Hence, always `self.model.device = CPU`, which causes the whole model to be placed back on CPU. This commit explicitly moves the model to HPU, so the pipeline will be also placed on HPU.
[1] https://github.com/huggingface/transformers/pull/37307/files#diff-441f558737166b045444da9c4be81f566b3d69054e8f20e288aed746a691fa61
[2] https://github.com/huggingface/optimum-habana/blob/v1.18.0/examples/image-to-text/run_pipeline.py#L360
=> Fix Mllama model placement

examples/sentence-transformers-training/paraphrases/training_paraphrases.py
The `training_paraphrases.py` script still used the deprecated `evaluation_strategy` keyword instead of `eval_strategy`.
=> Use `eval_strategy` in sentence-transformers-training

examples/stable-diffusion/requirements.txt
Pin opencv version to newer one to W/A incompatibility with newer numpy (2.+)
=> Pin opencv version to 4.10.0.84 to W/A incompatibility with newer numpy.

examples/stable-diffusion/training/README.md, setup.py
This PR upgrades the diffuser versions to the latest (as of date) upstream: https://github.com/huggingface/diffusers/releases
The following tests have been conducted to make sure the upgrade is functional:
- g2: CI#184
- g3: CI#49 
- g2: example/stable-diffusion/README.md
- g2: example/stable-diffusion/training/README.md
Notes: 
- **All tests passes.** 
- **details: internal ticket HS-6662**
=> Ig/diffuser 0.34.0

setup.py
With the merge of [1], the patching in `modeling_utils.py` causes a series of imports which eventually tries to import `sentencepiece`. Hence, now `sentencepiece` is now a required package.
[1] https://github.com/huggingface/optimum-habana/pull/1719
=> Add `sentencepiece` to setup.py

tests/test_text_generation_example.py
This PR is a minor fix for testing. It adds the `PT_HPU_LAZY_MODE=1` env variable when testing in lazy mode with HPU graph
```sh
>>> python -m pytest tests/test_text_generation_example.py::test_text_generation_fp8[meta-llama/Llama-2-70b-hf-4-3042-False-128-128]
[2025-07-18 21:14:24,426] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 289416
[2025-07-18 21:14:24,428] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 289417
[2025-07-18 21:14:24,428] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 289418
[2025-07-18 21:14:24,428] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 289419
[2025-07-18 21:14:24,428] [ERROR] [launch.py:325:sigkill_handler] ['/usr/bin/python3', '-u', '/root/optimum-habana/examples/text-generation/run_generation.py', …
```
=> Add the PT_HPU_LAZY_MODE=1 env variable when testing in lazy mode

Makefile, examples/trl/requirements.txt
tldr; with diffuser update to 0.34.0 #2152 the min  requirement for perf is bumped to 0.15.0. trl uses diffuser pipelines and we are bumping the peft version accordingly.
- trl config https://github.com/huggingface/trl/blob/main/setup.cfg suggests anything that 0.8.0 should be fine. 
- **Details of issue: https://github.com/huggingface/optimum-habana/pull/2152#issuecomment-3085914032**
```
ImportError: peft>=0.15.0 is required for a normal functioning of this module, but found peft==0.12.0.
```
- `python -m pytest tests/test_examples.py::MultiCardSFTChatExampleTester::test_sft_Qwen2-7B_multi_card` 
- local job
- passes
- no perf regression (on G2). 
- `python -m pytest tests/test_trl.py`:
- local job
- passes
- no perf regression (on G2).
- CI: G2#185 
- passes 
- no perf regression
- …
=> fea(trl): updated peft version

examples/text-generation/requirements_lm_eval.txt
For lm_eval (i.e. text-generation examples), we have tasks that can work with datasets 4.0.0.
This PR pins datasets, so the tests pass for 1.18.1. Until final solution is delivered.
=> Pin datasets for text-generation/lm_eval example

examples/question-answering/run_qa.py, examples/speech-recognition/run_speech_recognition_ctc.py, examples/stable-diffusion/training/textual_inversion.py, examples/stable-diffusion/training/train_dreambooth.py, examples/stable-diffusion/training/train_dreambooth_lora_sd3.py, examples/stable-diffusion/training/train_dreambooth_lora_sdxl.py, examples/stable-diffusion/training/train_text_to_image_sd3.py, optimum/habana/peft/peft_model.py, optimum/habana/transformers/generation/utils.py, optimum/habana/transformers/gradient_checkpointing.py, optimum/habana/transformers/models/bloom/modeling_bloom.py, optimum/habana/transformers/models/chatglm/modeling_chatglm.py, optimum/habana/transformers/models/deepseek_v2/modeling_deepseek_v2.py, optimum/habana/transformers/models/deepseek_v3/modeling_deepseek_v3.py, optimum/habana/transformers/models/minicpm/modeling_minicpm.py, optimum/habana/transformers/models/modeling_all_models.py, optimum/habana/transformers/models/qwen2_moe/modeling_qwen2_moe.py, optimum/habana/transformers/models/qwen3_moe/modeling_qwen3_moe.py, optimum/habana/transformers/models/t5/modeling_t5.py, optimum/habana/transformers/trainer.py, optimum/habana/transformers/training_args.py, optimum/habana/trl/models/modeling_sd_base.py, optimum/habana/trl/trainer/dpo_trainer.py, optimum/habana/trl/trainer/ppo_config.py, optimum/habana/trl/trainer/ppo_trainer.py, optimum/habana/trl/trainer/sft_trainer.py, optimum/habana/utils/__init__.py, optimum/habana/utils/warn0.py
This PR introduces a new utility function `warn0`, which wraps `warnings.warn` to ensure that warnings are only emitted on the main process (rank 0). This helps reduce noise in distributed training environments.
- Added `warn0` to `optimum/habana/utils/warn0.py`
- Replaced instances of `warnings.warn` in the code with `warn0`
- Ensured compatibility with `PartialState` for rank detection
In distributed training, emitting the same warning from every process can clutter logs and make debugging harder. This change ensures that warnings are only shown once, from the main process.
```python
from optimum.habana.utils import warn0
warn0("This warning will only appear on rank 0.")
```
=> Add warn0 utility to emit warnings only on main process

examples/text-to-speech/requirements.txt, examples/translation/requirements.txt
The pinned datasets versions for `text-to-speech` and `translation` examples caused the scripts to fail with `UTF-8` decode errors. Upgrading the version to `3.6.0` fixes this problem.
=> Update datasets to `3.6.0` in text-to-speech and translation

examples/trl/README.md, tests/test_examples.py
This commit removes the use of the `DEEPSPEED_HPU_ZERO3_SYNC_MARK_STEP_REQUIRED` environment variable, which was previously used as a workaround for HPU in DeepSpeed. As of DeepSpeed v1.16.0, this workaround has been removed and is no longer necessary.
=> Remove DEEPSPEED_HPU_ZERO3_SYNC_MARK_STEP_REQUIRED

examples/text-generation/model_adapter.py, examples/text-generation/run_lm_eval.py
To separate dependencies and make managing imports order easier, HabanaModelAdapter is extracted and moved to model_adapter.py. This allows us to cleanly initialize model and environmental variables before importing lm_eval, transformers and torch, all of which in turn load habana shared object, which needs to happen after env vars are prepared.
This fixes `RuntimeError: collective nonSFG is not supported during hpu graph capturing` in multiple workloads running lm_eval.
=> Extract HabanaModelAdapter from run_lm_eval to new script file.

tests/transformers/tests/models/wav2vec2/test_modeling_wav2vec2.py
Following PR [1], the `is_pt_flax_cross_test` mark was removed. This commit applies the same changes for the `wav2vec` tests [2].
[1] https://github.com/huggingface/transformers/pull/36283/
[2] https://github.com/huggingface/transformers/pull/36283/files#diff-1063ef75ba73fe97fec48faf71f5020152ca85811784caaef74d4ca18fc6049f
=> Remove 'is_pt_flax_cross_test` from `wav2vec` tests

tests/transformers/tests/test_modeling_common.py
Since Transformers 4.51, the `.from_pretrained` method includes model prefixes when reporting missing parameters. Following PR [1], this commit aligns the `test_model_weights_reload_no_missing_tied_weights` test to account for the new prefix behaviour.
[1] https://github.com/huggingface/transformers/pull/36033
=> Fix `test_model_weights_reload_no_missing_tied_weights`

examples/image-to-text/run_pipeline.py
Move some imports from global script scope to local function scope to aviod loading habana shared object before env vars are initialized in examples/image-to-text/run_pipeline.py script.
Fixes # `RuntimeError: collective nonSFG is not supported during hpu graph capturing` error when running tests using run_pipeline.py script from examples/image-to-text.
=> Move torch, transformers and optimum.habana imports to local scope.

tests/transformers/tests/models/deepseek_v3/test_modeling_deepseek_v3.py
This PR ports DeepSeek V3 model testing to the optimum-habana library for G2 hardware acceleration. The testing suite provides comprehensive coverage for the DeepSeek V3 model implementation on Habana Processing Units (HPUs).
Key changes:
Added complete test suite for DeepSeek V3 model with HPU-specific adaptations
Configured HPU device targeting and Habana-specific transformers integration
=> transformer deepseek-v3 Porting to optimum-habana

examples/text-generation/run_lm_eval.py
Check if output directory exists, and create it if it doesn't, before trying to write to output file, in order to properly output results to user-specified path, even if it doesn't exist.
=> Ensure output directory exists before trying to write to output file.

optimum/habana/transformers/models/chatglm/modeling_chatglm.py, optimum/habana/transformers/models/falcon/modeling_falcon.py, optimum/habana/transformers/models/glm4v/modeling_chatglm.py, optimum/habana/transformers/models/llava/modeling_llava.py, optimum/habana/transformers/models/llava_next/modeling_llava_next.py, optimum/habana/transformers/models/llava_onevision/modeling_llava_onevision.py, optimum/habana/transformers/models/mpt/modeling_mpt.py, optimum/habana/transformers/models/phi/modeling_phi.py, optimum/habana/transformers/models/starcoder2/modeling_starcoder2.py
Removing blocks of dead code:
* transformers/models/glm4v/modeling_chatglm.py
* transformers/models/chatglm/modeling_chatglm.py
`combined_attention_mask = (expanded_attn_mask if combined_attention_mask is None else expanded_attn_mask + combined_attention_mask)` is after `if attention_mask is not None:`
* transformers/models/falcon/modeling_falcon.py
`if token_idx is not None` is in a block executed only if `token_idx is not None`
* transformers/models/llava/modeling_llava.py
```
loss = None
[...]
return (loss,) + output if loss is not None else output
```
* transformers/models/llava_next/modeling_llava_next.py
if token_idx is None:
[...]
else:
legacy_processing = [...] (input_ids.shape[-1] == 1 if token_idx is None else token_idx == 1)
[...]
* …
=> Remove instances of logically dead code

optimum/habana/diffusers/pipelines/flux/pipeline_flux.py, optimum/habana/diffusers/pipelines/flux/pipeline_flux_img2img.py
Fix instances where there's a possibility to access a variable that is uninstantiated or None.
`transformer_bf16` is defined only when `if quant_mode == "quantize-mixed"`. Adding the condition before `transformer_bf16` is called ensures that there is no way it will be called uninstantiated.
=> Fixes for bad use of potential None value

optimum/habana/transformers/models/qwen3/modeling_qwen3.py, optimum/habana/transformers/models/qwen3_moe/modeling_qwen3_moe.py
max_position_embeddings is not initialized in qwen3 and qwen3_moe attention, which will cause failure in generation when self.config.max_position_embeddings < calculated_max_length.
=> qwen3: Fix missing max_position_embeddings init from config

examples/text-generation/utils.py
(cherry picked from commit f210ebf2606502bef8f749d81bf3bb7f9cf56136)
This is cherry-pick of PR #2032
Make sure that PT_HPU_LAZY_MODE env variable is set to proper value when running --torch_compile
This PR replaces #2032
=> Fix PT_HPU_LAZY_MODE assertion to match updated default value

examples/text-generation/run_generation.py, examples/text-generation/utils.py
Description:
This PR introduces a new command-line argument --dynamo_allow_unspec_int_on_nn_module to enable the torch._dynamo.config.allow_unspec_int_on_nn_module flag in text generation tests.
Changes:
Added CLI argument --dynamo_allow_unspec_int_on_nn_module with store_true action.
=> Add support for --dynamo_allow_unspec_int_on_nn_module option in text generation tests

examples/image-classification/run_image_classification.py, examples/language-modeling/run_clm.py, examples/language-modeling/run_mlm.py, examples/text-classification/run_glue.py, optimum/habana/transformers/trainer.py, tests/test_trainer.py
Extract of https://github.com/huggingface/optimum-habana/pull/2209 related to removal of `.keys()` calls when iterating over dicts
=> [Transformers 4.55] Do not use `.keys()` on dicts

examples/question-answering/run_qa.py, optimum/habana/transformers/generation/utils.py, optimum/habana/transformers/loss/loss_rt_detr.py
Extract of https://github.com/huggingface/optimum-habana/pull/2209 related to typo fixes
=> [Transformers 4.55] Fix typos

examples/text-generation/run_generation.py
The current implementation of `run_generation.py` does not take into account the value of `--dataset_max_samples` when using an MLCommons dataset (via the `--mlcommons_dataset` argument). Limiting the number of dataset samples allows for faster debugging.
=> Respect `--dataset_max_samples` when using `--mlcommons_dataset`

optimum/habana/transformers/trainer.py
When running a script on multiple HPUs using MPI, the script hangs. An investigation releaved that the problem is related to a `barrier` in the `Trainer` code [1], i.e., not all processes reach this barrier. In fact, the `self.state.best_model_checkpoint` is only set in certain process, whereas in other ones the variable is set to `None`. The variable should be set by the `_save_checkpoint` method [2] (which is in turn called by the `_maybe_log_save_evaluate` method [3]). Debugging showed that when different processes call the `os.path.exists(best_checkpoint_dir)` function [4], they get random results (sometimes it returns true, always a different subset of processes). This shows that there is a race condition on this directory check - i.e., a process (probably rank zero) writes the model …
=> Synchronize processes when saving model

examples/image-classification/README.md
One of the examples in image-classification README failed with an exception. The fix requires that train and eval batch sizes are be equal.
=> [image-classification] README example fix

tests/test_habana_profiler_unit.py
This pull request updates the Habana profiler unit tests to reflect changes in how multiple profiler instances are managed. The most important changes include switching from a list to a `WeakSet` for tracking profiler instances and updating test logic to match the new behavior where starting a new profiler stops any previous one.
**Profiler instance management:**
* Changed the storage of active profiler instances in `HabanaProfile._profilers` from a list to a `weakref.WeakSet` to better manage memory and object lifecycle. [[1]](diffhunk://#diff-a8dad2c65ab7f11000e93566d0a696d5e8e23598d01e53fdbfacf978b0562281R18) [[2]](diffhunk://#diff-a8dad2c65ab7f11000e93566d0a696d5e8e23598d01e53fdbfacf978b0562281L47-R48)
**Test behavior updates:**
* Updated the test to verify that starting a new …
=> Fix HabanaProfile unit tests to align with idempotent start behavior

optimum/habana/transformers/trainer.py
Seems like we still can't remove this autocast manager for now, there a few edge cases where the performance seems to be degraded when this manager is not overwritten with custom hpu logic, however this shouldn't be the cases because transformers no longer handles autocast with this function but rather rely on accelerate with forward wrapper.
=> Revert transformers autocast_smart_context_manager

README.md, examples/README.md, examples/contrastive-image-text/README.md, examples/image-to-text/README.md, examples/language-modeling/README.md, examples/multi-node-training/README.md, examples/sentence-transformers-training/README.md, examples/sentence-transformers-training/nli/README.md, examples/sentence-transformers-training/sts/README.md, examples/speech-recognition/README.md, examples/summarization/README.md, examples/text-generation/README.md, examples/trl/README.md
This PR changes static links pointing to main branch contents, located in READMEs and docs, into relative ones, which automagically point to current branch contents.
This removes the need to update links during branchout.
Branch v1.20-release has already updated the links where necessary, so this change doesn't need to be cherry-picked.
=> Change static to relative links in READMEs and docs.

optimum/habana/transformers/generation/utils.py
This is W/A for not having properly assigned static_shapes property of generation_config.
This should unblock CI runs of Model Llama 3-2-11B 2048/2048 Tokens bfloat16 tests, which have been failing for some time now.
=> Check if generation_config has attr 'static_shapes' before accessing value

optimum/habana/transformers/modeling_utils.py, optimum/habana/transformers/pipelines/__init__.py, optimum/habana/transformers/pipelines/image_to_text.py
With transformers updated to 4.55.4, there are changes in pipeline init method and causes error in optimum-habana when using pipeline for multi-modal inference, error log shown below:
> Traceback (most recent call last):
File "/workspace/optimum-habana/examples/image-to-text/run_pipeline.py", line 533, in <module>
main()
File "/workspace/optimum-habana/examples/image-to-text/run_pipeline.py", line 375, in main
generator = pipeline(
File "/usr/local/lib/python3.10/dist-packages/transformers/pipelines/__init__.py", line 1210, in pipeline
return pipeline_class(model=model, framework=framework, task=task, **kwargs)
File "/usr/local/lib/python3.10/dist-packages/transformers/pipelines/image_to_text.py", line 85, in __init__
super().__init__(*args, **kwargs)
File …
=> fix for GenerationConfig issue for pipeline init changes by transformers update

tests/test_bnb_qlora.py
test_bnb_qlora.py fails due to following 2 issues,
(1)  "ImportError: cannot import name '_reverse_4bit_compress_format' from 'bitsandbytes.utils'"
(2)  "/usr/local/lib/python3.10/dist-packages/accelerate/accelerator.py:1783: TypeError " 
Issue (1) will get fixed with this PR https://github.com/bitsandbytes-foundation/bitsandbytes/pull/1757 in bitsandbytes.
Issue (2) is fixed in this PR by allowing device_map to be automatically detected for Gaudi.
=> Fix QLoRA test

optimum/habana/transformers/models/gpt_bigcode/modeling_gpt_bigcode.py
Between transformers versions v4.53 and v4.54, a major refactor of GPTBigCodeAttention was made. This caused our GaudiBPTBigCodeAttention implementation incompatible.
This PR backports `_get_mask_value()` function from version v4.53, as well as overwrites `attn_dropout` property to make it an operator once again, as it was being stored as a scalar in v4.54+, and used in new `forward()` implementation differently than before.
This reenables text generation using bigcode, i.e:
`cd examples/text-generation`
`pip install -r requirements.txt`
`export PT_HPU_ENABLE_REFINE_DYNAMIC_SHAPES=1`
`PT_HPU_LAZY_MODE=1  python3 ../gaudi_spawn.py  --world_size 1 run_generation.py --batch_size 1 --bf16 --model_name_or_path bigcode/starcoder --use_hpu_graphs --use_kv_cache --n_iterations 1 --max_new_tokens …
=> Backport GPTBigCodeAttention from v4.53.0 to avoid major refactoring.

optimum/habana/transformers/models/mllama/modeling_mllama.py
These are fixes for functional errors which cropped up after transformers upgrade.
To reproduce:
```
PT_HPU_LAZY_MODE=1  python3  $OPTIMUM_HABANA/examples/image-to-text/run_pipeline.py    --model_name_or_path meta-llama/Llama-3.2-11B-Vision-Instruct   --use_hpu_graphs --limit_hpu_graphs --use_kv_cache --max_new_tokens 2048 --bf16 --batch_size 16  --use_flash_attention --flash_attention_recompute    --sdp_on_bf16 --logits_bf16 --trim_logits --max_input_tokens 2048    --ignore_eos
```
The example above requires also https://github.com/huggingface/optimum-habana/pull/2266/files to be applied.
=> [mllama] Minor fixes after transformers upgrade

optimum/habana/accelerate/accelerator.py
=> Fast ddp in prepare_model

optimum/habana/transformers/models/gpt_bigcode/modeling_gpt_bigcode.py
Pass `training` parameter to dropout in BigCodeAttention, which was omitted in previous change.
=> Properly apply dropout in GPTBigCode only when in training.

examples/audio-classification/requirements.txt, examples/audio-classification/run_audio_classification.py, tests/configs/examples/ast_finetuned_speech_commands_v2.json, tests/configs/examples/wav2vec2_base.json, tests/test_examples.py
This PR addresses compatibility issues with datasets>=4.0.0 by:
Dataset Migration
- Replaced the legacy anton-l/common_language dataset with a Parquet-converted version (regisss/common_language), which is fully supported under datasets v4.0.0.
- Ensures training, validation, and test splits are properly mapped without relying on trust_remote_code.
Audio Decoding
- The previous decoding mechanism expected an array field (auto-decoded audio). In datasets v4.0.0, decoding is disabled for performance and compatibility with HPUs.
- Introduced an explicit decoding step using SoundFile, handling both file paths and in-memory bytes.
- Added downmix to mono and validation of sample rates to ensure consistency with the feature extractor.
-
=> Migrate common_language dataset to Datasets v4.0.0 and switch audio decoding to SoundFile

examples/text-classification/requirements.txt
This PR updates the requirements to enforce evaluate>=0.4.5, as older versions of the library crash during metric computation when used together with datasets>=4.0.0.
After upgrading datasets from 3.6.0 to 4.0.0, evaluation on GLUE tasks started failing with evaluate==0.4.3 (and reproducible with 0.4.4). The issue occurs inside the simple_accuracy function of the GLUE metric:
`AttributeError: 'bool' object has no attribute 'mean'`
The problem was observed when running MRPC evaluation with Habana trainer: 
`"path": "/root/optimum-habana-fork/examples/text-classification",
"command": "PT_HPU_LAZY_MODE=1  python3 run_glue.py --task_name mrpc --learning_rate 3e-5 --max_seq_length 128 --output_dir ./output/mrpc/ --use_hpu_graphs_for_inference  --model_name_or_path …
=> Fix(requirements): set evaluate>=0.4.5 to resolve GLUE crash with datasets>=4.0.0

optimum/habana/transformers/models/deepseek_v2/modeling_deepseek_v2.py, optimum/habana/transformers/models/gemma/modeling_gemma.py, optimum/habana/transformers/models/gemma2/modeling_gemma2.py, optimum/habana/transformers/models/llama/modeling_llama.py, optimum/habana/transformers/models/mistral/modeling_mistral.py, optimum/habana/transformers/models/mixtral/modeling_mixtral.py, optimum/habana/transformers/models/qwen2_moe/modeling_qwen2_moe.py, optimum/habana/transformers/models/qwen3/modeling_qwen3.py
The statement `next_decoder_cache = () if not use_new_cache else None` was always evaluating to () because `use_new_cache` is hardcoded to False, making `not use_new_cache` always True.
Similar thing happens for optimum/habana/transformers/models/mistral/modeling_mistral.py, where there is even more dead code because of hardcoded `use_new_cache`.
This PR allows as to pass security scans required for the release.
=> Fix next_decoder_cache formula based on use_new_cache after tranformers 4.55 upgrade

examples/text-generation/run_generation.py
This PR updates the text-generation example (run_generation.py) to set --dynamo_allow_unspec_int_on_nn_module to True by default.
In PyTorch 2.8, torch._dynamo.config.allow_unspec_int_on_nn_module needs to be explicitly enabled to restore the behavior from PT 2.7.1 and reduce unnecessary recompilations.
Previously, the flag existed in the example but defaulted to False unless explicitly passed.
With this change, the flag is automatically enabled for all text-generation tests and benchmarks, ensuring consistent and stable execution without requiring QA or users to modify their configs.
Users can still override the behavior by explicitly setting --no-dynamo_allow_unspec_int_on_nn_module if needed.
This aligns the text-generation example with the recommended configuration for PT 2.8+
=> Enable --dynamo_allow_unspec_int_on_nn_module by default in text-generation example

examples/question-answering/requirements.txt
This PR updates the evaluate package version in
`examples/question-answering/requirements.txt` from 0.4.3 to 0.4.5
to align it with `examples/text-classification/requirements.txt`
on the master_next branch.
Background:
- The previous mismatch between 0.4.3 (QA) and 0.4.5 (Text Classification)
caused dependency conflicts in CI:
`Cannot install evaluate==0.4.3 and evaluate==0.4.5`.
Changes:
- Updated evaluate==0.4.3 → evaluate==0.4.5 in question-answering requirements.
- No functional code changes, only dependency alignment.
This resolves the version conflict reported in the
`Test_pytorch_training_tests_gaudi2_asic_8cards_topology_8cards_master_next`
job and ensures consistent dependency management across examples.
=> Align evaluate version to 0.4.5 in question-answering requirements
